Add spectral rules #20
aliencube/azure-openai-sdk-proxy pull request #229
Opened 2024-08-18 07:41 UTC by tae0y

related to #20, #21
필수 필드를 지정하고, 해당 필드가 없을 경우 에러를 발생시키도록 수정

spectral openapi 기본 룰셋을 확장해서
현재 기준으로 엔드포인트별 필수 필드를 지정하고
없을 경우에는 warn 대신 error를 발생시키도록 했습니다
(세부내용은 `.spectral.yaml` 각주에 기재해두었습니다!)

2024-08-18 07:52 UTC, justinyoo requested changes
좋습니다! 이 커스텀 룰셋을 로컬에서 테스트해 보려면 각 규칙별로 어떻게 해야 하는지를 PR 본문에 적어주시면 좋겠습니다.

2024-08-18 07:52 UTC, justinyoo commented on .spectral.yaml
> +extends:
맨 윗줄에 아래 주석 하나만 추가해 주세욥:

`# Source: https://docs.stoplight.io/docs/spectral/4dec24461f3af-open-api-rules`

2024-08-18 07:52 UTC, justinyoo commented on .spectral.yaml
> +  api-version-convention:
각각의 규칙을 로컬에서 테스트 해 보려면 어떤 것을 없앤다거나 하는 게 있는지 PR 본문에 적어주세요.

2024-08-18 08:07 UTC, justinyoo requested changes

2024-08-18 08:07 UTC, justinyoo commented on .spectral.yaml
> +        message: Parameters are required
- 파라미터는 header, query, path 이 세가지인데, 모두 정의되어 있지 않아도 유효할 것 같은데, 그럼에도 불구하고 warning을 주는 것이 맞을까요?
- 혹시 path parameter가 있을 경우에만 parameters의 path 항목이 필수로 정의하는 형태로 바꿀 수 있을까요?

2024-08-18 08:07 UTC, justinyoo commented on .spectral.yaml
> +        message: Content is not required when response code is 401
요 내용은 이전 내용을 덮어씌우는 것 같은데... 401 상황에만 특정할 수 있게 할 수 있을까요?

2024-08-18 09:54 UTC, tae0y commented on .spectral.yaml
> +  api-version-convention:
테스트 방법을 PR 본문에 추가했습니다!

2024-08-18 10:01 UTC, tae0y commented on .spectral.yaml
> +        message: Content is not required when response code is 401
규칙을 오버라이드 하려는 목적이었는데, 테스트시 잘 동작하지 않아 아래와 같이 수정했습니다
given절에서 401을 제외한 항목에만 적용되도록 수정했습니다
```
  # 401을 제외한 모든 응답 코드는 content를 포함해야함
  operation-responsedetail-content-convention:
    description: All Operation response might include content, except 401
    given: $.paths[*][*].responses[?(@property != '401')]
    severity: error
    then:
      - field: 'content'
        function: truthy
        message: Content is required
```

2024-08-18 10:34 UTC, tae0y commented on .spectral.yaml
> +        message: Parameters are required
- 조사해보니 내장 규칙에서 `spectral(path-params)` path parameters를 검사하고 있고,
- 메서드 시그니처에 path parameters를 선언해두면 암시적으로 swagger에 해당 항목이 생성됩니다

그래서 커스텀 규칙을 삭제하고, PR 본문의 테스트 항목을 수정했습니다 ~

2024-08-19 02:25 UTC, justinyoo requested changes
몇가지 불필요한 규칙만 삭제하면 될 듯 싶습니다.

2024-08-19 02:25 UTC, justinyoo commented on .spectral.yaml
> +        message: Request body is required
이 부분은 POST 리퀘스트일 경우 암묵적으로 Swashbuckle이 자동으로 생성해 주기 때문에 항상 존재하는 것이니 필요 없을 듯 합니다.

2024-08-19 02:25 UTC, justinyoo commented on .spectral.yaml
> +        message: Description is required
여기도 Swashbuckle이 자동으로 생성해 주는 부분이라 필요 없을 듯?

2024-08-19 02:25 UTC, justinyoo commented on .spectral.yaml
> +  # 규칙관리를 위해 각주만 유지, spectral(path-params)에서 이미 검사중임
이건 굳이 필요 없지 싶습니다.

2024-08-19 03:31 UTC, tae0y commented on .spectral.yaml
> +        message: Request body is required
해당규칙 삭제했습니다

2024-08-19 03:31 UTC, tae0y commented on .spectral.yaml
> +        message: Description is required
규칙 삭제했습니다!

2024-08-19 03:31 UTC, tae0y commented on .spectral.yaml
> +  # 규칙관리를 위해 각주만 유지, spectral(path-params)에서 이미 검사중임
각주 제거했습니다 !

2024-08-19 03:38 UTC, justinyoo approved these changes
LGTM @tae0y 수고하셨습니다!

2024-08-19 03:38 UTC, merged