Add Get event details endpoint by admin
aliencube/azure-openai-sdk-proxy pull request #231
Opened 2024-08-18 09:35 UTC by juhangil

#207 
- Get: Event details by admin endpoint class 추가
- Url constant 추가
- Response dto 추가

러프하게 작업을 진행해봤습니다
혹시 방향성이 맞을까요?

2024-08-18 13:38 UTC, justinyoo requested changes
@juhangil 첫 시작이 아주 좋습니다! 코멘트 남겨뒀구요, 이와 관련해서 테스트 코드도 좀 만들어 볼까요?

만약 테스트 코드 짜는 게 감이 안오면 말씀해 주세요.

2024-08-18 13:38 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEventDetailsEndpoint.cs
> +            }
#207 이슈는 여기 20-43 라인과 실제 구현을 고려하지 않습니다. 여기서는 간단하게 `return Results.OK()` 정도로만 넣어도 무방해요. 그 다음 이슈에서 실제로 구현을 할 겁니다.

2024-08-18 13:38 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEventDetailsEndpoint.cs
> +            [FromRoute] string eventID,
`eventID` 대신 `eventId` 로 바꾸겠습니다

2024-08-18 13:38 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Endpoints/EndpointUrls.cs
> +    public const string AdminEventDetails = "/admin/events/{eventID}";
`eventID` 대신 `eventId` 로 바꾸겠습니다

2024-08-18 13:38 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Endpoints/EndpointUrls.cs
> +    public const string AdminEventDetails = "/admin/events/{eventID}";
그리고 혹시 가능하다면 `AdminEventUrls.cs` 파일을 별도로 만들어서 관리하는 것이 어떨까요?

2024-08-18 13:38 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Models/AdminEventDetails.cs
> +}
지금 API 설계를 하는 부분이니까, 실제 이벤트 내용에 들어갈 항목들이 `EventId` 이외에 더 필요할 것 같은데, 이 부분에 대한 고민을 먼저 해 보면 좋을 것 같습니다.

어떤 데이터가 필요할 것 같은가요? * 마크 있는 항목은 필수 항목

- ID: EventId *
- 제목: Title *
- 요약 (마크다운): Summary *
- 상세 (마크다운): Description
- 시작: DateStart *
- 종료: DateEnd *
- 타임존: TimeZone *
- 활성 여부: IsActive *
- 이벤트 소유자: OrganizerName *
- 이벤트 소유자 Email: OrganizerEmail *
- 이벤트 부소유자: CoorganizerNames
- 이벤트 부소유자 Email: CoorganizerEmails
- 1회 최대 토큰 크기: MaxTokenCap *
- 1일 최대 요청 횟수: DailyRequestCap *

이 정도면 충분할 것 같은데, 혹시 더 있으려나?

2024-08-18 13:38 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEventDetailsEndpoint.cs
> +            operation.Description = "Get event details by event id, api for admin users";
- Summary: "Gets event details from the given event ID"
- Description: "This endpoint gets the event details from the given event ID."

2024-08-18 13:38 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEventDetailsEndpoint.cs
> +public static class AdminEventDetailsEndpoint
이벤트 전반의 엔드포인트가 다 여기에 들어갈 듯 하니 `AdminEventDetailsEndpoints` 라고 하면 어떨까요?

2024-08-18 13:38 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEventDetailsEndpoint.cs
파일 이름을 `AdminEventDetailsEndpoints.cs` 라고 바꿔볼까요?

2024-08-18 13:45 UTC, juhangil commented on src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEventDetailsEndpoint.cs
> +public static class AdminEventDetailsEndpoint
그러면 URL 파일하고 네이밍을 맞추게 AdminEvnetEndpoints라고 해도 괜찮을까요?

2024-08-18 15:10 UTC, justinyoo requested changes

2024-08-18 15:10 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEventEndpoints.cs
> +    public static RouteHandlerBuilder AddAdminEventDetails(this WebApplication app)
여기 메소드 이름도 `AddAdminEvents` 쯤으로 바꾸면 좋겠습니다

2024-08-18 15:10 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Program.cs
> +#endregion
`#region ... #endregion` 을 쓰는 건 안티패턴이라 그냥 줄바꿈 정도로하고 윗줄에 `//` 주석으로 여기부터는 어드민 엔드포인트다~ 하고 표시하는 게 좀 더 낫겠습니다.

2024-08-19 08:03 UTC, justinyoo requested changes

2024-08-19 08:04 UTC, justinyoo commented
좋은데요? 응답 페이로드만 고민해 보면 될 듯 합니다.

2024-08-19 08:08 UTC, juhangil commented
> 좋은데요? 응답 페이로드만 고민해 보면 될 듯 합니다.

네 모델이랑 테스트 적용해서 완료되면 추가로 커밋하겠습니다

2024-08-19 09:00 UTC, SeungHuLee commented on test/AzureOpenAIProxy.AppHost.Tests/ApiApp/Endpoints/AdminGetEventEventDetailsOpenApiTests.cs
테스트 파일과 클래스의 제목 AdminGetEventEventDetailsOpenApiTest 를 AdminGetEventDetailsOpenApiTest 로 바꾸면 어떨까요?

2024-08-19 11:52 UTC, juhangil commented
@justinyoo 요청하신 변경사항이랑 페이로드 정의 후 테스트 적용하였습니다

2024-08-19 15:26 UTC, justinyoo requested changes

2024-08-19 15:26 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Models/AdminEventDetails.cs
> +}
다른 클래스와 속성을 참고해서 클래스와 각각의 속성에 `///` 형태의 주석을 달아주세요.

2024-08-19 15:26 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Models/AdminEventDetails.cs
> +    public DateTime? DateEnd { get; set; }
`DateTime` 보다는 `DateTimeOffset`이 낫습니다.

2024-08-19 15:26 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Models/AdminEventDetails.cs
> +    public int DailyRequestCap { get; set; }
`System.Text.Json` 확인해 보시면 각 속성마다 데코레이터를 달아 필수 항목인지 여부를 지정할 수 있습니다.

2024-08-19 15:26 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Models/AdminEventDetails.cs
> +    public bool IsActive { get; set; }
이것도 `bool?` 로 해 주세요.

2024-08-19 15:26 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Models/AdminEventDetails.cs
> +    public int DailyRequestCap { get; set; }
이것들도 `int?`로 해 주세요.

2024-08-19 15:26 UTC, justinyoo commented on test/AzureOpenAIProxy.AppHost.Tests/ApiApp/Endpoints/AdminGetEventDetailsOpenApiTest.cs
> +        }
테스트에서는 `foreach` 루프를 돌리는 대신, 개별 값을 테스트합니다. 65-84 라인을 참조해 보세요.

2024-08-19 15:26 UTC, justinyoo commented on test/AzureOpenAIProxy.AppHost.Tests/ApiApp/Endpoints/AdminGetEventEventDetailsOpenApiTests.cs
오우 오타가 있었네요. 뉍 그렇게 해 주세요.

2024-08-19 15:28 UTC, justinyoo requested changes

2024-08-19 15:28 UTC, justinyoo commented on test/AzureOpenAIProxy.AppHost.Tests/ApiApp/Endpoints/AdminGetEventDetailsOpenApiTest.cs
> +public class AdminGetEventDetailsOpenApiTest(AspireAppHostFixture host) : IClassFixture<AspireAppHostFixture>
`Tests` 입니다 (복수형)

2024-08-19 15:28 UTC, justinyoo commented on test/AzureOpenAIProxy.AppHost.Tests/ApiApp/Endpoints/AdminGetEventDetailsOpenApiTest.cs
파일 이름도 역시 `Tests.cs` 입니다 (복수형)

2024-08-20 07:38 UTC, justinyoo requested changes
마지막 리뷰가 될 것 같은데, 코드 청소용입니다.

2024-08-20 07:38 UTC, justinyoo commented on test/AzureOpenAIProxy.AppHost.Tests/ApiApp/Endpoints/AdminGetEventDetailsOpenApiTests.cs
> +    // TODO: Add more tests for the component section
요 주석은 이제 지워도 됩니다.

2024-08-20 07:38 UTC, justinyoo commented on test/AzureOpenAIProxy.AppHost.Tests/ApiApp/Endpoints/AdminGetEventDetailsOpenApiTests.cs
> +                                        .GetProperty(attribute);
거의 다 온 것 같아요. 마지막 knit-picking 이긴 한데, 세로줄 맞추기 하시죠. 다른 메소들도 마찬가지.

2024-08-20 07:40 UTC, justinyoo requested changes

2024-08-20 07:40 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Models/AdminEventDetails.cs
> +    public required string? EventId { get; set; }
아 맞네. 이렇게 `required` 넣는 거랑 `JsonProperty` 같은 형태로 해서 `required = true` 넣는 거랑 어떤 차이가 있을까요?

2024-08-20 07:43 UTC, juhangil commented on src/AzureOpenAIProxy.ApiApp/Models/AdminEventDetails.cs
> +    public required string? EventId { get; set; }
@justinyoo `required` keyword는 컴파일러에서 생성자 초기화를 강제하고 attribute는 하지 않습니다

2024-08-20 07:59 UTC, justinyoo requested changes

2024-08-20 07:59 UTC, justinyoo commented on test/AzureOpenAIProxy.AppHost.Tests/ApiApp/Endpoints/AdminGetEventDetailsOpenApiTests.cs
> +        };
외부에서 이 필드를 참조하지 않는다면 `private static ...` 으로 스코프를 낮추는 게 좋겠습니다.

그리고, 이런 식으로 좀 더 간단하게 작성할 수 있어요:

```csharp
    private static IEnumerable<object[]> AttributeData =>
        [
            [ "eventId", true, "string" ],
            [ "title", true, "string" ],
            [ "summary", true, "string" ],
            [ "description", false, "string" ],
            [ "dateStart", true, "string" ],
            [ "dateEnd", true, "string" ],
            [ "timeZone", true, "string" ],
            [ "isActive", true, "boolean" ],
            [ "organizerName", true, "string" ],
            [ "organizerEmail", true, "string" ],
            [ "coorganizerName", false, "string" ],
            [ "coorganizerEmail", false, "string" ],
            [ "maxTokenCap", true, "integer" ],
            [ "dailyRequestCap", true, "integer" ],
        ];

```

2024-08-20 08:04 UTC, juhangil commented on test/AzureOpenAIProxy.AppHost.Tests/ApiApp/Endpoints/AdminGetEventDetailsOpenApiTests.cs
> +        };
@justinyoo Attribute에서 참조해서 주입하는 데이터라 에러가 발생해 public은 유지해야 할 것 같고 초기화문만 교체하겠습니다

2024-08-20 08:26 UTC, justinyoo requested changes

2024-08-20 08:26 UTC, justinyoo commented on test/AzureOpenAIProxy.AppHost.Tests/ApiApp/Endpoints/AdminGetEventDetailsOpenApiTests.cs
> +using IdentityModel.Client;
요기 한 줄만 띄우고 다시 푸시해 보실래요? 그냥 의미없는 푸시입니다.

2024-08-20 08:30 UTC, merged