[Playground] Component - button to display a given input #171
aliencube/azure-openai-sdk-proxy pull request #236
Opened 2024-08-19 15:19 UTC by o-ii

## Description

Issue #171 

버튼을 클릭하면 파라미터로 전달된 입력값을 화면에 표시하는 UI 컴포넌트를 추가했습니다.

## Summary of Changes

- **DebugButtonComponent 추가**: 'Debug' 버튼을 클릭하면 입력값을 화면에 출력하는 새 컴포넌트를 구현했습니다. 입력값이 없을 경우 'No input provided.'라는 기본 메시지가 표시됩니다.

- **Counter 페이지 업데이트**: `DebugButtonComponent`를 Counter 페이지에 추가하여, 사용자가 선택한 값이 버튼 클릭 시 화면에 표시되도록 구성했습니다.

- **테스트 추가**: 다양한 입력 유형에 대해 컴포넌트가 올바르게 동작하는지 확인하기 위해 [Playwright](https://playwright.dev/dotnet/docs/intro) 테스트를 작성했습니다.

## How to Test

1. 프로젝트를 빌드한 후, **Counter** 페이지로 이동합니다.
2. 제공된 입력 옵션 중 하나를 선택합니다.
3. **Debug** 버튼을 클릭하여 선택한 입력값이 화면에 정확하게 표시되는지 확인합니다.

<img width="496" alt="Screenshot 2024-08-19 at 11 24 03 PM" src="https://github.com/user-attachments/assets/79ecf5af-91b1-4f1d-b134-21844378ac27">

2024-08-20 01:19 UTC, justinyoo requested changes
Playwright 을 로컬에서 테스트하려면 어떻게 하는지에 대한 인스트럭션을 PR 본문에 올려주세요.

그리고 그걸 바탕으로 GitHub Actions workflow 도 업데이트해야 할 거예요.

2024-08-20 01:19 UTC, justinyoo commented on Directory.Build.props
> +    <NUnit3TestAdapterVersion>4.5.*</NUnit3TestAdapterVersion>
메이저 버전만 다루고 나머지는 꼽표 처리하시지욥.

- `1.46.*` 대신 `1.*`  같은 식으로

2024-08-20 01:19 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/DebugButtonComponent.razor
> +<p id="displayText">@displayText</p>
아주 좋습니다! 이제 Blazor Fluent UI https://www.fluentui-blazor.net/ 를 사용해서 조정해 보세요.

2024-08-20 02:17 UTC, justinyoo commented
로컬에서 돌려보니 테스트 실패합니다~

2024-08-20 02:18 UTC, justinyoo commented
카운터 페이지 말고 별도의 페이지를 하나 만들어서 거기서 Fluent UI 레이아웃을 적용해 보는 게 좋을 거예요.

2024-08-22 06:03 UTC, justinyoo commented
코드 컨플릭 났습니다.

1. 로컬에서 컨플릭 해결하세요
2. 로컬에서 테스트 돌려보고 푸시하세요

2024-08-23 08:16 UTC, o-ii commented
> 카운터 페이지 말고 별도의 페이지를 하나 만들어서 거기서 Fluent UI 레이아웃을 적용해 보는 게 좋을 거예요.

별도의 /tests 페이지를 만들어 Playwright E2E 테스트 코드를 작성했습니다.

컴포넌트처럼 Tests 페이지에도 Fluent UI를 적용하려 했으나, [Fluent UI의 RadioGroup 컴포넌트](https://www.fluentui-blazor.net/RadioGroup)가 다양한 타입(double, DateTime 등)을 지원하지 않아서, 다양한 inputType(int, double, string)을 테스트하기 위해 Tests 페이지에는 Fluent UI를 사용하지 않았습니다.

2024-08-23 08:19 UTC, o-ii commented
> Playwright 을 로컬에서 테스트하려면 어떻게 하는지에 대한 인스트럭션을 PR 본문에 올려주세요.
> 
> 그리고 그걸 바탕으로 GitHub Actions workflow 도 업데이트해야 할 거예요.

Playwright 테스트를 로컬에서 실행하는 방법에 대한 인스트럭션을 PR 본문에 추가했습니다.

1. 첫 번째 커밋`Add DebugButton component to display input parameter`에서는 로컬과 GitHub Actions 워크플로우에서 오류 없이 실행되는 **Playwright** (E2E) 테스트를 작성했습니다.

2. 두 번째 커밋`Add unit tests with bUnit for DebugButton component`에서는 **bUnit**을 사용하여 `dotnet run` 없이 컴포넌트만 테스트하는 유닛 테스트 코드를 추가했습니다. 현재 단계에서는 Playwright E2E 테스트보다는 bUnit을 사용한 유닛 테스트가 더 적절하다고 생각하는데, 프론트엔드 관련 코드를 모두 Playwright의 E2E 테스트로 통일하는 것이 좋을까요?

3. 예시로 제공해주신 테스트 코드에서 [Property("Category", "Integration")]를 사용하셨는데, Playwright로 작성한 코드는 모두 Integration 카테고리로 통일하면 될까요? UI 테스트에서 유닛 테스트는 "Unit", 통합 테스트와 E2E 테스트는 "Integration"으로 분류하면 될까요? 어떤 기준으로 카테고리를 작성해야 할지 궁금합니다.

2024-08-23 08:32 UTC, justinyoo commented
> 2. 두 번째 커밋`Add unit tests with bUnit for DebugButton component`에서는 **bUnit**을 사용하여 `dotnet run` 없이 컴포넌트만 테스트하는 유닛 테스트 코드를 추가했습니다. 현재 단계에서는 Playwright E2E 테스트보다는 bUnit을 사용한 유닛 테스트가 더 적절하다고 생각하는데, 프론트엔드 관련 코드를 모두 Playwright의 E2E 테스트로 통일하는 것이 좋을까요?

bUnit은 사용하지 않도록 하겠습니다. bUnit을 쓰게 되면 테스트 프로젝트가 플레이그라운드 프로젝트에 의존성이 생기는데 현재 이 부분에 문제가 있어서요.

> 3. 예시로 제공해주신 테스트 코드에서 [Property("Category", "Integration")]를 사용하셨는데, Playwright로 작성한 코드는 모두 Integration 카테고리로 통일하면 될까요? UI 테스트에서 유닛 테스트는 "Unit", 통합 테스트와 E2E 테스트는 "Integration"으로 분류하면 될까요? 어떤 기준으로 카테고리를 작성해야 할지 궁금합니다.

플레이그라운드 테스트 코드에만 `[Property("Category", "Integration")]` 데코레이터를 사용합니다.

2024-08-23 14:54 UTC, o-ii commented
> bUnit은 사용하지 않도록 하겠습니다. bUnit을 쓰게 되면 테스트 프로젝트가 플레이그라운드 프로젝트에 의존성이 생기는데 현재 이 부분에 문제가 있어서요.

bUnit 테스트를 삭제하고, Playwright 테스트만 유지한 상태로 다시 커밋했습니다.

> 플레이그라운드 테스트 코드에만 [Property("Category", "Integration")] 데코레이터를 사용합니다.

Playwright 테스트용 /tests 페이지를 생성하고, 비어 있는 페이지에 테스트용 컴포넌트를 추가했습니다. 앞으로 다른 플레이그라운드 테스트 코드를 작성할 때, /tests 페이지에서 각 테스트에 개별적으로 접근할 수 있는 [메뉴](https://www.fluentui-blazor.net/NavMenu)를 추가하는 것이 좋을까요? 아니면 모든 테스트 컴포넌트를 한 페이지에 배치하는 방식이 더 효율적일까요?

2024-08-24 01:06 UTC, justinyoo commented
> Playwright 테스트용 /tests 페이지를 생성하고, 비어 있는 페이지에 테스트용 컴포넌트를 추가했습니다. 앞으로 다른 플레이그라운드 테스트 코드를 작성할 때, /tests 페이지에서 각 테스트에 개별적으로 접근할 수 있는 [메뉴](https://www.fluentui-blazor.net/NavMenu)를 추가하는 것이 좋을까요? 아니면 모든 테스트 컴포넌트를 한 페이지에 배치하는 방식이 더 효율적일까요?

현재 상태로 냅두셔도 됩니다. 이건 다른 사람들이 추가하는 컴포넌트 값을 확인하기 위한 테스트용 버튼이고 이 버튼 말고 자기들이 추가하는 컴포넌트와 버튼과 연결시켜서 해당 컴포넌트가 제대로 작동하는지 확인하는 용도기 때문에 궁극적으로는 없어질 컴포넌트입니다.

2024-08-24 01:18 UTC, justinyoo requested changes
코멘트 남겼습니다.

2024-08-24 01:18 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/Tests.razor
> +<DebugButtonComponent Input="@input" />
방향을 바꿔야 할 듯 합니다? 이 버튼이 가리키는 컴포넌트의 현재 값을 가져오는 형태가 되어야지 외부 컴포넌트가 바꾼 상태값을 이 버튼에 보내는 형식이 되어서는 안될 듯?

그렇게 해야, 한 페이지 안에 여러 컴포넌트가 있을 때 각각에 이 버튼을 달고 각 버튼마다 클릭하면 가리키는 컴포넌트의 현재 값을 갖고 오는 방식이 되어야 할 거예요.

2024-08-25 09:13 UTC, o-ii commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/Tests.razor
> +<DebugButtonComponent Input="@input" />
### 1. [코드 설명]

`TargetComponent`에 **EventCallback**을 추가하여, **가리키는 컴포넌트의 현재 값**이 변경될 때마다 `DebugButtonComponent`의 Input 파라미터가 자동으로 업데이트되도록 구성했습니다.

```razor
<TargetComponent OnChangeCallback="OnValueChanged" />
<DebugButtonComponent Input="@currentValue" />

@code {
    private object? currentValue;

    private void OnValueChanged(object newValue)
    {
        currentValue = newValue;
    }
}
```

### 2. [방식 비교]

현재 구현된 방식은 `TargetComponent`의 구체적인 속성명을 알 필요 없이 `DebugButtonComponent`를 사용할 수 있습니다.

```razor
<TargetComponent OnChangeCallback="OnValueChanged" />
<DebugButtonComponent Input="@currentValue" />
```

>  이 **버튼이 가리키는 컴포넌트의 현재 값을 가져오는 형태**가 되어야지 외부 컴포넌트가 바꾼 상태값을 이 버튼에 보내는 형식이 되어서는 안될 듯?

이 형태는 가리키는 **컴포넌트 자체**를 파라미터로 받아서,  `DebugButtonComponent` **내부**에서 값을 조회하라는 의미일까요?

```razor
<TargetComponent @ref="targetComponent" />
<DebugButtonComponent TargetComponent="targetComponent" />
```

이 방식으로 구현하려면 `@using System.Reflection`를 사용해서 `TargetComponent`의 내부 속성에 접근하거나, `TargetComponent`의 내부 구조를 사전에 파악해야 합니다. 이 외에 다른 방법이 있을까요?

### 3. [구현 방향]

데이터 타입(string, int, double)과 반환 방식(public 속성, EventCallback)이 서로 다른 UI 컴포넌트들과 호환 가능한 버튼을 설계하려고 합니다.

현재 코드처럼 `TargetComponent`는 **EventCallback**을 유일한 파라미터로 갖고,

```razor
[Parameter]
public EventCallback<object> OnChangeCallback { get; set; }
```

`DebugButtonComponent`는 **가리키는 컴포넌트의 현재 값**을 파라미터로 받는 형태로 구현하면 될까요?

```razor
[Parameter]
public object? Input { get; set; }
```

2024-08-26 01:13 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/Tests.razor
> +<DebugButtonComponent Input="@input" />
제가 혹시 이 문서 공유했던가요? https://learn.microsoft.com/ko-kr/aspnet/core/blazor/components/event-handling

현재 구현을 보면 `TargetComponent`의 구체적인 구현에 `DebugButtonComponent`가 의존성을 갖는 걸로 보입니다. `TargetComponent`는 사실 뭐가 되어도 상관이 없어야 하고, `TargetComponent`의 현재 상태값 &ndash; 텍스트 인풋이라면 현재 텍스트 인풋값, 드롭다운리스트라면 현재 선택한 값, 라디오버튼리스트라면 현재 선택한 값 등등이 될 수 있겠죠.

이벤트 버블링/터널링 개념을 확인해 보시면 좋을 듯 합니다.

<img width="1384" alt="image" src="https://github.com/user-attachments/assets/760db2be-b690-417c-b6d0-5d8d36933663">

2024-08-26 01:27 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/Tests.razor
> +<DebugButtonComponent Input="@input" />
지금의 문제는 `DebugButtonComponent`가 `TargetComponent`의 값을 직접 핸들링하려는데서 생기는 것 같은데, 그러려면 `DebugButtonComponent`는 `TargetComponent`에 의존성이 생기게 됩니다. 그 의존성을 없애려면 부모 컴포넌트(페이지 컴포넌트)가 핸들링을 해 줘야 할 거예요.

제가 예전에 만들어 둔 샘플입니다:

- https://github.com/devkimchi/Blazor-Code-Behind-Sample/blob/main/BlazorServerApp/Pages/CounterBehind.razor
- https://github.com/devkimchi/Blazor-Code-Behind-Sample/blob/main/BlazorServerApp/Pages/CounterBehind.razor.cs
- https://github.com/devkimchi/Blazor-Code-Behind-Sample/blob/main/BlazorServerApp/Components/CounterComponent.razor
- https://github.com/devkimchi/Blazor-Code-Behind-Sample/blob/main/BlazorServerApp/Components/CounterComponent.razor.cs

이걸 한 번 보시면 대략 감을 잡으실 듯?

2024-08-26 04:32 UTC, o-ii commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/Tests.razor
> +<DebugButtonComponent Input="@input" />
감사합니다!

**현재 코드**가 멘토님이 설명하신 방식을 잘 따르고 있는지, 그리고 개선할 부분이 있는지 검토 부탁드립니다.

_(이전 질문은 **현재 코드**가 적절하지 않을 경우, 다른 구현 방식이 더 적절한지 여쭤본 것이었습니다.)_

### 샘플 코드

공유해주신 샘플 코드는 **부모 컴포넌트**(페이지 컴포넌트)가 **자식 컴포넌트**(타겟 컴포넌트)의 `EventCallback`을 받아 `@CurrentCount`의 값을 업데이트하는 방식으로 구성되어 있습니다.

```razor
@page "/counter-behind"

<h1>Counter</h1>
<p>Current count: @CurrentCount</p>
<CounterComponent StartingCount="0" OnClick="IncrementCount"></CounterComponent>

@code {
    protected int CurrentCount { get; set; } = 0;

    protected void IncrementCount(int count)
    {
        this.CurrentCount += count;
    }
}
```
```razor
<button class="btn btn-primary" @onclick="OnButtonClicked">Click me</button>

@code {
    [Parameter]
    public int StartingCount { get; set; } = 0;

    [Parameter]
    public EventCallback<int> OnClick { get; set; }

    protected async Task OnButtonClicked(MouseEventArgs ev)
    {
        this.StartingCount++;
        await OnClick.InvokeAsync(this.StartingCount).ConfigureAwait(false);
    }
}
```

### 현재 코드

**자식 컴포넌트**(타겟 컴포넌트)는 `EventCallback`을 통해 값의 변경을 외부로 전달하며, 이 값은 **부모 컴포넌트**(페이지 컴포넌트)에서 처리되어 최종적으로 **디버그 컴포넌트**로 전달됩니다. 이 구조는 샘플 코드의 설계 방식처럼 컴포넌트 외부로 값을 전송하고, 페이지를 통해 **간접적으로** 값을 전달합니다.

- 부모 컴포넌트 (페이지 컴포넌트)

```razor
@page "/tests"
@using AzureOpenAIProxy.PlaygroundApp.Components.UI

<TargetComponent OnChangeCallback="OnValueChanged" />
<DebugButtonComponent Input="@currentValue" />

@code {
    private object? currentValue;

    private void OnValueChanged(object newValue)
    {
        currentValue = newValue;
    }
}
```

- 자식 컴포넌트 (타겟 컴포넌트)

```razor
<fieldset>
    <legend>UI Test <a href="https://github.com/aliencube/azure-openai-sdk-proxy/issues/171">#171</a></legend>
@foreach (var option in options)
{
    <div class="form-check">
        <input class="form-check-input" id="@option" type="radio" name="inputType" @onchange="() => OnChangeCallback.InvokeAsync(option)" />
        <label class="form-check-label" for="@option">
            @option
        </label>
    </div>
}
</fieldset>

@code {
    [Parameter]
    public EventCallback<object> OnChangeCallback { get; set; }

    private List<object> options = new()
    {
        123,
        3.14159,
        "Hello, World!",
    };
}
```

- 디버그 컴포넌트
  - `DebugButtonComponent`의 입력 파라미터는 `object` 타입으로, 다양한 유형의 데이터를 받아 출력할 수 있습니다.

```razor
<FluentButton Appearance="Appearance.Accent" OnClick="@DisplayInput">Debug</FluentButton>
<p id="displayText">@displayText</p>

@code {
    [Parameter]
    public object? Input { get; set; }

    private string displayText = "No input provided.";

    private void DisplayInput()
    {
        if (Input == null)
        {
            displayText = "Input is null.";
        }
        else
        {
            displayText = $"{Input} (Type: {Input.GetType()})";
        }
    }
}
```

2024-08-30 03:26 UTC, justinyoo reviewed
Fluent UI 컴포넌트로 바꿔보세요.

2024-08-30 03:26 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/DebugButtonComponent.razor
> +<p id="displayText">@displayText</p>
여기도 MessageBar 혹은 MessageBox 혹은 Toast 같은 걸로 바꿔보면 어때요?

2024-08-30 03:26 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/TargetComponent.razor
> +</fieldset>
사실 이 부분은 여기서는 라디오버튼 리스트긴 하지만, 뭐가 되든 상관이 없겠죠? 혹시 라디오버튼 리스트로 하려면 이것도 마찬가지로 Fluent UI 컴포넌트를 활용해 보시렵니까?

2024-08-31 08:52 UTC, o-ii commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/DebugButtonComponent.razor
> +<p id="displayText">@displayText</p>
displayText 영역을 FluentUI의 Toast로 변경했습니다.

2024-08-31 08:55 UTC, o-ii commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/TargetComponent.razor
> +</fieldset>
Fluent UI의 Radio Group으로 변경했습니다. 이 UI 컴포넌트는 단일 타입만 사용할 수 있어서, 여러 타입 대신 정수(int)로 통일하고, 이에 맞춰 테스트 코드도 수정했습니다.

2024-08-31 12:15 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Layout/MainLayout.razor
> +        <FluentMessageBarProvider />
원래 있던 자리에서는 제대로 작동하지 않나요?

2024-08-31 12:29 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/DebugButtonComponent.razor
> +    }
가급적이면 `void` 메소드 보다는 `async Task` 메소드를 쓰는 것이 좋습니다.

이런 식으로 `if { ... } else { ... }` 블록 depth를 낮추는 것이 좋습니다.

```csharp
private async Task ShowToast()
{
    if (Input is null)
    {
        ToastService.ShowToast(ToastIntent.Warning, "Input is null.");
        await Task.CompletedTask;
        return;
    }

    ToastService.ShowToast(ToastIntent.Success, $"{Input} (Type: {Input.GetType()})");
    await Task.CompletedTask;
}
```

2024-08-31 12:31 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/DebugTargetComponent.razor
> +    public EventCallback<int> OnValueChange { get; set; }
다른 빌트인 이벤트 핸들러를 보면 `OnInitialized` 같은 형태이니만큼 여기서도 비슷한 형식으로 `OnValueChanged` 이렇게 네이밍을 가져가면 좋습니다.

2024-08-31 12:33 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/UI/DebugButtonComponentTests.cs
- 파일 이름을 `TestsPageTests.cs`로 바꿔주세요.
- 클래스 이름을 `TestsPageTests`라고 바꿔주세요.
- 위치를 `UI/`가 아니라 `Pages/`쪽으로 바꿔주세요.

2024-08-31 12:35 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/UI/DebugButtonComponentTests.cs
> +        await Expect(Page.Locator(".fluent-toast-title")).ToHaveTextAsync($"{inputValue} (Type: System.Int32)");
`System.Int32` 값도 위의 `TestCast(123, typeof(int))` 같은 식으로 보낼 수 있지 않을까요?

2024-08-31 12:56 UTC, o-ii commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Layout/MainLayout.razor
> +        <FluentMessageBarProvider />
[ToastProvider](https://www.fluentui-blazor.net/Toast) 문서의 코드를 참고했는데, 원래 자리에서도 작동해서 다시 제자리로 옮겨두었습니다!

```razor
<main>
    <nav>
    :
    </nav>
    <div class="content">
        <article id="article">
            @Body
        </article>
    </div>
    <FluentToastProvider MaxToastCount="10" />
</main>
```

2024-08-31 13:01 UTC, justinyoo requested changes

2024-08-31 13:01 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/DebugButtonComponent.razor
> +        ToastService.ShowToast(ToastIntent.Success, $"{Input} (Type: {Input.GetType()})");
`{Input.GetType().FullName}` 이렇게 바꾸면 어떤가요?

2024-08-31 13:08 UTC, o-ii commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/TestsPageTests.cs
> +        await Expect(Page.Locator(".fluent-toast-title")).ToHaveTextAsync($"{inputValue} (Type: System.{expectedType.Name})");
`expectedType.Name`을  `inputType`으로 수정했습니다

```cs
await Expect(Page.Locator(".fluent-toast-title")).ToHaveTextAsync($"{inputValue} (Type: {inputType})");
```

2024-08-31 13:13 UTC, o-ii commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/DebugButtonComponent.razor
> +<FluentButton @onclick="@ShowToast" Appearance="Appearance.Accent">Debug</FluentButton>
`@ShowToast`를 `ShowToast`로 수정했습니다.

2024-08-31 13:21 UTC, justinyoo approved these changes
고생하셨습니다! LGTM!

2024-08-31 13:21 UTC, merged