Response payload definition #22
aliencube/azure-openai-sdk-proxy pull request #237
Opened 2024-08-19 19:52 UTC by jhmin99

Related to #22 

- 기존 chat completion의 endpoint가 변경된 것 같습니다.
  - `/deployments/{deploymentName}/chat/completions` ->` /deployments/{deployment-id}/chat/completions`
  - [azure-rest-api-specs(2024-06-01)](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/data-plane/AzureOpenAI/inference/stable/2024-06-01/inference.json)
- 문서 내 response 관련 내용을 아래에 정리하였습니다.

## Endpoint: /deployments/{deployment-id}/chat/completions

```json
"/deployments/{deployment-id}/chat/completions": {
      "post": {
        "summary": "Creates a completion for the chat message",
        "operationId": "ChatCompletions_Create",
        "parameters": [
          {
            "in": "path",
            "name": "deployment-id",
            "required": true,
            "schema": {
              "type": "string",
              "description": "Deployment id of the model which was deployed."
            }
          },
          {
            "in": "query",
            "name": "api-version",
            "required": true,
            "schema": {
              "type": "string",
              "example": "2024-06-01",
              "description": "api version"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/createChatCompletionRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/createChatCompletionResponse"
                }
              }
            },
            "headers": {
              "apim-request-id": {
                "description": "Request ID for troubleshooting purposes",
                "schema": {
                  "type": "string"
                }
              }
            }
          },
          "default": {
            "description": "Service unavailable",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/errorResponse"
                }
              }
            },
            "headers": {
              "apim-request-id": {
                "description": "Request ID for troubleshooting purposes",
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        },
        "x-ms-examples": {
          "Create a chat completion.": {
            "$ref": "./examples/chat_completions.json"
          },
          "Creates a completion based on Azure Search data and system-assigned managed identity.": {
            "$ref": "./examples/chat_completions_azure_search_minimum.json"
          },
          "Creates a completion based on Azure Search vector data, previous assistant message and user-assigned managed identity.": {
            "$ref": "./examples/chat_completions_azure_search_advanced.json"
          },
          "Creates a completion for the provided Azure Cosmos DB.": {
            "$ref": "./examples/chat_completions_cosmos_db.json"
          }
        }
      }
    }
```

- createChatCompletionResponse

```json
"createChatCompletionResponse": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/components/schemas/chatCompletionsResponseCommon"
          },
          {
            "properties": {
              "prompt_filter_results": {
                "$ref": "#/components/schemas/promptFilterResults"
              },
              "choices": {
                "type": "array",
                "items": {
                  "type": "object",
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/chatCompletionChoiceCommon"
                    },
                    {
                      "properties": {
                        "message": {
                          "$ref": "#/components/schemas/chatCompletionResponseMessage"
                        },
                        "content_filter_results": {
                          "$ref": "#/components/schemas/contentFilterChoiceResults"
                        },
                        "logprobs": {
                          "$ref": "#/components/schemas/chatCompletionChoiceLogProbs"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        ],
        "required": [
          "id",
          "object",
          "created",
          "model",
          "choices"
        ]
      }
```

- chatCompletionsResponseCommon

```json
"chatCompletionsResponseCommon": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "A unique identifier for the chat completion."
          },
          "object": {
            "$ref": "#/components/schemas/chatCompletionResponseObject"
          },
          "created": {
            "type": "integer",
            "format": "unixtime",
            "description": "The Unix timestamp (in seconds) of when the chat completion was created."
          },
          "model": {
            "type": "string",
            "description": "The model used for the chat completion."
          },
          "usage": {
            "$ref": "#/components/schemas/completionUsage"
          },
          "system_fingerprint": {
            "type": "string",
            "description": "Can be used in conjunction with the `seed` request parameter to understand when backend changes have been made that might impact determinism."
          }
        },
        "required": [
          "id",
          "object",
          "created"
          "model"
        ]
      }
```

- promptFilterResults

```json
 "promptFilterResults": {
        "type": "array",
        "description": "Content filtering results for zero or more prompts in the request. In a streaming request, results for different prompts may arrive at different times or in different orders.",
        "items": {
          "$ref": "#/components/schemas/promptFilterResult"
        }
      }
```

- chatCompletionChoiceCommon

```json
"chatCompletionChoiceCommon": {
        "type": "object",
        "properties": {
          "index": {
            "type": "integer"
          },
          "finish_reason": {
            "type": "string"
          }
        }
      }
```

- chatCompletionResponseMessage

```json
"chatCompletionResponseMessage": {
        "type": "object",
        "description": "A chat completion message generated by the model.",
        "properties": {
          "role": {
            "$ref": "#/components/schemas/chatCompletionResponseMessageRole"
          },
          "content": {
            "type": "string",
            "description": "The contents of the message.",
            "nullable": true
          },
          "tool_calls": {
            "type": "array",
            "description": "The tool calls generated by the model, such as function calls.",
            "items": {
              "$ref": "#/components/schemas/chatCompletionMessageToolCall"
            }
          },
          "function_call": {
            "$ref": "#/components/schemas/chatCompletionFunctionCall"
          },
          "context": {
            "$ref": "#/components/schemas/azureChatExtensionsMessageContext"
          }
        }
      }
```

- contentFilterChoiceResults (

```json
"contentFilterChoiceResults": {
        "type": "object",
        "description": "Information about the content filtering category (hate, sexual, violence, self_harm), if it has been detected, as well as the severity level (very_low, low, medium, high-scale that determines the intensity and risk level of harmful content) and if it has been filtered or not. Information about third  [...]

2024-08-20 01:41 UTC, justinyoo requested changes
고생하셨습니다! 이게 어렵진 않은데 시간이 많이 걸리는 거라서 어쩌나 싶었는데, 이렇게 빨리 해 주시다니...

https://github.com/aliencube/azure-openai-sdk-proxy/pull/231

이거 참고해서 테스트 케이스도 만들어 주세요.

2024-08-20 01:41 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Endpoints/ChatCompletionsEndpoint.cs
> +        .Produces<CreateChatCompletionResponseDto>(statusCode: StatusCodes.Status200OK, contentType: "application/json")
여기서는 `Dto`라는 표현을 쓰지 않습니다.

2024-08-20 01:41 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Models/CreateChatCompletionResponseDto.cs
> +    [property: JsonPropertyName("choices"), Required] List<ChatCompletionChoice> Choices
모든 속성을 nullable 로 해 주세요. 예) `string?`, `DateTimeOffset?`, etc

다른 개체들도 모두 적용시켜 주세요.

2024-08-20 01:41 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Models/CreateChatCompletionResponseDto.cs
> +    [property: JsonPropertyName("logprobs")] ChatCompletionChoiceLogProbs Logprobs
`Logprobs` ➡️ `LogProbs`

2024-08-20 01:41 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Models/CreateChatCompletionResponseDto.cs
> +    [property: JsonPropertyName("content"), Required] List<ChatCompletionTokenLogprob>? Content
`Logprob` ➡️ `LogProb`

2024-08-20 21:58 UTC, jhmin99 commented
진행 상황에 대해 말씀드리는 게 좋을 것 같아 중간 점검 느낌으로 작성하였습니다..ㅎ

- **변경 사항**:
  - 타입 일치를 위해 `CreateChatCompletionResponse`의 `created` 필드 타입을 `DateTimeOffset?`에서 `long?`으로 변경하였습니다.
  - `JsonStringEnumConverter`와 `EnumMember`를 함께 사용할 때 발생하는 문제를 해결하기 위해 커스텀 컨버터를 구현하였습니다.
  - JSON 객체를 DTO에 역직렬화할 때 발생할 수 있는 enum 관련 오류를 확인하기 위한 테스트를 작성했습니다.
  
- **향후 작업**: 
  - 커스텀 컨버터에 대한 테스트 작성이 필요합니다.
  - DTO가 OpenAPI 문서와 일치하는지 검증하는 테스트가 필요합니다.

2024-08-20 23:39 UTC, justinyoo commented
> * **변경 사항**:
>   
>   * 타입 일치를 위해 `CreateChatCompletionResponse`의 `created` 필드 타입을 `DateTimeOffset?`에서 `long?`으로 변경하였습니다.

실제로 API 호출 응답개체의 JSON 모양을 확인해 보시고 확정짓는게 낫겠습니다. 또한 좀 더 찾아봐야겠지만 `DateTimeOffset`의 경우 문자열이 아마 자동으로 개체로 변환되거나 할 거예요.

2024-08-21 10:09 UTC, jhmin99 commented
> 실제로 API 호출 응답개체의 JSON 모양을 확인해 보시고 확정짓는게 낫겠습니다. 또한 좀 더 찾아봐야겠지만 `DateTimeOffset`의 경우 문자열이 아마 자동으로 개체로 변환되거나 할 거예요.
<img width="824" alt="스크린샷 2024-08-21 오후 6 20 22" src="https://github.com/user-attachments/assets/5af1a54c-bb88-4a19-9c46-038e97f4b066">   


여기에서 openAI.Chat.ChatCompletion 을 확인하니 전달받는 JSON 의 created필드가 아래와 같이 DateTimeOffset으로 확인되었는데 필드값을 이에 따라 DateTimeOffset으로 원상복구 시키는 것이 좋을까요?    


   ```
    // 요약:
    //     The Unix timestamp (in seconds) of when the chat completion was created.
    [CodeGenMember("Created")]
    public DateTimeOffset CreatedAt { get; }
```


[azure-rest-api-specs(2024-06-01)](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/data-plane/AzureOpenAI/inference/stable/2024-06-01/inference.json)   

이 문서에서 해당 엔드포인트는 아니지만, created 필드가 포함된 예시 응답 JSON을 확인하니 다음과 같이 `"created": 1637097562` 로 반환하는 것을 확인했습니다.   

<img width="551" alt="스크린샷 2024-08-21 오후 6 45 26" src="https://github.com/user-attachments/assets/b4c5f5fc-0e18-4ea3-8949-720a51abaead">


테스트 시 created 필드가 DateTimeOffset 일 때에 1637097562 (unix timestamp) 가 DateTimeOffset 변환되지 못하고 에러를 내뱉어 구글링을 해보니 따로 DateTimeOffset의 함수를 이용해야 할 것 같습니다. [참고](https://learn.microsoft.com/en-us/dotnet/api/system.datetimeoffset.fromunixtimeseconds?view=net-8.0)


정리하자면, 공식문서의 응답예시와 현재 프로젝트에 작성되어 있는 openAI.Chat.ChatCompletion 에서의 created 필드가 달라 어느 것을 택해야할 지 @justinyoo 저스틴님의 의견이 필요합니다!

2024-08-21 12:10 UTC, jhmin99 commented
> 실제로 API 호출 응답개체의 JSON 모양을 확인해 보시고 확정짓는게 낫겠습니다. 또한 좀 더 찾아봐야겠지만 `DateTimeOffset`의 경우 문자열이 아마 자동으로 개체로 변환되거나 할 거예요.

아! 추후에 직접 Request를 보내보고 전달받는 응답객체를 보고 확정 짓자는 말씀이신가요? 🤔

2024-08-22 06:04 UTC, justinyoo commented
> 아! 추후에 직접 Request를 보내보고 전달받는 응답객체를 보고 확정 짓자는 말씀이신가요? 🤔

맞습니다!

2024-08-22 08:16 UTC, jhmin99 commented
> 맞습니다!

문서의 openai에 대해서 #ref, allOf, required 등에 대해서만 dto 테스트를 만들어봐도 괜찮을까요??

타입이나 enum에 대해서는 나중에 일단 생각하는 걸로..

2024-08-22 23:01 UTC, justinyoo commented
> 문서의 openai에 대해서 #ref, allOf, required 등에 대해서만 dto 테스트를 만들어봐도 괜찮을까요??
> 
> 타입이나 enum에 대해서는 나중에 일단 생각하는 걸로..

우선 해 보시구요, 다 되면 또 논의하시지요.

2024-08-23 07:58 UTC, justinyoo requested changes
커스텀 컨버터 도입이 정말로 필요한가에 대해 고민을 좀 해 보시죠.

https://github.com/dotnet/runtime/issues/74385#issuecomment-2220667024

2024-08-23 07:58 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Models/CreateChatCompletionResponse.cs
> +}
이거 한 번 보시겠어요?

https://github.com/dotnet/runtime/issues/74385#issuecomment-2220667024

2024-08-23 07:58 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Models/CreateChatCompletionResponse.cs
record 보다는 class 로 구현해 보는게 어떤가요?

2024-08-23 07:58 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Models/Converter/EnumMemberConverter.cs
모델의 하위라기 보다는 모델과 같은 레벨의 `Converters` 네임스페이스가 적절할 것 같습니다. 그런데, 앞서 언급한 대로 굳이 이 컨버터가 필요한가요?

2024-08-23 08:51 UTC, jhmin99 commented on src/AzureOpenAIProxy.ApiApp/Models/CreateChatCompletionResponse.cs
> +}
앗 넵 바로 확인하겠습니다! 감사합니다ㅎㅎ

2024-08-23 10:18 UTC, jhmin99 commented on src/AzureOpenAIProxy.ApiApp/Models/Converter/EnumMemberConverter.cs
https://github.com/dotnet/runtime/issues/74385#issuecomment-2243743381

@justinyoo 저스틴님! 올려주신 자료 확인했습니다.

.Net 9 Preview 7부터 아마 위 제안이 라이브러리에 추가가 된 것 같습니다.
현 상황에서는 프로젝트가 .Net 8을 사용하고 있어 따로 컨버터가 필요할 것 같기는 합니다..

아니면 https://github.com/dotnet/runtime/issues/31081#issuecomment-816963462 이곳에 나와 있는 Nuget 패키지를 사용하는 것은 너무 신뢰성이 떨어지려나요..? 

https://www.nuget.org/packages/Macross.Json.Extensions
위 버젼은 그래도 500만 다운로드 정도 되는 것 같습니다!

2024-08-23 20:20 UTC, jhmin99 commented
일단은 임시로 dto에 컨버터를 넣고 테스트를 작성하였습니다.
추후에 컨버터를 사용하지 않게 된다면 dto부분만 수정하면 될 것 같습니다!

2024-08-25 06:37 UTC, justinyoo requested changes
좋습니다! 거의 된 것 같은데 컨버터 테스트도 추가해 주세요.

2024-08-25 06:37 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Converters/EnumMemberConverter.cs
요 컨버터 테스트도 추가해 주세요!

2024-08-25 07:42 UTC, jhmin99 commented
> 좋습니다! 거의 된 것 같은데 컨버터 테스트도 추가해 주세요.

변경사항:

- CreateChatCompletionResponseTests의 namespace를 `AzureOpenAIProxy.ApiApp.Tests`에서 `AzureOpenAIProxy.ApiApp.Tests.Models`로 변경했습니다.
- EnumMemberConverter에 대한 테스트를 추가했습니다.

2024-08-26 00:58 UTC, justinyoo requested changes
거의 다 됐습니다! 이제 작성하신 테스트 메소드 이름들을 다른 테스트와 마찬가지로 동일하게 `Given___When___Then___` 형식으로 바꿔주세요!

2024-08-26 05:47 UTC, jhmin99 commented
> 거의 다 됐습니다! 이제 작성하신 테스트 메소드 이름들을 다른 테스트와 마찬가지로 동일하게 `Given___When___Then___` 형식으로 바꿔주세요!

테스트들 메서드 명 수정완료 하였습니다!

2024-08-27 03:09 UTC, justinyoo requested changes
데헷, 테스트 메소드 하나에서 serialisation, deserialisation 두가지를 한번에 테스트하는 걸 이제서야 발견했네요, 테스트 메소드 둘로 쪼개서 하나는 serialisation, 다른 하나는 deserialisation 쪽을 테스트하게끔 해 주세욥.

2024-08-27 03:09 UTC, justinyoo commented on test/AzureOpenAIProxy.ApiApp.Tests/Models/CreateChatCompletionResponseTests.cs
> +        serializedJson.Should().Be(exampleJson.Replace("\r", "").Replace("\n", "").Replace(" ", ""));
오, 저 이거 하나만 테스트 하는 줄 알았더니, 두 개를 하나의 테스트 메소드에서 테스트하네요?

메소드 두개로 쪼개서 하나는 직렬화, 하나는 비직렬화 테스트하는 걸로 변경해 주실랍니까?

2024-08-27 03:23 UTC, jhmin99 commented on test/AzureOpenAIProxy.ApiApp.Tests/Models/CreateChatCompletionResponseTests.cs
> +        serializedJson.Should().Be(exampleJson.Replace("\r", "").Replace("\n", "").Replace(" ", ""));
수정했습니다!

2024-08-28 02:40 UTC, justinyoo requested changes
테스트 방식을 한 번 다시 검토해 봐야 할 것 같아요.

2024-08-28 02:40 UTC, justinyoo commented on test/AzureOpenAIProxy.ApiApp.Tests/Models/CreateChatCompletionResponseTests.cs
> +        var deserializedResponse = JsonSerializer.Deserialize<CreateChatCompletionResponse>(exampleJson);
앗, 이건 좀 반칙 같은데... 문자열 형태의 JSON을 비직렬화한 내용으로 다시 직렬화하는 테스트 보다는 여기서는 아예 C# 인스턴스를 `exampleResponse` 같은 식으로 만든 후에 이 인스턴스를 직렬화하는 테스트가 좀 더 정확해 보입니다.

2024-08-28 03:11 UTC, jhmin99 commented on test/AzureOpenAIProxy.ApiApp.Tests/Models/CreateChatCompletionResponseTests.cs
> +        var deserializedResponse = JsonSerializer.Deserialize<CreateChatCompletionResponse>(exampleJson);
앗 넵 확인했습니다! 감사합니다.

2024-08-30 13:48 UTC, jhmin99 commented
1. C# 인스턴스(exampleResponse)를 사용하여 직렬화 테스트:
- C# 인스턴스를 JSON으로 직렬화하여 exampleJson과 비교
2. exampleJson을 사용하여 역직렬화 테스트: 
- exampleJson을 역직렬화하여 C# 인스턴스로 변환하고, 이 인스턴스가 exampleResponse와 동일한지 확인

이렇게 진행되도록 수정하였습니다!

2024-08-31 12:37 UTC, justinyoo commented
@jhmin99 컨플릭트 해결해 주세요!

2024-09-01 10:53 UTC, jhmin99 commented
@justinyoo 저스틴님 충돌 해결 하느라 rebase를 잘못 쓴 것 같은데, 브랜치를 새로 파서 제가 작업한 부분만 다시 커밋하는게 좋을까요..? ㅠ

2024-09-01 11:10 UTC, jhmin99 commented
@justinyoo  저스틴님, 충돌 해결하면서 rebase를 써보다가 잘못쓴것같아요.. 이전 푸시된 것들까지 제 이름으로 다시 커밋해버린 것 같은데 브랜치를 하나 새로 파서 제가 작업한 부분만 다시 커밋하고 pr 날려야 할까요??

2024-09-01 14:38 UTC, justinyoo commented
헑 ㅠ 아무래도 그래야 할 듯? ㅠ

2024-09-01 20:35 UTC, jhmin99 commented
> 헑 ㅠ 아무래도 그래야 할 듯? ㅠ 새 PR 생성하면서 히스토리 추적 느낌으로 이 PR도 함께 링크 걸어주세요.

넵 알겠습니다!

2024-09-06 04:29 UTC, justinyoo commented
#298 에서 이어서 리뷰합니다. 이 PR은 닫습니다.

2024-09-06 04:29 UTC, closed without merging