[OpenAPI] Add endpoint for update event details
aliencube/azure-openai-sdk-proxy pull request #241
Opened 2024-08-20 09:55 UTC by SeungHuLee

https://github.com/aliencube/azure-openai-sdk-proxy/issues/202

- AddAdminEvents 함수 변경점
  - Add -> Map으로 이름 변경
    - DI Container에 추가 시 `Add`, 미들웨어 추가 시 `Use`, 엔드포인트 추가 시 `Map`으로 지정하였습니다.

  - 리턴 타입과 인수를 `IEndpointRouteBuilder`로 변경
    - 해당 변경점 토대로 신규 함수 작성하지 않고 동일 함수에서 신규 엔드포인트 추가하였습니다.

   - 신규 엔드포인트 `UpdateAdminEventDetails` 추가

- 테스트 코드 추가: 신규 엔드포인트 `UpdateAdminEventDetails`

확인 부탁드립니다. 감사합니다.

2024-08-20 23:31 UTC, justinyoo requested changes

2024-08-20 23:31 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEventEndpoints.cs
> +    public static IEndpointRouteBuilder MapAdminEvents(this IEndpointRouteBuilder app)
- 기존의 `RouteHandlerBuilder`에서 `IEndpointRouteBuilder`로 바꾼 이유가 있나요?
- 메소드 이름을 `Addxxx`에서 `Mapxxx`로 바꾼 이유가 있나요?

충분한 논의 없이 구현 자체를 바꾸는 것은 PR 리뷰에서 거의 받아들여지지 않습니다.

2024-08-21 00:36 UTC, juhangil commented on src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEventEndpoints.cs
> +    public static IEndpointRouteBuilder MapAdminEvents(this IEndpointRouteBuilder app)
```csharp
public static RouteHandlerBuilder AddRouteHandlerSet(this RouteHandlerBuilder builder,
                                                     ICollection<IEndpointConventionBuilder> set)
{
    set.Add(builder);
    return builder;
}

/// <summary>
/// Adds the get event details by admin endpoint
/// </summary>
/// <param name="app"><see cref="WebApplication"/> instance.</param>
/// <returns>Returns <see cref="RouteHandlerBuilder"/> instance.</returns>
public static RouteHandlerBuilder MapAdminEvents(this WebApplication app)
{
    List<IEndpointConventionBuilder> set = new();

    // Todo: Issue #19 https://github.com/aliencube/azure-openai-sdk-proxy/issues/19
    // Need authorization by admin
    app.MapGet(AdminEndpointUrls.AdminEventDetails, (
        [FromRoute] string eventId) =>
    {
        // Todo: Issue #208 https://github.com/aliencube/azure-openai-sdk-proxy/issues/208
        return Results.Ok();
        // Todo: Issue #208
    })
    .Produces<AdminEventDetails>(statusCode: StatusCodes.Status200OK, contentType: "application/json")
    .Produces(statusCode: StatusCodes.Status401Unauthorized)
    .Produces<string>(statusCode: StatusCodes.Status500InternalServerError, contentType: "text/plain")
    .WithTags("admin")
    .WithName("GetAdminEventDetails")
    .WithOpenApi(operation =>
    {
        operation.Summary = "Gets event details from the given event ID";
        operation.Description = "This endpoint gets the event details from the given event ID.";

        return operation;
    })
    .AddRouteHandlerSet(set);

    // Todo: Issue #19 https://github.com/aliencube/azure-openai-sdk-proxy/issues/19
    // Need authorization by admin
    app.MapPut(AdminEndpointUrls.AdminEventDetails, (
        [FromRoute] string eventId) =>
    {
        // Todo: Issue #203 https://github.com/aliencube/azure-openai-sdk-proxy/issues/203
        return Results.Ok();
    })
    // TODO: Produce Status201Created according to RFC 9110
    .Produces(statusCode: StatusCodes.Status200OK)
    .Produces(statusCode: StatusCodes.Status401Unauthorized)
    .Produces<string>(statusCode: StatusCodes.Status500InternalServerError, contentType: "text/plain")
    .WithTags("admin")
    .WithName("UpdateAdminEventDetails")
    .WithOpenApi(operation =>
    {
        operation.Summary = "Updates event details by the given event ID";
        operation.Description = "This endpoint updates event details by event id, api for admin users";

        return operation;
    })
    .AddRouteHandlerSet(set);

    return new RouteHandlerBuilder(set);
}
```
구상해본 거 빠르게 짜보느라 이상한 모습이긴 한데 이렇게 return하면

```csharp
// Admin Endpoints
app.MapAdminEvents()
      .RequireAuthorization("admin");
```
외부에서 한번에 관리할 수 있지 않을까 생각합니다.
아니면 Extension Method에선 각 그룹마다 policy만 설정하고 실제 route 과정은 private method에서 따로 돌리는 것도 괜찮지 않을까 싶네요

2024-08-21 08:16 UTC, SeungHuLee commented on src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEventEndpoints.cs
> +    public static IEndpointRouteBuilder MapAdminEvents(this IEndpointRouteBuilder app)
@justinyoo @juhangil 리뷰 감사합니다!
- `Add` 에서 `Map`으로 이름 변경한 것은 엔드포인트 매핑 시 일반적으로 `Map` 접미사를 사용하는 것이 적절하다 생각하여 변경하였습니다.

- 함수 리턴타입과 인수 변경
  - 추후 작업 진행 시 코드 가독성 손상의 여지가 있다 판단하여 변경하였습니다.
  `RouteHandlerBuilder`를 리턴할 경우, 함수 `WithName()`, `WithOpenApi()`가 `IEndpointConventionBuilder`를 리턴하므로 신규 엔드포인트 매핑 시 불필요한 빌더 추가로 인해 가독성을 해칠 것으로 생각합니다.
  
  - 한길님께서 주신 리뷰 및 기타 조사를 통해 다음과 같이 변경해보려 합니다.
  ```csharp
  // Program.cs
  app.MapGroup(AdminEndpointUrls.AdminEventDetails)
     .MapAdminEvents()
     .WithTags("admin")
     .RequireAuthorization();
   
   
  // AdminEndpointUrls.cs
  public const string AdminEventDetails = "/admin";
   
   
  // AdminEventEndpoints.cs
  public static RouteGroupBuilder MapAdminEvents(this RouteGroupBuilder group)
  {
      group.MapGet("/events/{eventId}", (string eventId) =>
      {
          return Results.Ok();
      })
      .Produces<AdminEventDetails>(statusCode: StatusCodes.Status200OK, contentType: "application/json")
      .Produces(statusCode: StatusCodes.Status401Unauthorized)
      .Produces<string>(statusCode: StatusCodes.Status500InternalServerError, contentType: "text/plain")
      .WithName("GetAdminEventDetails")
      .WithOpenApi(operation =>
      {
          operation.Summary = "Gets event details from the given event ID";
          operation.Description = "This endpoint gets the event details from the given event ID.";
      
          return operation;
      });
      
      group.MapPut("/events/{eventId}", (string eventId) =>
      {
          return Results.Ok();
      })
      .Produces(statusCode: StatusCodes.Status200OK)
      .Produces(statusCode: StatusCodes.Status401Unauthorized)
      .Produces<string>(statusCode: StatusCodes.Status500InternalServerError, contentType: "text/plain")
      .WithName("UpdateAdminEventDetails")
      .WithOpenApi(operation =>
      {
          operation.Summary = "Updates event details by the given event ID";
          operation.Description = "This endpoint updates event details by event id, api for admin users";
  
          return operation;
      });
  
      return group;
  }
  ```
  
  확인 부탁드립니다. 감사합니다!

2024-08-22 06:09 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEventEndpoints.cs
> +    public static IEndpointRouteBuilder MapAdminEvents(this IEndpointRouteBuilder app)
@SeungHuLee 일단, 이 태스크의 요구사항과 전혀 다른 것을 구현하셨어요. 지금 코드 변경사항은 요구사항과는 전혀 다릅니다.

지금 작성한 코드 변경사항은 향후 발전방향이 될 수도 있고 아닐 수도 있습니다. 논의를 해 본적이 없기 때문인데요, 이 태스크에서는 수용하지 않습니다. 만약 생각하고자 하는 것이 있다면 별도의 이슈를 생성해서 하나씩 차근차근 논의하는 것이 바람직합니다.

기존 요구사항대로 작성해 주세요.

2024-08-22 08:05 UTC, SeungHuLee commented on src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEventEndpoints.cs
> +    public static IEndpointRouteBuilder MapAdminEvents(this IEndpointRouteBuilder app)
@justinyoo 확인했습니다! 숙지하겠습니다.
현재 태스크의 요구사항에 맞는 부분 이외는 제거하였습니다!

2024-08-22 08:19 UTC, justinyoo requested changes
몇가지 수정사항 코멘트 남겨뒀습니다.

2024-08-22 08:19 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEventEndpoints.cs
> +        .Produces(statusCode: StatusCodes.Status200OK)
요청 payload와 응답 payload가 빠졌습니다.

2024-08-22 08:19 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEventEndpoints.cs
> +            operation.Description = "This endpoint updates event details by event id, api for admin users";
36번 줄 참고해서 다시 작성해 주세요.

2024-08-22 08:19 UTC, justinyoo commented on test/AzureOpenAIProxy.AppHost.Tests/ApiApp/Endpoints/AdminUpdateEventDetailsOpenApiTests.cs
요청 payload와 응답 payload 정의가 없기 때문에 추가한 후에 테스트 케이스도 거기 맞춰서 추가해 주세요.

2024-08-24 08:13 UTC, SeungHuLee commented on src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEventEndpoints.cs
> +        .Produces(statusCode: StatusCodes.Status200OK)
다음과 같이 변경하였습니다.

```csharp
.Accepts<AdminEventDetails>(contentType: "application/json")
.Produces(statusCode: StatusCodes.Status204NoContent)
```

2024-08-24 08:14 UTC, SeungHuLee commented on src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEventEndpoints.cs
> +            operation.Description = "This endpoint updates event details by event id, api for admin users";
다음과 같이 변경하였습니다.
```csharp
.WithOpenApi(operation =>
{
    operation.Summary = "Updates event details from the given event ID";
    operation.Description = "This endpoint updates the event details from the given event ID.";

    return operation;
});
```

2024-08-24 08:14 UTC, SeungHuLee commented on test/AzureOpenAIProxy.AppHost.Tests/ApiApp/Endpoints/AdminUpdateEventDetailsOpenApiTests.cs
대응되는 테스트 케이스 추가하였습니다.

2024-08-24 11:47 UTC, justinyoo requested changes

2024-08-24 11:47 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEventEndpoints.cs
> +        .Produces<string>(statusCode: StatusCodes.Status500InternalServerError, contentType: "text/plain")
404 not found 에러도 넣어주세요. path 에 eventId 값이 없을 경우 던지는 에러입니다.

2024-08-24 13:17 UTC, SeungHuLee commented on src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEventEndpoints.cs
> +        {
다음과 같이 변경하였습니다.
```csharp
var builder = app.MapPut(AdminEndpointUrls.AdminEventDetails, (
    [FromBody] AdminEventDetails payload,
    [FromRoute] string eventId) =>
{
```

2024-08-24 13:18 UTC, SeungHuLee commented on src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEventEndpoints.cs
> +        .Produces<string>(statusCode: StatusCodes.Status500InternalServerError, contentType: "text/plain")
다음과 같이 변경하였습니다.
```csharp
.Accepts<AdminEventDetails>(contentType: "application/json")
.Produces<AdminEventDetails>(statusCode: StatusCodes.Status200OK, contentType: "application/json")
.Produces(statusCode: StatusCodes.Status401Unauthorized)
.Produces<string>(statusCode: StatusCodes.Status404NotFound, contentType: "text/plain")
.Produces<string>(statusCode: StatusCodes.Status500InternalServerError, contentType: "text/plain")
```

2024-08-24 14:49 UTC, justinyoo requested changes
거의 다 온 것 같네요. 코멘트 추가했습니다.

2024-08-24 14:49 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEventEndpoints.cs
> +            [FromRoute] string eventId) =>
기존 엔드포인트 순서를 보시면 `FromRoute` 먼저, `FromBody`가 나중입니다. 순서 한 번 맞춰보시겠어요? 우선은 이 두 파라미터만 생각해 보시지요.

2024-08-24 14:49 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEventEndpoints.cs
> +        .Produces<string>(statusCode: StatusCodes.Status404NotFound, contentType: "text/plain")
404 에러는 401과 마찬가지로 응답 개체가 없습니다.

2024-08-24 15:18 UTC, SeungHuLee commented on src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEventEndpoints.cs
> +            [FromRoute] string eventId) =>
앗 그렇네용 변경했습니다~

2024-08-24 15:19 UTC, SeungHuLee commented on src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEventEndpoints.cs
> +        .Produces<string>(statusCode: StatusCodes.Status404NotFound, contentType: "text/plain")
수정했습니다!

2024-08-25 07:05 UTC, justinyoo requested changes
하나 더!

2024-08-25 07:05 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEventEndpoints.cs
> +        .Produces(statusCode: StatusCodes.Status404NotFound, contentType: "text/plain")
응답 개체가 없으니 `contentType`도 필요 없습니다

2024-08-25 07:13 UTC, SeungHuLee commented on src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEventEndpoints.cs
> +        .Produces(statusCode: StatusCodes.Status404NotFound, contentType: "text/plain")
앗 ㅋㅋ 수정했습니다~

2024-08-26 00:54 UTC, justinyoo requested changes
OpenAPI 문서 린팅 규칙도 추가해야겠네요.

https://github.com/aliencube/azure-openai-sdk-proxy/blob/485cbe9bf9c4ef3522d738d6492a188f51573ca7/.spectral.yaml#L75-L83

여기 참고해서 현재 401만 예외처리되어 있는데, 400과 404도 예외규칙에 추가해 주세요.

2024-08-26 00:54 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEventEndpoints.cs
> +        .Produces(statusCode: StatusCodes.Status404NotFound)
요 부분이 OpenAPI 린팅에서 걸립니다.

https://github.com/aliencube/azure-openai-sdk-proxy/blob/485cbe9bf9c4ef3522d738d6492a188f51573ca7/.spectral.yaml#L75-L83

여기 보시면 401만 예외인데, 400과 404도 예외를 추가해 주세요.

2024-08-26 07:14 UTC, SeungHuLee commented on src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEventEndpoints.cs
> +        .Produces(statusCode: StatusCodes.Status404NotFound)
수정했습니다!

2024-08-27 02:58 UTC, justinyoo approved these changes
고생하셨습니다! LGTM

2024-08-27 02:58 UTC, merged