[Admin] Component: Landing Page(Page) #235
aliencube/azure-openai-sdk-proxy pull request #242
Opened 2024-08-20 12:33 UTC by n-y-kim

#235 

Page 생성이라 딱히 추가할 코드가 없는 상황입니다.
해당 기능도 테스트 코드가 필요한가요?

2024-08-20 23:24 UTC, justinyoo commented
페이지가 만들어졌다면, 접속이 가능한지 테스트가 필요하겠지요? AppHost 프로젝트에서 테스트 코드를 추가해 보세요.

2024-08-25 06:24 UTC, n-y-kim commented
@justinyoo 테스트 코드 추가 확인 부탁드립니다

2024-08-25 06:30 UTC, justinyoo requested changes
글로벌 using 디렉티브만 처리하면 될 듯?

2024-08-25 06:30 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/Admin.razor
> +@using AzureOpenAIProxy.PlaygroundApp.Components.UI
요거 `_Imports.razor` 쪽으로 넣어주세요

2024-08-25 06:47 UTC, n-y-kim commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/Admin.razor
> +@using AzureOpenAIProxy.PlaygroundApp.Components.UI
[650cd07](https://github.com/aliencube/azure-openai-sdk-proxy/pull/242/commits/650cd0735f620b6832b0062b7454ec06168ed75d)

2024-08-25 07:06 UTC, justinyoo approved these changes
LGTM!

2024-08-25 07:06 UTC, merged