[WIP] Feature/221 add openapi linting
aliencube/azure-openai-sdk-proxy pull request #243
Opened 2024-08-20 14:03 UTC by sikutisa

* Related to #221
  * 현재 다양한 시나리오에 대해 github workflow가 의도대로 동작하는지 테스트하고 있습니다. 

## Description
### 빌드 시점에 swagger.json 생성
* #229에서 제시한 것 처럼 json 생성을 위해 run을 하는 것보다는 빌드 시점에 생성하는 것이 더 낫다고 판단했습니다.
* 따라서 다음 링크를 참고하여 작업했습니다. 
  * https://stackoverflow.com/questions/48652092/generate-swagger-json-at-build-time
* 이를 위해 SwashBuckle.AspNetCore.Cli를 사용했고, azure-dev-build-only.yml과 azure-dev.yml에 아래처럼 cli를 설치하는 스텝이 포함됐습니다.
* Swagger.json을 생성하기 위한 커맨드가 AzureOpenAIProxy.ApiApp.csproj에 추가됐습니다. 
  * 논의사항
    * 해당 커맨드 실행에 **ApiVersion**에 대한 값이 필요한데, 이 값이 현재 Constant.cs에서 관리돼고 있습니다. 해당 값을 csproj 파일로 가져오는 방법을 찾지 못해서 일단 <ApiVersion> 태그로 값을 하드코딩 했는데, 더 좋은 방법을 고려 중입니다.
    * 현재 json 파일은 AzureOpenAIProxy.ApiApp 폴더 내애 openapi.json으로 생성되고 있습니다. 커맨드를 ```sh--output ./PATH_WHERE_YOU_WANT/FILE_NAME_YOU_WANT.json``` 로 변경하면 생성 경로와 파일명을 변경할 수 있습니다. 다만, 폴더의 경우 이미 생성된 폴더로 지정해야 합니다.

### doc linting
* Spectral Linter Action 사용했습니다. 
  * https://github.com/marketplace/actions/spectral-linting
* 위에서 json 파일이 생성되는 경로와 이름에 따라 설정이 변경될 수 있습니다.
* 논의사항
  * 제 개인 레포에서 api 규약을 충족하지 못했을 때 에러 발생해 파이프라인이 fail이 뜨는 것은 확인했는데, unit test 결과처럼 어떤 부분에서 문제가 있었는지 PR 코멘트로 확인하는 방법이 적용돼야 하나 고민 중입니다. 지금은 문제를 확인하려면 깃헙 액션에 들어가서 로그 내 링크를 타고 들어가야 하는 상황입니다.

2024-08-21 04:30 UTC, justinyoo requested changes
코멘트 남겨뒀습니다. 확인해 주세요!

2024-08-21 04:30 UTC, justinyoo commented on .github/workflows/azure-dev-build-only.yml
> +        dotnet tool install SwashBuckle.AspNetCore.Cli
이 태스크를 dotnet restore 태스크 앞으로 놓으면 어떨까요?

2024-08-21 04:30 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/AzureOpenAIProxy.ApiApp.csproj
> +    <ApiVersion>v1.0.0</ApiVersion>
이 값을 `dotnet build` 명령어를 쓸 때 외부에서 인젝션 할 수 있을 것 같은데, 방법을 한 번 찾아보시겠어요?

2024-08-21 04:30 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/AzureOpenAIProxy.ApiApp.csproj
> +  </Target>
1. 사실 평소에는 이 PostBuild 작업이 필요가 없어서, 이걸 그냥 깃헙 액션 태스크로 빼면 어떨까 싶습니다.
2. 아니면 이 파일은 굳이 관리를 하지 않아도 되는 거니까, `.gitignore`에 추가하는 것도 좋겠네요.

1번과 2번 중 어떤게 낫겠어요?

2024-08-21 04:30 UTC, justinyoo commented on .github/workflows/azure-dev-build-only.yml
> +      uses: stoplightio/spectral-action@latest
이게 스펙트럴 공식 액션이긴 한데, 너무 오랫동안 업데이트가 없어서... 이것 말고 제가 제안하는 다른 것도 한 번 써 보실래요? 어떤게 더 낫나요?

2024-08-21 04:32 UTC, justinyoo commented
> 제 개인 레포에서 api 규약을 충족하지 못했을 때 에러 발생해 파이프라인이 fail이 뜨는 것은 확인했는데, unit test 결과처럼 어떤 부분에서 문제가 있었는지 PR 코멘트로 확인하는 방법이 적용돼야 하나 고민 중입니다. 지금은 문제를 확인하려면 깃헙 액션에 들어가서 로그 내 링크를 타고 들어가야 하는 상황입니다.

이게 지금 권한 문제가 생겨서 방법을 찾는 중입니다. ㄷㄷㄷ 현재로서는 액션 결과 화면에서만 볼 수 있게 되어 있어요.

2024-08-22 06:10 UTC, sikutisa commented on .github/workflows/azure-dev-build-only.yml
> +        dotnet tool install SwashBuckle.AspNetCore.Cli
해당 부분 반영하였습니다.

2024-08-22 06:13 UTC, sikutisa commented on src/AzureOpenAIProxy.ApiApp/AzureOpenAIProxy.ApiApp.csproj
> +    <ApiVersion>v1.0.0</ApiVersion>
현재 생각나는 방법은 grep 명령어를 사용해서 읽는 방법인데, 더 좋은 방법이 있을까요?

2024-08-22 06:14 UTC, sikutisa commented on src/AzureOpenAIProxy.ApiApp/AzureOpenAIProxy.ApiApp.csproj
> +  </Target>
깃헙 액션 태스크로 빼는 게 더 나을 것 같습니다. 해당 방향으로 작업하겠습니다.

2024-08-22 06:15 UTC, sikutisa commented on .github/workflows/azure-dev-build-only.yml
> +      uses: stoplightio/spectral-action@latest
이 부분은 깃헙 태스크에서 쉘 스크립트로 스펙트럴을 사용하는 것을 고려하고 있는데, 제안해주시면 같이 검토해보겠습니다.

2024-08-22 14:12 UTC, sikutisa commented on src/AzureOpenAIProxy.ApiApp/AzureOpenAIProxy.ApiApp.csproj
> +    <ApiVersion>v1.0.0</ApiVersion>
grep을 사용해서 Constants.cs에서 APiVersion을 가져오고, 이를 뒤에 있는 swagger 파일 생성 커맨드에 인자로 전달하는 방식으로 변경하였습니다. 
f88e61517738cb7cbe9db682db9874f533f1da2a 의 azure-dev-build-only.yml 71번 라인과 azure-dev.yml의 85번 라인이 그 부분입니다.

2024-08-22 14:16 UTC, sikutisa commented on .github/workflows/azure-dev-build-only.yml
> +      uses: stoplightio/spectral-action@latest
스펙트럴 cli 설치하는 깃헙 액션 태스크를 추가하고, 이를 사용하여 linting 하도록 변경했습니다.

2024-08-22 23:18 UTC, justinyoo requested changes
몇가지 아이디어를 코멘트로 남겼습니다. 같이 논의해 봐요.

2024-08-22 23:18 UTC, justinyoo commented on .github/workflows/azure-dev-build-only.yml
> +    - name: OpenAPI linting
`Lint OpenAPI doc` 으로 변경해 주세요. Verb + Object 형식

2024-08-22 23:18 UTC, justinyoo commented on .github/workflows/azure-dev-build-only.yml
> +        API_VERSION=$(grep -oP 'public const string Version = "\K[^"]+' ./src/AzureOpenAIProxy.ApiApp/Constants.cs)
혹시 `appsettings.json` 파일을 이용해서 `Constants.Version` 값을 대체할 수 있도록 한다면 어떨것 같으신가요? 사실 이 값을 지금처럼 하드코딩해 놓는 건 지금 당장에야 괜찮겠지만, 장기적으로 볼 때는 바뀌어야 하는 부분이긴 하거든요.

2024-08-22 23:18 UTC, justinyoo commented on .github/workflows/azure-dev-build-only.yml
> +        spectral lint openapi.json
이렇게 하면 린팅 결과를 리포트 형태로 볼 수 있나요? 결과를 어떻게 해서든 리포트 형태로 돌려줘야 할텐데...?

2024-08-23 06:25 UTC, sikutisa commented on .github/workflows/azure-dev-build-only.yml
> +        spectral lint openapi.json
![image](https://github.com/user-attachments/assets/337bfb54-0dea-4db2-9e05-66deed29c183)
현재 상태로는 위와 같이 깃헙 액션 로그상에 에러 메시지가 찍히는 상태입니다.
말씀하신 것처럼 리포트 형태로 제공되고 있다고 생각되진 않네요. spectral cli 에서 output이나 format 관련 옵션들이 몇 개 있는 것을 확인했습니다. 제가 일단 테스트한 후, 결과를 보고 어떤 게 적절할지 더 논의하면 좋을 것 같습니다.

2024-08-23 06:30 UTC, sikutisa commented on .github/workflows/azure-dev-build-only.yml
> +        API_VERSION=$(grep -oP 'public const string Version = "\K[^"]+' ./src/AzureOpenAIProxy.ApiApp/Constants.cs)
말씀하신 것처럼 변경해도 좋을 것 같습니다. appsetting.json으로 해당 값이 옮겨간다면 지금처럼 grep을 사용하거나 아니면 jq를 사용하도록 변경하면 될 것 같습니다.
https://jqlang.github.io/jq/

2024-08-23 06:32 UTC, sikutisa commented on .github/workflows/azure-dev-build-only.yml
> +    - name: OpenAPI linting
반영하였습니다.

2024-08-23 07:59 UTC, justinyoo commented on .github/workflows/azure-dev-build-only.yml
> +        API_VERSION=$(grep -oP 'public const string Version = "\K[^"]+' ./src/AzureOpenAIProxy.ApiApp/Constants.cs)
아예 셸을 bash 대신 pwsh 로 하면 좀 더 쉽게 JSON 개체를 다룰 수 있습니다.

2024-08-23 08:01 UTC, justinyoo commented on .github/workflows/azure-dev-build-only.yml
> +        spectral lint openapi.json
스펙트럴 공식 액션이나 제가 제안한 다른 액션은 리포트 기능을 제공하는 걸로 알고 있습니다. 굳이 CLI를 직접 사용해야 하는 이유가 없다면 리포트 기능을 제공하는 기존의 액션을 사용해 보는 것을 고려해 보세요.

2024-08-23 08:03 UTC, justinyoo requested changes

2024-08-23 08:03 UTC, justinyoo commented on .github/workflows/azure-dev-build-only.yml
> +        API_VERSION=$(grep -oP 'public const string Version = "\K[^"]+' ./src/AzureOpenAIProxy.ApiApp/Constants.cs)
OpenAPI 버전을 `appsettings.json`으로부터 가져오는 기능은 별도의 이슈를 생성해서 그걸 먼저 해결하고 이리로 다시 넘어올까요?

2024-08-23 14:55 UTC, sikutisa commented on .github/workflows/azure-dev-build-only.yml
> +        spectral lint openapi.json
이슈에 남겨주셨던 Spectral linting이랑 Lint OpenAPI and AsyncAPI 확인 했었는데요. 마지막 업데이트가 각 8개월 전, 1년 전으로 오래 되기도 했고 이전 코멘트 https://github.com/aliencube/azure-openai-sdk-proxy/pull/243#discussion_r1724368399 에서 비슷한 말씀 주셨길래 CLI를 적용했었습니다.

2024-08-23 14:57 UTC, sikutisa commented on .github/workflows/azure-dev-build-only.yml
> +        API_VERSION=$(grep -oP 'public const string Version = "\K[^"]+' ./src/AzureOpenAIProxy.ApiApp/Constants.cs)
네. 저도 해당 이슈부터 처리하는게 더 좋을 것 같습니다.

2024-08-24 02:24 UTC, sikutisa commented on .github/workflows/azure-dev-build-only.yml
> +        spectral lint openapi.json
그럼 이 부분은 Spectral Linting 액션 적용하도록 하겠습니다.
https://github.com/marketplace/actions/spectral-linting

2024-08-24 02:44 UTC, sikutisa commented on .github/workflows/azure-dev-build-only.yml
> +        spectral lint openapi.json
Spectral Linting 적용 후 테스트 결과는 현재 아래처럼 확인할 수 있었습니다.
![image](https://github.com/user-attachments/assets/d0c76c17-00c4-4929-a3f4-13cf3b2657fb)
![image](https://github.com/user-attachments/assets/07e73f01-fce7-42a5-9597-e99fc64a6eef)

2024-08-24 05:42 UTC, justinyoo requested changes

2024-08-24 05:42 UTC, justinyoo commented on .github/workflows/azure-dev-build-only.yml
> +  contents: write
이거 원래대로 `read`로 돌려놓을까요?

2024-08-24 05:42 UTC, justinyoo commented on .github/workflows/azure-dev-build-only.yml
> +        if( $LINT_RESULT.Count -ge 1) {
`-ge 1` 대신 `-gt 0` 으로 가시죠

2024-08-24 05:42 UTC, justinyoo commented on .github/workflows/azure-dev-build-only.yml
> +        $LINT_RESULT = spectral lint -f json -F warn -D openapi.json
마지막에 `| ConvertFrom-Json` 추가해서 파워셸 콜렉션 개체로 변환시키면 좀 더 풍부하게 값을 활용할 수 있습니다.

2024-08-24 05:42 UTC, justinyoo commented on .github/workflows/azure-dev.yml
> +  contents: write
요기도 `read`로 바꿔주세요

2024-08-24 06:11 UTC, sikutisa commented on .github/workflows/azure-dev-build-only.yml
> +        spectral lint openapi.json
cli로 생성된 json의 경우 servers에 대한 정보가 누락된 채로 생성돼 항상 warning이 발생하게 됩니다. 따라서 app울 run 한 이후 swagger.json을 복사해 lint하는 방식으로 변경하였습니다.
깃헙 액션 상에서 에러 로그는 아래와 같이 표현되게 됩니다.
![image](https://github.com/user-attachments/assets/0cc7ce2b-cb08-4375-accd-362fa968b55b)

2024-08-24 06:12 UTC, sikutisa commented on .github/workflows/azure-dev-build-only.yml
> +  contents: write
변경하였습니다.

2024-08-24 06:12 UTC, sikutisa commented on .github/workflows/azure-dev-build-only.yml
> +        if( $LINT_RESULT.Count -ge 1) {
변경하였습니다.

2024-08-24 06:12 UTC, sikutisa commented on .github/workflows/azure-dev.yml
> +  contents: write
변경하였습니다.

2024-08-24 06:14 UTC, sikutisa commented on .github/workflows/azure-dev-build-only.yml
> +        $LINT_RESULT = spectral lint -f json -F warn -D openapi.json
아래와 같이 수정했습니다. 

```sh       
$LINT_RESULT = spectral lint -f json -F warn -D -q openapi.json | ConvertFrom-Json
        if( $LINT_RESULT.Count -gt 0) {
          $LINT_RESULT | ForEach-Object {
            echo ("code: " + $_.code)
            echo ("message: " + $_.message)
            echo ("path: " + $_.path)
            echo "`n"
          }
          exit 1
        }
발생한 에러에 대한 code, message, path 값을 보여주도록 하였습니다.

2024-08-24 06:22 UTC, justinyoo requested changes

2024-08-24 06:22 UTC, justinyoo commented on .github/workflows/azure-dev-build-only.yml
> +            echo ("path: " + $_.path)
`$_.path` 대신 `$($_.path -join ".")` 으로 바꾸면 가독성이 좀 더 높아질 듯?

2024-08-24 06:22 UTC, justinyoo commented on .github/workflows/azure-dev-build-only.yml
> +            echo ("path: " + $_.path)
`echo` 대신 `Write-Host`로 바꿔주세요.

2024-08-24 06:26 UTC, sikutisa commented on .github/workflows/azure-dev-build-only.yml
> +            echo ("path: " + $_.path)
반영하였습니다.

2024-08-24 06:26 UTC, sikutisa commented on .github/workflows/azure-dev-build-only.yml
> +            echo ("path: " + $_.path)
반영하였습니다.

2024-08-24 07:43 UTC, justinyoo approved these changes
LGTM!

2024-08-24 07:43 UTC, merged