[Playground] Component - Tab for system message and parameters (UI only) #225
aliencube/azure-openai-sdk-proxy pull request #244
Opened 2024-08-20 14:58 UTC by 5jisoo

## Description
- #225 
System Message 와 Parameters를 조정할 수 있는 Tab Component를 추가하였습니다.

## Summary of Changes
- ConfigTabComponent 추가 : 
`FluentUI`의 `FluentTab`을 사용하였으며, 탭 전환을 확인할 수 있도록 OnTabChange 이벤트를 추가해두었습니다.

## Questions
- Tab Component 테스트 작성에서 감을 잡지 못하고 있습니다

클릭한 tab의 id에 따라

```
<p id ="active-tab">[TEST] Active tab changed to: @SelectedTab?.Id</p>
```

이 부분의 텍스트에 해당 tab의 id가 포함되는가? 에 대해 작성하고자 했는데,
너무 하드 코딩의 테스트가 되어버리진 않을까 걱정되고, 근본적으로 이렇게 작성하는 게 맞는지도 의문이 드는 상태입니다!

2024-08-21 01:10 UTC, justinyoo requested changes
@5jisoo 코멘트 남겨뒀습니다. 일단 이것 전에 `/playground` 페이지 콤포넌트 만드는 PR 먼저 시작해 볼까요?

2024-08-21 01:10 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Program.cs
> +builder.Services.AddSingleton<Microsoft.FluentUI.AspNetCore.Components.LibraryConfiguration>();
이건 어디서 나온 건가요? 문서를 찾아봐도 없던데?

이 문서 보면 https://www.fluentui-blazor.net/CodeSetup#register-services

```csharp
builder.Services.AddFluentUIComponents();
```

이거 넣으라든데, 어떻게 다른 건가요?

이 이슈도 한 번 보세용: https://github.com/microsoft/fluentui-blazor/issues/1542

2024-08-21 01:10 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/Home.razor
> +<ConfigTabComponent @rendermode="InteractiveServer"/>
요거는 `Home.razor` 대신에 별도의 `Playgrounds.razor` 페이지 콤포넌트 만들고 거기에 올려볼까요? 그래야 나중에 before & after 를 잘 볼 수 있을 듯

2024-08-21 01:17 UTC, justinyoo commented
#6 👉 #245 👉 #246 순서로 참고해 보시고, 아무래도 이 PR보다 #246 관련 PR을 먼저 만들고 거기서 작업해 보는 게 나을 듯 합니다. 이건 그동안 홀드해 둘까요?

2024-08-22 23:19 UTC, justinyoo commented
@5jisoo 컨플릭 해결해 주세요!

2024-08-30 04:25 UTC, justinyoo requested changes
중복 라인 제거하시고, 이제 테스트 추가해 주세요!

2024-08-30 04:25 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/_Imports.razor
> +@using Microsoft.FluentUI.AspNetCore.Components
이 17번 라인은 중복입니다.

2024-08-30 04:25 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Program.cs
> +builder.Services.AddFluentUIComponents();
이 18번 라인도 중복입니다.

2024-08-31 06:40 UTC, justinyoo requested changes
테스트 메소드 구현 방식과 이벤트 핸들러 메소드 네이밍 쪽을 한 번 더 고민해 주세요.

2024-08-31 06:40 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/UI/ConfigTabComponentTest.cs
> +    }
이 테스트는 탭을 어디를 클릭했을 때 무슨 패널이 보여야 하는지 테스트하는 것이니, 탭이 두 개라면 탭 두개 모두 테스트를 해야 할 듯?

https://docs.nunit.org/articles/nunit/writing-tests/attributes/testcase.html

이 문서 참고해서 테스트를 짜 보세욥.

2024-08-31 06:40 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/Playground.razor
> +@using AzureOpenAIProxy.PlaygroundApp.Components.UI
이 `@using ...` 디렉티브도 `_Imports.razor` 쪽으로 옮겨 볼까요?

2024-08-31 06:40 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/ConfigTabComponent.razor
> +    private void HandleOnTabChange(FluentTab tab)
- 이 메소드를 `async Task` 로 처리하면 어때요? 그러면 맨 마지막에 `await Task.Complete` 같은 걸로 마무리하면 됨
- 이벤트 핸들러 메소드의 이름에는 `On`을 넣지 않습니다. 이미 핸들러 이름이 `OnTabChange` 이기 때문에 실제 뭘 핸들링하는지를 Verb + Object 형태로 작성해요. 예) `ChangeActiveTab` 같은 식이 될 수 있죠.

2024-08-31 07:14 UTC, 5jisoo commented
### 변경
1. 테스트 케이스 사용해서 두 탭 모두 테스트할 수 있도록 코드를 변경하였습니다.
2. HandleOnTabChange -> ChangeTab 네이밍 변경, async Task로 처리하였습니다.

2024-08-31 07:34 UTC, justinyoo approved these changes
좋습니다! LGTM!

2024-08-31 07:34 UTC, merged