[OpenAPI] Add endpoint for list of events #179
aliencube/azure-openai-sdk-proxy pull request #259
Opened 2024-08-22 17:10 UTC by Capella87

## Description 
* #179
 /events GET handler와, handler에서 사용할 Data Transfer Object 모델인 ```EventListEntity```, 해당 핸들러가 있는 ```EventEndpoint```를 추가하였습니다.

현재 ```GET``` handler는 샘플의 ```EventListEntity```를 생성해 반환하는 방식으로 구현되어 있습니다.

## Features on this PR

이벤트를 보여주기 위해 필요한 정보를 담는 클래스 두 개를 새로 정의했습니다.

### EventListEntity

```json
      "EventListEntity": {
        "required": [
          "endTime",
          "eventId",
          "eventName",
          "isActive",
          "OrganizerEmail",
          "organizerName",
          "registered",
          "startTime",
          "tz"
        ],
        "type": "object",
        "properties": {
          "eventId": {
            "type": "string",
            "description": "Event Id",
            "nullable": true
          },
          "eventName": {
            "type": "string",
            "description": "Event name",
            "nullable": true
          },
          "startTime": {
            "type": "string",
            "description": "Event start time",
            "format": "date-time",
            "nullable": true
          },
          "endTime": {
            "type": "string",
            "description": "Event end time",
            "format": "date-time",
            "nullable": true
          },
          "tz": {
            "type": "string",
            "description": "Event's time zone. It could be serialized to string",
            "nullable": true
          },
          "organizerName": {
            "type": "string",
            "description": "Organizer's name",
            "nullable": true
          },
          "OrganizerEmail": {
            "type": "string",
            "description": "Organizer's email address.",
            "format": "email",
            "nullable": true
          },
          "registered": {
            "type": "integer",
            "description": "The number of registered users",
            "format": "int32",
            "nullable": true
          },
          "resources": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/ResourceEntity"
            },
            "description": "List of resources that the organizer deploys",
            "nullable": true
          },
          "isActive": {
            "type": "boolean",
            "description": "Shows whether the event is active or not",
            "nullable": true
          }
        },
        "additionalProperties": false,
        "description": "Data transfer model for showing all events"
      },
```
해당 클래스는 내부에 리소스 정보를 담기 위해 ResourceEntity라는 서브 클래스 정의를 갖고 있습니다.

### ResourceEntity

```json
"ResourceEntity": {
        "required": [
          "id",
          "name"
        ],
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "Resource's Id",
            "nullable": true
          },
          "name": {
            "type": "string",
            "description": "Resource's name. e.g. gpt4o",
            "nullable": true
          }
        },
        "additionalProperties": false,
        "description": "Define the list entity of Resources"
      },
```
Azure 쪽에서는 리소스(예: gpt4o)를 표시하고 있었기 때문에 추가하였습니다. 이 클래스에서는 리소스 ID와 이름만 들어 있습니다. 리소스에 대한 자세한 정보를 담는 클래스는 별도로 정의될 것 같습니다.

### Endpoint

이벤트 목록을 반환하는 GET 메소드를 ```MapGet```을 통해 ```/events``` 경로 하에 정의하였으며, 해당 메소드를 갖고 있는 endpoint를 ```RouteHandlerBuilder```를 사용하여 ```EventEndpoint```로 정의하였습니다.

```json
"paths": {
    "/events": {
      "get": {
        "tags": [
          "events"
        ],
        "summary": "Get all events",
        "description": "Show all events in Azure OpenAI Proxy services.",
        "operationId": "GetEvents",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/EventListEntity"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/problem+json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemHttpResult"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/problem+json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemHttpResult"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/problem+json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemHttpResult"
                }
              }
            }
          }
        }
      }
    },
```

아울러, 페이로드를 정의해야 했으나 현재 구현에서는 샘플 객체를 반환하는 방식으로만 구현했고, Authorization 관련 구현이 없어 따로 정의하지는 않았습니다.

```events```는 TypedResults를 이용해 정상적으로는 200 OK를 반환하며, Authorization 없는 접근의 경우 401번, 찾을 수 없었던 경우면 404번, 서버에 문제가 생긴 경우 500번을 반환하게 정했습니다.

해당 에러가 발생하는 경우 application/problem+json MIME으로 반환하게 됩니다.

### 기타 변경점
* Swashbuckle에서 XML comment를 파싱하여 description을 작성하게 Swagger 설정 추가

해당 endpoint에 관련된 테스트도 추가하겠습니다.

감사합니다.

2024-08-22 23:29 UTC, justinyoo commented
@Capella87 머지 컨플릭트 먼저 해결해 주세요!

2024-08-23 01:44 UTC, Capella87 commented
충돌 해결했습니다

2024-08-23 05:29 UTC, justinyoo requested changes
코멘트 남겨뒀습니다. 무언가 새로운 것을 도입하고 싶다면, 별도의 이슈를 생성하고 거기서 논의를 거쳐 그것을 바탕으로 다른 PR을 생성해 주세요. 새로운 것은 이 태스크의 스코프가 아닙니다.

2024-08-23 05:29 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/AzureOpenAIProxy.ApiApp.csproj
> +    <ImplicitUsings>enable</ImplicitUsings>
이건 build.props 파일 안에 이미 정의가 되어 있습니다.

2024-08-23 05:29 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/AzureOpenAIProxy.ApiApp.csproj
> +    <NoWarn>$(NoWarn);1591</NoWarn>
이건 어떤 의미에서 넣은 건가요?

2024-08-23 05:29 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/AzureOpenAIProxy.ApiApp.csproj
> +    <GenerateDocumentationFile>true</GenerateDocumentationFile>
XML 코멘트 기반으로 OpenAPI 문서를 생성하지 않으니 필요가 없습니다.

2024-08-23 05:29 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Endpoints/EventEndpoint.cs
> +    /// </summary>
아래 링크 참조해서 주석 작성해 주세요:

https://github.com/aliencube/azure-openai-sdk-proxy/blob/c7100726eff14cd9448a57b419f988835edec201/src/AzureOpenAIProxy.ApiApp/Endpoints/ChatCompletionsEndpoint.cs#L12-L14

2024-08-23 05:29 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Endpoints/EventEndpoint.cs
> +        /// <returns></returns>
여기 참조해서 주석 작성해 주세요:

https://github.com/aliencube/azure-openai-sdk-proxy/blob/c7100726eff14cd9448a57b419f988835edec201/src/AzureOpenAIProxy.ApiApp/Endpoints/ChatCompletionsEndpoint.cs#L17-L21

2024-08-23 05:29 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Endpoints/EventEndpoint.cs
> +                ) =>
들여쓰기

2024-08-23 05:29 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Endpoints/EventEndpoint.cs
> +                ) =>
GET 방식인데 `HttpRequest` 개체가 필요한가요?

https://github.com/aliencube/azure-openai-sdk-proxy/blob/c7100726eff14cd9448a57b419f988835edec201/src/AzureOpenAIProxy.ApiApp/Endpoints/WeatherForecastEndpoint.cs#L22

2024-08-23 05:29 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Endpoints/EventEndpoint.cs
> +                    return TypedResults.Ok(sampleEvents);
비지니스 로직은 지금 구현하지 않습니다. 아래 코드 참고하세요:

https://github.com/aliencube/azure-openai-sdk-proxy/blob/c7100726eff14cd9448a57b419f988835edec201/src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEventEndpoints.cs#L24-L26

2024-08-23 05:29 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Endpoints/EventEndpoint.cs
> +                // Note: RouteHandlerBuilder does not have ProducesProblem extension method yet, but it will be added on .NET 9
현재 일어나지 않은 일은 주석으로도, 구현으로도 할 필요가 없습니다.

2024-08-23 05:29 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Endpoints/EventEndpoint.cs
> +                .Produces<ProblemHttpResult>(statusCode: StatusCodes.Status500InternalServerError, contentType: "application/problem+json")
- 4XX 에러는 굳이 리턴 타입을 정의할 필요가 없습니다.
- 5XX 에러는 문자열 타입으로 정의해 주세요.

2024-08-23 05:29 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Endpoints/EventEndpoint.cs
> +                    operations.Summary = "Get all events";
기본적으로 이 리스트는 로그인한 사용자가 가입한 이벤트만을 반영합니다. (현재 가정은 모두 로그인을 했다는 가정입니다.) 따라서 해당 써머리와 디스크립션도 그에 맞게 반영해 주세요

2024-08-23 05:29 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Extensions/ServiceCollectionExtensions.cs
> +            options.IncludeXmlComments(Assembly.GetExecutingAssembly());
우리는 XML 기반 OpenAPI 문서 생성 기능을 사용하지 않습니다.

2024-08-23 05:29 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Models/EventListEntity.cs
> +public class EventListEntity
클래스 이름 일관성을 유지해 주세요. 여기서는 `EventDetails` 정도쯤이 될 겁니다. `AdminEventDetails` 클래스를 참조해 주세요.

2024-08-23 05:29 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Program.cs
> +app.UseSwagger();
이미 바로 위 `UseSwaggerUI(basePath)` 익스텐션 메소드 안에 정의해 두었습니다.

2024-08-23 05:31 UTC, justinyoo commented
@Capella87 로컬에서 빌드가 성공하든가요? 로컬에서 빌드가 성공하는지 확인하시고 커밋해 보세요.

2024-08-23 07:20 UTC, Capella87 commented
> @Capella87 로컬에서 빌드가 성공하든가요? 로컬에서 빌드가 성공하는지 확인하시고 커밋해 보세요.

확인한 결과 ```ServiceCollectionExtensions```에서 ```SecretClient``` 가 정의된 ```Azure.Security.KeyVault.Secrets```와 ```DefaultAzureCredential```이 정의된 ```Azure.Identity``` 네임스페이스가 소스 코드에 누락되어 있어 추가했습니다.

2024-08-23 07:45 UTC, Capella87 commented
## 수정한 점
* ```EventListEntity```를 ```EventDetails```로 이름을 변경하고, Admin 클래스에 맞추어 프로퍼티도 수정했습니다. (946c381)
* ```EventDetails```와 ```EventEndpoint```에 있는 주석을 규칙에 맞게 다시 작성했습니다. (bf5c999)
* 중복되거나 불필요한 설정을 전부 제거했습니다. (8e1e71a, c03c5d1, 99616eb)
* ```EventEndpoint```의 handler의 HttpRequest 매개변수를 삭제했습니다. (78927ac)
* ```EventEndpoint```의 handler가 ```Results.Ok()```를 반환하게 수정했습니다. (bf5c999, 2326d7e)
* Endpoint의 OpenAPI annotation 중 오류 발생시 반환하는 코드와 관련된 부분을 수정했습니다. (86ed5ec)
* Endpoint의 OpenAPI summary와 description을 '로그인된 사용자가 참여한 이벤트를 보여준다'는 내용을 포함하게 수정했습니다. (343db20)

2024-08-23 08:06 UTC, justinyoo commented
> 확인한 결과 `ServiceCollectionExtensions`에서 `SecretClient` 가 정의된 `Azure.Security.KeyVault.Secrets`와 `DefaultAzureCredential`이 정의된 `Azure.Identity` 네임스페이스가 소스 코드에 누락되어 있어 [fb3e867](https://github.com/aliencube/azure-openai-sdk-proxy/commit/fb3e867579ef53a03ef6e2bba6b221bd82d4fed8) 에서 추가했습니다.
> 
> 추가한 이후 빌드와 테스트가 성공했습니다.

그렇지 않습니다 최신 코드를 받아보세요. 이미 누락됐다고 하는 코드는 한참전에 추가되어 있었어요. 지금 이상태라면 자신의 코드가 가장 최신을 반영하고 있는지 먼저 검토해 보는 것을 추천합니다.

2024-08-23 08:08 UTC, justinyoo commented
> ## 수정한 점
> * `EventListEntity`를 `EventDetails`로 이름을 변경하고, Admin 클래스에 맞추어 프로퍼티도 수정했습니다. ([946c381](https://github.com/aliencube/azure-openai-sdk-proxy/commit/946c381ca2f6da92761a86ac045b70c35c7d5f4c))
> * `EventDetails`와 `EventEndpoint`에 있는 주석을 규칙에 맞게 다시 작성했습니다. ([bf5c999](https://github.com/aliencube/azure-openai-sdk-proxy/commit/bf5c99956d66c8d6c70665487da8308074240086))
> * 중복되거나 불필요한 설정을 전부 제거했습니다. ([8e1e71a](https://github.com/aliencube/azure-openai-sdk-proxy/commit/8e1e71a865cdfac0d2d928e15f2ad6a9d94ad5df), [c03c5d1](https://github.com/aliencube/azure-openai-sdk-proxy/commit/c03c5d17485ee88959d350e0bd5cd0f8b43cb972), [99616eb](https://github.com/aliencube/azure-openai-sdk-proxy/commit/99616eb4a0ba50499d99a20fca1cba575835a09c))
> * `EventEndpoint`의 handler의 HttpRequest 매개변수를 삭제했습니다. ([78927ac](https://github.com/aliencube/azure-openai-sdk-proxy/commit/78927ac64a1822b121477a453d37e8448367bfe2))
> * `EventEndpoint`의 handler가 `Results.Ok()`를 반환하게 수정했습니다. ([bf5c999](https://github.com/aliencube/azure-openai-sdk-proxy/commit/bf5c99956d66c8d6c70665487da8308074240086), [2326d7e](https://github.com/aliencube/azure-openai-sdk-proxy/commit/2326d7ed84907c5d78946a7559165b39cdd678e0))
> * Endpoint의 OpenAPI annotation 중 오류 발생시 반환하는 코드와 관련된 부분을 수정했습니다. ([86ed5ec](https://github.com/aliencube/azure-openai-sdk-proxy/commit/86ed5ec77f6e2600a049f76f0ad05fc81c3ca5d2))
> * Endpoint의 OpenAPI summary와 description을 '로그인된 사용자가 참여한 이벤트를 보여준다'는 내용을 포함하게 수정했습니다. ([343db20](https://github.com/aliencube/azure-openai-sdk-proxy/commit/343db20a9b8876ef0d5914f1490c5d3f65b972db))

다른 코멘트에서도 언급을 했지만, 현재 변경사항이 최신 코드베이스에서 한 것인지 의구심이 듭니다. 자신의 코드베이스를 최신화 한 후에 이 변경사항을 적용시켜보시고, 그리고 다시 PR을 생성해 주세요.

2024-08-24 05:24 UTC, justinyoo requested changes

2024-08-24 05:24 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Extensions/ServiceCollectionExtensions.cs
이 파일은 변경사항이 없는데...요?

2024-08-24 05:24 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Models/EventDetails.cs
> +public class EventDetails
이 `EventDetails` 클래스는 어드민이 아닌 사용자가 보는 거잖아요? 그러면, 지금 이 `EventDetails` 클래스는 `AdminEventDetails` 클래스보다 적은 정보만 갖고 있어야 할텐데, 지금은 클래스 이름만 다를 뿐 동일합니다. 어떻게 하면 어드민에게는 필요하지만 사용자에게는 필요하지 않은 정보를 감출 수 있을까요?

2024-08-24 05:24 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Program.cs
> +using Microsoft.OpenApi.Models;
여기 추가된 `using ...` 디렉티브들이 필요한가요?

2024-08-24 05:56 UTC, Capella87 commented on src/AzureOpenAIProxy.ApiApp/Extensions/ServiceCollectionExtensions.cs
해당 파일의 마지막 줄에 개행 문자가 삽입되어서 일어난 것 같습니다.

2024-08-24 06:01 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Extensions/ServiceCollectionExtensions.cs
그러면 아예 수정한 내용이 없으니까 코드 변경에서 뺄 수 있을까요?

2024-08-24 07:19 UTC, Capella87 commented
## 수정한 점
* ```AdminEventDetails```가 ```EventDetails```를 상속하게 리팩토링 (e4c9859)
* 불필요한 namespace 삭제 (f46d996)

2024-08-24 08:09 UTC, justinyoo requested changes

2024-08-24 08:09 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Endpoints/EventEndpoint.cs
> +        .Produces<EventDetails>(statusCode: StatusCodes.Status200OK, contentType: "application/json")
이벤트 리스트를 가져오는 부분이니 `EventDetails`가 맞나요? `List<EventDetails>`가 맞을 듯?

2024-08-24 08:13 UTC, justinyoo requested changes

2024-08-24 08:13 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Endpoints/EventEndpoint.cs
> +        .WithTags("events")
요거 때문에 로컬에서는 몰라도 푸시하면 빌드 fail 날 거예요. 요 파일도 수정해야 함: https://github.com/aliencube/azure-openai-sdk-proxy/blob/main/src/AzureOpenAIProxy.ApiApp/Filters/OpenApiTagFilter.cs

2024-08-24 08:43 UTC, justinyoo requested changes
잘하셨습니다! 이제 테스트코드를 작성해 주세요!

2024-08-26 02:48 UTC, Capella87 commented
# 추가한 점
* ```EventEndpoint```에서 경로 반환, verb 테스트, 태그 반환, 값 반환, 객체 반환, 응답(response) 반환에 대한 xUnit 테스트 코드 작성

2024-08-27 03:16 UTC, justinyoo commented
@Capella87 컨플릭 났어요~!

2024-08-27 03:18 UTC, Capella87 commented
@justinyoo 해결했습니다.

2024-08-28 02:43 UTC, justinyoo approved these changes
좋습니다! 고생하셨어요!

2024-08-28 02:43 UTC, merged