[Playground] Component - list of deployment models (UI only) #172
aliencube/azure-openai-sdk-proxy pull request #260
Opened 2024-08-23 01:17 UTC by yjchun626

## 개요
- [[Playground] Component - list of deployment models (UI only) #172](https://github.com/aliencube/azure-openai-sdk-proxy/issues/172)
- 목표: Playground App 내에서 'List of deployment model' 용도로 사용할 드롭다운 UI 컴포넌트를 구현

## 구현 내용
### 1. DeploymentModelListComponent 생성
- PlaygroundApp 프로젝트 내 'Components/UI'에 UI 컴포넌트 **'DeploymentModelListComponent.razor'** 파일 생성
- FluentUI - FluentSelect와 FluentOption을 사용해 컴포넌트 구현
- 데이터는 FluentOption으로 하드코딩 처리 
- Home.razor에 컴포넌트 추가하여 로컬에서 작동 확인하였습니다.
<img width="709" alt="image" src="https://github.com/user-attachments/assets/bf3062ac-36c5-49a8-84cf-8b44358288a1">

### 2. 테스트 추가
- Playwright(통합 테스트)와 BUnit(컴포넌트 단위 테스트)을 이용해 **'DeploymentModelListComponentTests.cs'** 파일 작성
#### 2-1. Playwright
- 드롭다운 UI가 포함된 페이지 전체(여기서는 Tests.razor)를 테스트하기 위해 코드를 작성해보았습니다.
#### 2-2. BUnit
- 기존의 PlaygroundApp 프로젝트를 ProjectReference에 넣어 Components/UI 부분을 직접 참조하는 방식으로 진행했습니다.
- 현재 **(1) 드롭다운 UI가 올바르게 렌더링 되고, 모든 옵션이 잘 표시되는지 확인**, 
**(2) 옵션 값이 선택되면 ValueChanged 이벤트가 트리거되고, 선택된 값으로 업데이트 되는지 확인** 
- 이렇게 총 2개의 테스트 코드를 작성해두었습니다.

## 잘 모르겠는 점
- 지금은 UI 컴포넌트 구현에만 집중해서 데이터를 하드코딩 해 놓았는데(FluentOption 단순히 나열), 추후 OpenAPI에서 deployment model을 받아올 것을 생각하고 'DeploymentModelListComponent.razor'에 미리 더 추가하거나 수정해야 할 내용이 있는지 궁금합니다.
- Playwright와 BUnit으로 테스트를 작성해서 일단 돌려보니 체크 표시가 뜨고 통과는 되었는데, 제가 처음 작성하는 것이다 보니 테스트가 다른 곳에서도 돌릴 수 있게 제대로 짠 것인지 잘 모르겠습니다.
     - 테스트는 README 파일에 추가된 테스트 방법으로 로컬에서 확인하고, 제 fork된 리포지토리에서 workflow가 끝까지 돌아간 것까지 확인했습니다.

2024-08-23 05:57 UTC, justinyoo requested changes
코드리뷰 남겼습니다. 중복코드 삭제와 bUnit 사용하지 않는 방향으로 고민해 봐 주세요

2024-08-23 05:57 UTC, justinyoo commented on Directory.Build.props
> +    <NUnit3TestAdapterVersion>4.*</NUnit3TestAdapterVersion>
중복 코드라서 빼도 됩니다

2024-08-23 05:57 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/App.razor
> +<script src="_content/Microsoft.FluentUI.AspNetCore.Components/Microsoft.FluentUI.AspNetCore.Components.lib.module.js"
중복 코드라서 빼도 됩니다

2024-08-23 05:57 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/DeploymentModelListComponent.razor
> +    <p>Selected Value: @selectValue</p>
들여쓰기

2024-08-23 05:57 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/DeploymentModelListComponent.razor
> +    <p>none</p>
들여쓰기

2024-08-23 05:57 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Program.cs
> +builder.Services.AddFluentUIComponents();
중복 코드라서 빼도 됩니다

2024-08-23 05:57 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/AzureOpenAIProxy.PlaygroundApp.Tests.csproj
> +    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" Version="$(FluentUIVersion)" />
빼도 됩니다

2024-08-23 05:57 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/AzureOpenAIProxy.PlaygroundApp.Tests.csproj
> +  </ItemGroup>
지금 단계에서는 bUnit 대신 Playwright 만 사용하는 방향으로 고민해 보시죠. 주석 풀지 말아주세요.

2024-08-23 05:57 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/AzureOpenAIProxy.PlaygroundApp.Tests.csproj
> +    <PackageReference Include="bunit" Version="1.31.3" />
지금 상황에서는 일단 bUnit을 안 쓰는 방향으로 고민해 보시죠.

2024-08-23 05:57 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/AzureOpenAIProxy.PlaygroundApp.Tests.csproj
> +    </PackageReference>
필요 없습니다.

2024-08-23 05:57 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/UI/DeploymentModelListComponentTests.cs
> +        public async Task NavigateToTargetPage()
NUnit 컨벤션상 SetUp 메소드는 `Init()` 일 겁니다.

2024-08-23 05:57 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/UI/DeploymentModelListComponentTests.cs
> +        public async Task IsThereAHeading()
기존 테스트 메소드처럼 `Given___When___Then` 형태로 적어주세요.

2024-08-23 05:57 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/UI/DeploymentModelListComponentTests.cs
> +        public async Task IsThereADropdownComponent()
기존 테스트처럼 `Given___When___Then` 형식으로 적어주세요.

2024-08-23 05:57 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/UI/DeploymentModelListComponentTests.cs
> +            var userSelectedOptionValue = await fluentSelect.EvaluateAsync<string>("el => el.value"); // Get the selected value
여기도 마찬가지로 Arrange/Act/Assert 가 혼재되어 있고, 하나의 테스트 메소드 안에서 여러개를 테스트하고 있습니다.

2024-08-23 05:57 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/UI/DeploymentModelListComponentTests.cs
> +            // Arrange & Act
일단 bUnit 관련 테스트는 삭제하는 걸로 하시죠. 조금 더 고민을 해 봐야겠습니다.

2024-08-24 01:39 UTC, justinyoo requested changes
컴포넌트가 자신의 외부로 값을 넘길 때 사용하는 이벤트콜백에 대해 고민을 해 보셔야 합니다.

2024-08-24 01:39 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/App.razor
이 `App.razor` 파일 자체를 수정할 이유가 없습니다. 최신 코드베이스 기준으로 본인 변경사항만 보이게 해 보세요.

2024-08-24 01:39 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/DeploymentModelListComponent.razor
> +        <h6>
`<label>` 엘리멘트 안에 `<h6>` 헤딩 엘리먼트 넣는 것이 시맨틱한가요?

2024-08-24 01:39 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/DeploymentModelListComponent.razor
> +        }
이건 디버깅용으로 넣은 것 같은데, 빼도 됩니다.

2024-08-24 01:39 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/DeploymentModelListComponent.razor
> +    public string? selectValue { get; set; }
요렇게 하면 상위 컴포넌트에서 이 컴포넌트의 값을 못 갖고 올 걸요?

이 페지이의 이벤트 콜백 섹션 참고해 보세요: https://learn.microsoft.com/ko-kr/aspnet/core/blazor/components/event-handling

2024-08-27 02:48 UTC, justinyoo requested changes

2024-08-27 02:48 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/App.razor
> +        type="module" async></script>
이건 굳이 줄바꿈을 한 이유가 있나요?

2024-08-27 02:48 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/DeploymentModelListComponent.razor
> +    public string? selectedValue { get; set; }
이 파라미터는 어디에 쓰는 건가요?

2024-08-27 02:48 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/DeploymentModelListComponent.razor
> +    public Option<string>? selectedOption { get; set; }
이 값을 초기화하는 게 필요하지 않을까요? 예를 들자면...

```csharp
public Option<string>? selectedOption { get; set; } = new();
```

아니면 `OnInitializeAsync()` 같은 메소드를 통해 초기화 한다거나?

2024-08-27 02:48 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/DeploymentModelListComponent.razor
> +        }
`if { ... }` 블록의 depth를 낮춰보세요.

2024-08-27 02:54 UTC, justinyoo commented
테스트에서 Given/When/Then은 보통 BDD (행위 기반 개발) 관점에서 많이 쓰는 컨벤션인데,

- Given: 미리 주어지는 조건 혹은 가정
- When: 실제로 어떤 행위를 함
- Then: 예상하는 결과

라고 대충 생각하시면 됩니다.

따라서, 테스트에서 Arrange/Act/Assert 구분이 Given/When/Then 하고 얼추 겹친다고 생각해 보시면 됩니다. 그렇다면 `Expect(...)` 구문은 Then 영역 (혹은 Assert 영역)에 속하겠죠? 테스트 메소드는 내가 어떤 인풋값을 가지고 어떤 행위를 했을 때 어떤 결과가 나와야 한다는 걸 표현하는 거니까, 하나의 메소드 안에서 여러개의 결과를 확인하는 것은 뭔가 좀 이상하지 않을까요?

2024-08-27 02:55 UTC, justinyoo commented
`Page.Locator()` 많이 쓰셔도 됩니다.

2024-08-27 02:56 UTC, yjchun626 commented on src/AzureOpenAIProxy.PlaygroundApp/Components/App.razor
> +        type="module" async></script>
앗 맨처음에 App.razor 수정할 필요 없다고 피드백 해주신 이후로 건드린 적이 없어서 왜 줄바꿈이 되었는지 정확히는 모르겠습니다. 
다만 제 생각에 vscode 저장 시 자동정렬 설정이 켜져있어서 그랬던 것 같습니다. 위에서 들여쓰기 피드백 주신 것도 그 설정 때문에 계속 일어난 것이라, 자동정렬 설정을 꺼서 해결했습니다. 
일단 줄바꿈 해제하고 원래대로 돌려놓겠습니다.

2024-08-27 06:05 UTC, yjchun626 commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/DeploymentModelListComponent.razor
> +    public string? selectedValue { get; set; }
초반에 테스트 코드 작성할 때 `await Page.EvaluateAsync<string>("() => document.querySelector('fluent-select#deployment-model-list').value");` 부분 수정할 때 아마도 쓰이지 않을까 하고 남겨뒀었는데, 이번에 코드 수정하고 테스트 반복하다 보니 필요없는 것 같아 삭제했습니다.

2024-08-28 02:37 UTC, justinyoo requested changes

2024-08-28 02:37 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/Tests.razor
> +    }
혹시 `OnAfterRenderAsync()` 메소드와 `OnInitializeAsync()` 메소드의 차이를 알아보고 둘 중 어떤 것이 여기에 적합한지 설명해 주실 수 있나요?

2024-08-28 02:37 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/DeploymentModelListComponent.razor
> +    [Parameter]
이 `[Parameter]` 데코레이터가 `selectedOption` 에 필요한가요? 좀 더 정확하게는 이 값을 컴포넌트 외부로 노출시킬 필요가 있나요?

2024-08-28 02:37 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/DeploymentModelListComponent.razor
> +    public EventCallback<string> UserSelectedOption { get; set; }
보통 이벤트 콜백은 `On...`으로 시작합니다. 따라서 `OnOptionSelected` 또는 `OnUserOptionSelected` 정도가 적당합니다. 그렇게 해야, 부모 컴포넌트에서 "아 이게 이벤트 콜백이겠구나~"하고 인지할 수 있어요.

2024-08-28 02:37 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/UI/DeploymentModelListComponentTests.cs
> +        public async Task Teardown()
`[TearDown]` 데코레이터를 쓰는 메소드는 보통 `CleanUp`이라는 이름을 관례적으로 붙입니다.

2024-08-28 02:37 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/DeploymentModelListComponent.razor
> +    }
`selectedOption` 필드값을 초기화하는 용도로 이 `OnInitializeAsync` 메소드를 사용하는 것과 그냥 23번 라인을 `... selectedOption { get; set; } = new();` 하는 것과 어떤 것이 좀 더 간결한 것같으세요?

2024-08-28 02:37 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/UI/DeploymentModelListComponentTests.cs
> +        public async Task Given_ComponentLabel_When_Waiting_Then_ShouldBeVisible()
`When...` 쪽에서는 실제로 어떤 것을 하는지가 나타나야 합니다. 지금 이 메소드를 예로 들자면 `When_Page_Loaded` 같은 식이 되겠죠?

`Then...` 쪽에서는 보통 `Then_It_Should_(expectation)`과 같은 형태로 사용합니다. 다른 테스트 메소드 이름들을 한 번 보시고 비슷하게 맞춰보세요.

2024-08-28 05:22 UTC, yjchun626 commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/Tests.razor
> +    }
### 궁금한 점
1. `OnInitializedAsync`를 사용할 때 동기/비동기의 차이가 부모-자식 간 초기화 순서 보장 유무라고 이해했는데, 나중에 드롭다운 컴포넌트의 로직(deployment model 선택 시 적용)을 구현할 것을 고려해서 페이지와 동기하는 방식으로 설정하는 것이 나은지 궁금합니다.
     - deployment model 선택 시 그 데이터가 플레이그라운드 내에서 타고 타고... chat 할 때 적용되기까지 기다려야 될 것 같다고 생각했습니다.
2. `OnInitialized` 메소드를 보통 단일 UI 컴포넌트가 아닌 컴포넌트들을 여러 개 모아놓는 페이지 같은 부모 컴포넌트에 주로 사용하는 것이 맞을까요? 
     - 수명 주기 자료들을 찾아보면 대체로 부모 컴포넌트를 예로 든 것이 많고, `OnInitialized`부터 시작해서 뒤따라오는 메소드가 굉장히 많은데 부모 컴포넌트에서 각 자식 컴포넌트 컨트롤을 전체적으로 관리하기 위해 사용하는 것으로 보여져서 궁금합니다.
     - 다만 `OnParametersSet`은 부모 컴포넌트에서 자식으로 매개변수를 전달받을 때 매개변수를 설정하는 메소드라고 이해했습니다.
> selectedOption 필드값을 초기화하는 용도로 이 OnInitializeAsync 메소드를 사용하는 것과 그냥 23번 라인을 ... selectedOption { get; set; } = new(); 하는 것과 어떤 것이 좀 더 간결한 것같으세요?
- 그리고 위에서 찾아본 것들과 같이 피드백을 보니 드롭다운 컴포넌트 내에서 꼭 `OnInitializedAsync`를 사용해서 필드값을 초기화할 필요가 없어보여서 `selectedOption { get; set; } = new();`로 초기화하는 방향으로 가려고 합니다!

2024-08-28 05:35 UTC, yjchun626 commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/DeploymentModelListComponent.razor
> +    [Parameter]
헉 
`[Parameter]` 데코레이터가 단순히 selectedOption 값을 다른 컴포넌트에 보내고 하기 위해서는 필요한 줄로만 알고 있었습니다. (그리고 다른 분들 것 잠깐씩 확인해볼 때 파라미터에 데코레이터 달아놓으셨길래 저도 따라 쓴 감도... 있습니다.) 
나중에 선택된 옵션 값 `selectedOption.Value`를 이벤트로 여기저기 보내는 일은 생기더라도 `selectedOption` 필드 자체가 컴포넌트 외부로 노출될 필요는 없어보여서 해당 데코레이터 삭제하는 방향으로 결정했습니다.

2024-08-28 05:54 UTC, yjchun626 commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/UI/DeploymentModelListComponentTests.cs
> +        public async Task Given_ComponentLabel_When_Waiting_Then_ShouldBeVisible()
넵 알겠습니다!! 테스트 코드에서는 테스트 메소드 이름만 수정하면 될까요? 아니면 given when then 구분이나 코드를 좀 더 점검하는게 필요한가요?

2024-08-28 06:42 UTC, yjchun626 commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/UI/DeploymentModelListComponentTests.cs
> +        public async Task Given_ComponentLabel_When_Waiting_Then_ShouldBeVisible()
우선은 테스트 메소드 이름까지 수정하고 커밋하겠습니다

2024-08-28 09:44 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/Tests.razor
> +    }
크으으 훈늉하게 조사하셨네영. 조사하신 내용들을 다른 멘티들과 함께 공유해 보셔도 좋을 듯 합니다.

1. 동기식은 쓰레드 블록킹이고, 비동기식은 쓰레드 논블록킹입니다. 순서 보장하고는 상관 없어요. `async`/`await` 만 잘 쓰면 됩니다. 못먹어도 비동기식 고고고!
2. 컴포넌트 초기화에 `OnInitializedAsync` 메소드를 쓰는 거구요, 각 컴포넌트마다 필요할 때 쓰면 됩니다. 초기화 하는 대상은 여러가지가 있을 수 있겠죠?

2024-08-28 09:44 UTC, justinyoo commented
지금 계속 빌드가 깨지는데 로컬에서는 빌드가 잘 돌아가던가요?

2024-08-28 10:00 UTC, yjchun626 commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/Tests.razor
> +    }
네넵 간단하게 정리해주신 덕분에 좀 더 확신 갖고 정리할 수 있을것 같아요 감사합니다!!

2024-08-28 10:41 UTC, yjchun626 commented
어디다 작성해놔야 좋을지 잘 모르겠어서 일단 기록용으로 코멘트에 작성하겠습니다! (resolved 처리되니까 링크가 안 먹히더라고요) 

---
## Blazor 컴포넌트 수명 주기 메소드 조사 배경
> 혹시 OnAfterRenderAsync() 메소드와 OnInitializeAsync() 메소드의 차이를 알아보고 둘 중 어떤 것이 여기에 적합한지 설명해 주실 수 있나요?
- 현재 작업 중인 `DeploymentModelListComponent.razor` 드롭다운 UI 컴포넌트를 자식으로 갖는, `Tests.razor` 페이지 컴포넌트에서 용도를 잘 모르고 `OnAfterRenderAsync()`를 사용하고 난 뒤 피드백을 받게 돼서 조사하게 되었습니다.

## 결론부터 말씀드리면 
- `OnInitializedAsync()` 메소드를 사용하는 것이 적합한 것 같습니다.
     - (`OnAfterRender`는 UI 이벤트가 트리거 된 이후의 프로세스이므로) 
     - `OnInitializedAsync()`와 `OnInitialized()` 중에 무엇을 사용해야 할지는 고민이 있습니다. (아래에 궁금한 점을 따로 코멘트로 달아놓았습니다.)

## 이전에 생각했던 것
- 제가 참고했던 자료: [ASP.NET Core Razor 구성 요소 수명 주기](https://learn.microsoft.com/ko-kr/aspnet/core/blazor/components/lifecycle?view=aspnetcore-8.0&preserve-view=true#component-initialization-oninitializedasync)
1. `OnInitializedAsync()` - 컴포넌트 초기화
     - 작업 중인 컴포넌트가 드롭다운 목록이고 정적으로 option을 로드하므로 매개변수 영향이 없음 -> `DeploymentModelListComponent.razor`에서 사용
2. `OnAfterRenderAsync()` - 컴포넌트를 **대화형 렌더링** 후 업데이트 완료가 된 뒤에 호출
     - 페이지 로드 - 컴포넌트 렌더링하고 나서 1회 수행
- 코드를 작성할 때 저는 Tests.razor가 `@rendermode InteractiveServer` 대화형 렌더링 모드를 사용하고 있기 때문에 페이지 초기화 수행을 명시해줘야 할 지 헷갈렸던 것 같습니다. 
(개념 확립하지 않고서 페이지도 결국 컴포넌트인데 그 점을 간과했던 것 같습니다...)
- 그리고 `OnAfterRenderAsync()`을 사용함으로써, 앞서 `OnInitializedAsync()`로 초기화된 UI 컴포넌트를 렌더링 해서 불러오면 이후에 페이지가 잘 받아와서 전체적으로 렌더링 되었는지 최초 확인해주는 메소드라고 생각했습니다. 
- 결론: **완전** 헛다리 짚고 있었습니다. (...)

## 이번에 알게 된 것
![image](https://github.com/user-attachments/assets/b08ccf6f-893f-4fe9-b6c5-188f90ccfcc5)

- 참고한 글: [Component lifecycles - Blazor University](https://blazor-university.com/components/component-lifecycles/), [Should I use OnAfterRenderAsync instead of OnInitializedAsync?](https://stackoverflow.com/questions/69374767/should-i-use-onafterrenderasync-instead-of-oninitializedasync)

- `OnAfterRender`는 DOM 이벤트 프로세스의 일부며, 렌더러가 DOM 업데이트 이벤트를 수신함으로써 구동됨
- ex. 페이지에서 버튼 클릭 등 이벤트 발생 -> `OnInitialized` 이후에 StateHasChanged 호출되면 렌더링 발생 -> 그제서야 `OnAfterRender` 발생
- blazor 컴포넌트의 수명 주기에서 `OnInitialized`와 `OnAfterRender`는 별개의 프로세스고, 특히 `OnAfterRender`는 언제 실행될지 보장할 수 없으며 **일반적으로 JSInterop 작업을 할 때만 사용**해야 함
- 따라서 UI 이벤트 핸들러를 작성하더라도 `OnInitialized{Async}/OnParametersSet{Async}`에 등록해야 함
     - `OnInitialized`는 구성 요소가 완전히 로드되면 실행되며, UI의 각 컨트롤이 초기화 이벤트 이후에 발생하므로, 이 이벤트에서 데이터를 구성

2024-08-30 04:42 UTC, justinyoo requested changes
주석으로 `// given` `// when` `// then` 한 부분들은 다른 테스트들과 동일하게 `// Arrange` `// Act` `// Assert`로 바꿔주세요.

2024-08-30 04:42 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/DeploymentModelListComponent.razor
> +    public Option<string>? selectedOption { get; set; } = new();
이 `selectedOption` 속성은 이 컴포넌트 외부로 공개하는 스코프인가요? 그렇다면 `SelectedOption`으로 써 주시고, 아니라면 `public` 대신 `private`으로 바꿔주세요.

2024-08-30 04:42 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/UI/DeploymentModelListComponentTests.cs
> +            // given
요건 `// Act`가 됩니다.

2024-08-30 04:42 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/UI/DeploymentModelListComponentTests.cs
> +            await Expect(label).ToBeVisibleAsync();
요게 `// Assert`가 되겠죠?

2024-08-30 04:42 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/UI/DeploymentModelListComponentTests.cs
> +            // given
마찬가지로 이게 `// Act`, 즉 실제로 무언가 행위를 하는 것

2024-08-30 04:42 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/UI/DeploymentModelListComponentTests.cs
> +            // when & then
여긴 확인하는 부분이므로 `// Assert`

2024-08-30 04:42 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/UI/DeploymentModelListComponentTests.cs
> +            await fluentOptions.Nth(2).ClickAsync(); // 옵션 클릭
여기서 `expectedValue`와 `Nth(2)` 같은 부분은 파라미터라이징으로 여러 값을 동시에 테스트해 볼 수 있습니다.

https://docs.nunit.org/articles/nunit/writing-tests/attributes/testcase.html

이 문서 확인해 보세요.

2024-08-30 04:42 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/UI/DeploymentModelListComponentTests.cs
> +            Assert.That(actualValue, Is.EqualTo(expectedValue));
FluentAssertions 써서 해 보세요. `actualValue.Should().Be(expectedValue)` 같은 식이 될 거예요.

2024-08-31 08:12 UTC, justinyoo requested changes
거의 다 왔습니다! 몇가지만 클린업 정도로 수정해 보시지요.

2024-08-31 08:12 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/Tests.razor
> +@using AzureOpenAIProxy.PlaygroundApp.Components.UI
이 `@using ...` 디렉티브는 생략해도 됩니다.

2024-08-31 08:12 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/Tests.razor
> +<DeploymentModelListComponent OnUserOptionSelected="HandleSelectedValue" />
여기에 `@rendermode="InteractiveServer"` 추가해 주세요.

2024-08-31 08:12 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/Tests.razor
> +    }
별다른 로직 없이 이것만 있으면 굳이 이 메소드를 오버라이딩하지 않아도 됩니다. 빼도 될 듯?

2024-08-31 08:12 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/DeploymentModelListComponent.razor
> +@using Microsoft.FluentUI.AspNetCore.Components
라인 2의 `@using ...` 디렉티브는 중복이라 없어도 됩니다

2024-09-01 02:14 UTC, justinyoo requested changes
PR 도중에 갑자기 리베이스를 했는지 포스 푸시가 들어와서 당황했는데, 야튼 몇가지 리뷰 코멘트 남겨뒀습니다.

2024-09-01 02:14 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/Tests.razor
> +<p style="margin-top: 10px">Selected Value: @selectedModelValue</p>
이것 대신 `DebugButtonComponent`로 처리하면 어떨까요? 그러라고 만들어둔 버튼이니까.

2024-09-01 02:14 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/Tests.razor
> +    private string? selectedModelValue = "";
큰 건 아니지만, 컴포넌트 순서에 따라 이 변수도 `currentValue` 밑으로 내리는 게 나을 듯?

2024-09-01 02:14 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/Tests.razor
>      private void SetInput(int newValue)
고치는 김에 이 메소드도 `private async Task SetInput(...)`으로 바꿀까요? 메소드 마지막에 `await Task.CompletedTask;` 넣고.

2024-09-01 02:14 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/Tests.razor
> +    private void HandleSelectedValue(string val)
이 메소드를 `private async Task HandleSelectedValue(...)`으로 바꿀까요? 메소드 마지막에 `await Task.CompletedTask;` 넣고.

2024-09-01 02:14 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/DeploymentModelListComponent.razor
> +@using AzureOpenAIProxy.PlaygroundApp.Clients
이 `@using ...` 디렉티브는 지금 필요 없습니다.

2024-09-01 03:52 UTC, yjchun626 commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/Tests.razor
> +<p style="margin-top: 10px">Selected Value: @selectedModelValue</p>
넵 아래 `HandleSelectedValue` 메소드 (지금은 `HandleSelectedModelValue`로 메소드명 변경) 수정해서 다음과 같이 뜨도록 만들어봤습니다!
<img width="701" alt="image" src="https://github.com/user-attachments/assets/8de90655-0643-48b7-bd12-5abefd912ea3">

2024-09-01 05:00 UTC, justinyoo requested changes

2024-09-01 07:58 UTC, yjchun626 commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/Tests.razor
> +<DeploymentModelListComponent OnUserOptionSelected="HandleSelectedModelValue" @rendermode="InteractiveServer" />
아하 찾아보니 그러면 `deployment-model-list-component` 이런식으로 작성하는게 맞죠? 
케밥케이싱이라는 명칭이 따로 있는줄은 처음 알았습니다...🤣 귀엽네요...

2024-09-01 08:03 UTC, yjchun626 commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/Tests.razor
>  <DebugTargetComponent OnValueChanged="SetInput" />
근데 혹시 몰라서 여쭙는데, id 값 추가할때 단순히 컴포넌트 명을 케밥케이싱으로 해서 추가하면 되나요? 
(여기서는 `debug-target-component`로 작성하려고 했습니다.)

2024-09-01 08:55 UTC, yjchun626 commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/Tests.razor
>  <DebugTargetComponent OnValueChanged="SetInput" />
아 근데 저는 컴포넌트 안에 `id="{id 명}"` 이렇게 추가하면 되는줄 알았는데 InvalidOperationException이 뜨네요. 
컴포넌트 파일에 들어가서 뭔가 해줘야하는 것인가요? 아니면 쓰는 방식이 다른 것일까요... 이 부분은 더 찾아보겠습니다.

2024-09-01 10:07 UTC, yjchun626 commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/Tests.razor
>  <DebugTargetComponent OnValueChanged="SetInput" />
그런데 컴포넌트 안에 `id="{id 명}"` 같은 방식으로 작성하면 되는 줄 알았는데 보니까 InvalidOperationException이 뜨네요. 혹시 blazor 컴포넌트 안에 따로 id를 지정해주는 다른 방식이 있을까요? 
아니면 컴포넌트에 id 값을 추가해달라고 하셨던 것이, 각 컴포넌트 페이지에 가서 따로 파라미터를 생성해서 그곳에 id 값을 지정할 수 있게 하라는 말씀이셨을까요?

2024-09-01 14:54 UTC, justinyoo requested changes
리뷰 코멘트 남겨뒀습니다.

2024-09-01 14:54 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/Tests.razor
>  <DebugTargetComponent OnValueChanged="SetInput" />
이 컴포넌트 수정이 필요하겠네요. 제가 해 보겠습니다.

2024-09-01 14:54 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/Tests.razor
>  <DebugButtonComponent Input="@currentValue" />
이것도 ID 속성을 따로 줘야 하는 듯. 제가 확인해 볼께요.

2024-09-01 14:54 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/DeploymentModelListComponent.razor
> +<FluentLayout Style="margin: 10px;">
여기에 `Id` 속성을 지정할 수 있으니, 이걸 `Id="@Id"` 같은 식으로 하고 파라미터로 외부로 노출시키면 될 듯 합니다.

2024-09-01 14:54 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/DeploymentModelListComponent.razor
> +
여기에

```csharp
[Parameter]
public string? Id { get; set; }
```

같은 식으로 추가하면 될 듯?

이렇게 추가하면 관련해서 테스트 케이스도 추가해야 합니다.

2024-09-01 15:47 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/DeploymentModelListComponent.razor
> +<FluentLayout Style="margin: 10px;">
`DebugTargetComponent`와 `DebugButtonComponent`는 수정해 뒀습니다. 리포지토리 최신화 한 후에 유정님 컴포넌트에 적용시켜 보세요.

2024-09-02 04:34 UTC, yjchun626 commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/DeploymentModelListComponent.razor
> +
넵 id 관련해서 `DeploymentModelListComponentTests.cs`에 테스트 코드를 추가했는데, `Tests.razor`의 다른 컴포넌트도 테스트가 필요해보여서 일단 `TestsPageTests.cs`에도 테스트 코드를 추가했습니다! 

```
[Test]
    [TestCase("debug-target")]
    [TestCase("debug-button")]
    [TestCase("deployment-model-list")]
    [TestCase("debug-button-selected-model")]
    public async Task Given_ComponentID_When_Page_Loaded_Then_Component_Should_Be_Visible(string id)
    {
        // Arrange
        var expectedId = id;

        // Act
        var component = Page.Locator($"#{expectedId}");

        // Assert
        await Expect(component).ToBeVisibleAsync();
    }
```

2024-09-02 04:36 UTC, yjchun626 commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/DeploymentModelListComponent.razor
> +
`DeploymentModelListComponentTests.cs`에도 다음과 같은 코드를 추가했었는데, 위에 추가한 테스트 코드와 중복되는 것 같아 일단은 지운 상태입니다. 

```
[Test]
        public async Task Given_DropdownComponentID_When_Page_Loaded_Then_DropdownComponent_Should_Be_Visible()
        {
            // Arrange
            var expectedId = "deployment-model-list";

            // Act
            var component = Page.Locator($"#{expectedId}");

            // Assert
            await Expect(component).ToBeVisibleAsync();
        }
```

2024-09-06 04:23 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/Tests.razor
>  <DebugTargetComponent OnValueChanged="SetInput" />
`DebugTargetComponent` 수정했습니다

2024-09-06 04:26 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/DeploymentModelListComponent.razor
> +
우선은 둘 다 넣어 보시겠어요? 나중에 덜어내도 되니까요.

2024-09-06 04:28 UTC, justinyoo commented
@yjchun626 추가 코멘트를 달아뒀습니다. 거의 다 온 것 같아요!

2024-09-06 05:11 UTC, yjchun626 commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/DeploymentModelListComponent.razor
> +
넵 전에 커밋했을때 둘 다 넣어서 커밋했습니다!

2024-09-06 05:20 UTC, justinyoo approved these changes
고생하셨습니다! LGTM!

2024-09-06 05:20 UTC, merged