Feature/212 add endpoint for create event details
aliencube/azure-openai-sdk-proxy pull request #261
Opened 2024-08-23 16:57 UTC by DOZAKA

Related to https://github.com/aliencube/azure-openai-sdk-proxy/issues/212

This PR is:

To add endpoint for create event details

[작업 내역]
- [AzureOpenAIIProxy.ApiApp] Endpoints.AdminEndpointUrls 내 AdminEvent url(/admin/events) 추가
- [AzureOpenAIIProxy.ApiApp] Endpoints.AdminEventEndpoints 내 CreateAdminEvent 메소드 작성
- [AzureOpenAIIProxy.ApiApp] 관리자 이벤트 상세 조회 API 이슈에서 생성한 AdminEventDetails 모델을 기반으로 관리자 이벤트 등록용 모델(Models.AdminEvent) 생성
- [AzureOpenAIIProxy.ApiApp] Program.cs 내 app.CreateAdminEvent() 등록
- [OpenAPI] Add endpoint for view event details #207 관련 머지(https://github.com/aliencube/azure-openai-sdk-proxy/pull/231) 내 기능과 불일치한 메소드 명 변경(AddAdminEvents -> GetAdminEventDetails)

OpenAPI: [swagger.json](https://github.com/user-attachments/files/16731662/swagger.json)

<img width="943" alt="swagger_image" src="https://github.com/user-attachments/assets/597ac587-e679-4837-bd24-161a1470b22d">

2024-08-24 01:49 UTC, justinyoo requested changes
코멘트 남겨뒀습니다.

2024-08-24 01:49 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEndpointUrls.cs
> -    /// Declares the admin event details endpoint.
요 주석은 이벤트 디테일 엔드포인트에 대한 것이니 살려주세요.

2024-08-24 01:49 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEndpointUrls.cs
> +    /// Declares the admin events endpoint.
그리고 이건 새 이벤트 리스트 혹은 생성과 관련한 엔드포인트이니 이건 별도로 추가해 주세요.

2024-08-24 01:49 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEndpointUrls.cs
> +    public const string AdminEvent = "/admin/events";
`AdminEvents`와 같이 복수형으로 가는 것이 좋을 듯?

2024-08-24 01:49 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEventEndpoints.cs
> +            [FromBody] AdminEvent payload,
혹시 `AdminEventDetails` 클래스 대신 따로 `AdminEvent` 클래스를 만든 이유가 있나요?

2024-08-24 01:49 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEventEndpoints.cs
> +            });
요건 필요 없습니다.

2024-08-24 01:49 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEventEndpoints.cs
> +            return Results.Ok();
이걸 `return await Task.FromResult(Results.Ok());` 하는게 여기서는 가장 깔끔합니다.

2024-08-24 02:11 UTC, DOZAKA commented on src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEndpointUrls.cs
> -    /// Declares the admin event details endpoint.
확인 및 적용 완료

2024-08-24 02:11 UTC, DOZAKA commented on src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEndpointUrls.cs
> +    /// Declares the admin events endpoint.
확인 및 적용 완료

2024-08-24 02:11 UTC, DOZAKA commented on src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEndpointUrls.cs
> +    public const string AdminEvent = "/admin/events";
확인 및 적용 완료

2024-08-24 02:12 UTC, DOZAKA commented on src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEventEndpoints.cs
> +            [FromBody] AdminEvent payload,
AdminEventDetails를 재사용하면 openapi 내 아직 정의되지 않은  EventId 가 노출이 되기도 하고 EventId Requied 값이라서 따로 뺐습니다.

2024-08-24 02:18 UTC, DOZAKA commented on src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEventEndpoints.cs
> +            });
확인 및 적용 완료

2024-08-24 02:18 UTC, DOZAKA commented on src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEventEndpoints.cs
> +            return Results.Ok();
확인 및 적용 완료

2024-08-24 02:30 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEventEndpoints.cs
> +            [FromBody] AdminEvent payload,
디스코드 챗으로 얘기했다시피 너무 복잡하게 갈 필요는 없을 듯 싶구요, 어차피 EventId 값이 GUID 형태라면 중복 ID가 만들어질 가능성이 아주아주아주 낮습니다.

2024-08-24 02:37 UTC, DOZAKA commented on src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEventEndpoints.cs
> +            [FromBody] AdminEvent payload,
- EventId required 제거
- EventId 타입 변경 (string -> GUID)

2024-08-24 02:44 UTC, DOZAKA commented
[작업 내역]
- AdminEvent 모델 제거 (AdminEventDetails 모델 재사용)
- EventId required 제거
- EventId 타입 변경 (string -> GUID)

OpenAPI: [swagger.json](https://github.com/user-attachments/files/16734966/swagger.json)

<img width="991" alt="스크린샷 2024-08-24 오전 11 30 48" src="https://github.com/user-attachments/assets/de5ea958-0f2d-4a54-ae4d-4b57e3b7d28f">

2024-08-24 03:49 UTC, justinyoo requested changes
쟈... 이제 얼추 다 됐구요, 테스트 코드를 작성해 주세요!

2024-08-28 02:17 UTC, justinyoo requested changes
두어가지만 수정하면 될 듯 합니다!

2024-08-28 02:17 UTC, justinyoo commented on test/AzureOpenAIProxy.AppHost.Tests/ApiApp/Endpoints/AdminCreateEventsOpenApiTests.cs
> +    }
우리가 비지니스 로직을 작성한 적이 없기 때문에, 이 테스트는 불필요해 보입니다.

2024-08-28 02:17 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEventEndpoints.cs
> +        .Produces(statusCode: StatusCodes.Status404NotFound)
이벤트 생성하는 엔드포인트에서는 404 에러가 필요 없습니다. 대신 400 에러를 추가해 주세요.

2024-08-28 09:46 UTC, justinyoo approved these changes
LGTM! 수고하셨습니다!

2024-08-28 09:46 UTC, merged