[Admin] Component: List event details - UI component #219
aliencube/azure-openai-sdk-proxy pull request #266
Opened 2024-08-24 06:01 UTC by praivesi

## 개요
https://github.com/aliencube/azure-openai-sdk-proxy/issues/219

목표: Playground App 내에 Admin 계정으로 로그인 시 'Events' 탭에서 Event 목록을 표출

## 구현 화면
<img width="1717" alt="스크린샷 2024-08-24 오후 2 43 49" src="https://github.com/user-attachments/assets/a9dd957b-da26-4647-94f1-56cf64faf626">

## 구현 내용
**1. Events Page 구현**
1) 페이지 기본 정보를 출력
2) ListEventDetailsComponent 컴포넌트를 이용해 이벤트 목록 표시

**2. ListEventDetailsComponent 구현**
1) eventDetails 객체를 생성하여 AzureOpenAIProxy.ApiApp.Models.AdminEventDetails 목록 관리
2) eventDetails 객체에 있는 정보를 "evt-detail-tbl" 테이블로 표시
3) ListEventDetailsHeaderComponent 컴포넌트를 이용해 테이블의 Header 표시
4) EventDetailsElemComponent 컴포넌트를 이용해 AdminEventDetails 객체의 각 필드값을 테이블에 표시
5) EventDetailsElemActiveComponent 컴포넌트를 이용해 AdminEventDetails 객체의 IsActive 필드값을 테이블에 표시

**3. ListEventDetailsHeaderComponent 구현**
1) AdminEventDetails 테이블의 각 필드별 헤더 표시

**4. EventDetailsElemComponent 구현**
1) AdminEventDetails 테이블의 각 필드값 표시

**6. EventDetailsElemActiveComponent 구현**
1) AdminEventDetails 객체의 IsActive 값이 true 이면 초록, false이면 빨강으로 표시

**7. 테스트 추가**
1) EventsPageTests를 추가하여 웹 페이지의 /events 경로로 접속 시 반드시 있어야 하는 요소가 있는지 확인
- 이벤트 목록 컴포넌트 ("#evt-detail-comp")
- 이벤트 테이블 ("table.evt-detail-tbl")
- 이벤트 테이블 헤더 ("div.evt-detail-header")

## 잘 모르겠는 점
Test에서 테이블 존재 유무를 검증할 때 Task.Delay()를 선언하지 않으면 간헐적으로 Test 실패가 발생합니다.

Backend 데이터를 수신하는 행위를 시뮬레이션하고자
ListEventDetailsComponent의 OnInitializeAsync() 에서 Task.Delay()를 선언한 것이 원인으로 추측됩니다.

실제 데이터를 받더라도 어느정도 Delay가 발생할 것으로 생각되어 Test 코드에서 Task.Delay()를 주어 통과되도록 선언하였습니다.
하지만 추후 데이터 수신 시간이 길어져서 Test의 Delay 시간을 넘어가면 테스트가 다시 실패할 것으로 예상됩니다.

상황에 따라 유동적으로 변하는 Delay 시간에 대응하여 Test 코드에서 대처할 방법이 있을지 궁금합니다..!

2024-08-24 06:18 UTC, justinyoo requested changes

2024-08-24 06:18 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Layout/NavMenu.razor
이 사이드바는 별도의 이슈 #238 에서 따로 작업을 할 예정이니 여기서는 빼도 됩니다.

2024-08-24 06:18 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/Events.razor
> +@attribute [StreamRendering]
이 어트리뷰트를 빼야 할 거예요.

2024-08-24 06:18 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/ListEventDetailsComponent.razor
> +            <tbody>
혹시 DataGrid 컴포넌트를 고려해 보면 어때요?

https://www.fluentui-blazor.net/DataGrid

2024-08-24 06:18 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/ListEventDetailsComponent.razor
> +    }
새로 클래스를 선언하기 보다는 기존에 있는 걸 재활용하면 안되나요? 아직 머지가 안됐나...? 🤔

2024-08-24 06:18 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/EventsPageTests.cs
> +        await Task.Delay(200);
이게 0.2초 딜레이인데... 그냥 넉넉하게 한 2초 줘 보면 어때요?

2024-08-24 06:18 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/EventsPageTests.cs
파일 이름을 `AdminEventsPageTests`로 바꿔야 사용자 이벤트 리스트 페이지와 혼동을 줄일 수 있을 겁니다.

2024-08-26 16:57 UTC, praivesi commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Layout/NavMenu.razor
네 해당 파일 변경 내역은 제외했습니다.

2024-08-26 16:57 UTC, praivesi commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/Events.razor
> +@attribute [StreamRendering]
제외했습니다.

2024-08-26 16:58 UTC, praivesi commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/ListEventDetailsComponent.razor
> +            <tbody>
위 테이블을 제거하고 FluentDataGrid를 활용하여 테이블을 만들도록 수정하였습니다.

2024-08-26 17:00 UTC, praivesi commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/ListEventDetailsComponent.razor
> +    }
ApiApp에 기존에 선언된 구조체가 있어서 재활용하도록 변경하였습니다.
이 과정에서 ApiApp 프로젝트를 PlaygroundApp 프로젝트가 참조하도록 변경하였습니다.

2024-08-26 17:01 UTC, praivesi commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/EventsPageTests.cs
해당 파일명은 EventPageTests -> AdminEventsPageTests로 변경되었습니다.

2024-08-26 17:01 UTC, praivesi commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/EventsPageTests.cs
> +        await Task.Delay(200);
네 2초로 변경하였습니다.

2024-08-27 02:25 UTC, justinyoo requested changes
코멘트 확인해 주세요!

2024-08-27 02:25 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/AzureOpenAIProxy.PlaygroundApp.csproj
> +    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.DataGrid.EntityFrameworkAdapter" Version="4.9.3" />
혹시 이 패키지 없어도 되나요? 우리는 엔티티프레임워크를 사용하지 않을 것 같은데 그럼에도 불구하고 필요한가요?

2024-08-27 02:25 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/AzureOpenAIProxy.PlaygroundApp.csproj
> +    <ProjectReference Include="..\AzureOpenAIProxy.ApiApp\AzureOpenAIProxy.ApiApp.csproj" />
이게 ApiApp에 있던 모델 참조하기 위해서 가져온 거죠?

프론트와 백엔드는 서로 의존성이 없어야 하기 때문에, 만약 이런 상황이 된다면 프론트엔트 앱에 별도로 Models 디렉토리 만들고 동일한 모델을 복사해 오는 걸로 하시지요.

2024-08-27 02:25 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/AdminEventDetailElemActiveComponent.razor
이 파일 이름에서 `Elem`이 무엇을 의미하나요?

2024-08-27 02:25 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/AdminEventDetailElemActiveComponent.razor
혹시 `AdminEventIsActiveComponent` 라고 하면 의미를 전달하지 못하나요?

2024-08-27 02:25 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/AdminListEventDetailsComponent.razor
이 콤포넌트는 이벤트 디테일이라기 보다는 이벤트 리스트를 보여주는 거니 `AdminEventsComponent` 쯤으로 바꾸면 의미 전달이 될까요?

2024-08-27 02:25 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/AdminEventsPageTests.cs
> +        await this.Page.GotoAsync("https://localhost:5001/events");
`/admin/events`로 가야 할 듯?

2024-08-27 02:25 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/AdminEvents.razor
> +﻿@page "/events"
`/admin/events` 입니당~

2024-08-27 02:26 UTC, justinyoo commented
@praivesi 빌드 깨졌습니다~

2024-08-28 11:11 UTC, praivesi commented on src/AzureOpenAIProxy.PlaygroundApp/AzureOpenAIProxy.PlaygroundApp.csproj
> +    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.DataGrid.EntityFrameworkAdapter" Version="4.9.3" />
FluentDataGrid를 테스트해보다가 실수로 들어간 것 같아 제거했습니다.

2024-08-28 11:23 UTC, praivesi commented on src/AzureOpenAIProxy.PlaygroundApp/AzureOpenAIProxy.PlaygroundApp.csproj
> +    <ProjectReference Include="..\AzureOpenAIProxy.ApiApp\AzureOpenAIProxy.ApiApp.csproj" />
네, 참조가 새로 생기는 게 마음에 걸려 [이전 comment](https://github.com/aliencube/azure-openai-sdk-proxy/pull/266#discussion_r1731532109)에서 참조가 추가됨을 언급했었습니다.


말씀하신대로 ApiApp에 있는 `AdminEventDetails` 모델을 
`AzureOpenAIProxy.PlaygroundApp/Models/AdminEventDetails.cs` 파일로 복사하여 사용하도록 변경했습니다.

2024-08-28 11:24 UTC, praivesi commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/AdminEventDetailElemActiveComponent.razor
list에 있는 하나의 원소(Element)를 나타내고자 사용하였는데 
`AdminEvent` 라고만 해도 의미가 충분할 것 같아 `AdminEventIsActiveComponent` 로 이름을 변경하였습니다.

2024-08-28 11:26 UTC, praivesi commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/AdminEventDetailElemActiveComponent.razor
`AdminEventIsActiveComponent` 으로 의미가 충분한다고 판단되어 이름을 변경했습니다.

2024-08-28 11:27 UTC, praivesi commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/AdminListEventDetailsComponent.razor
네 AdminEvent 의 list임을 충분히 표현되어 `AdminEventsComponent` 로 이름을 변경하였습니다.

2024-08-28 11:27 UTC, praivesi commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/AdminEvents.razor
> +﻿@page "/events"
변경하였습니다

2024-08-28 11:28 UTC, praivesi commented
> @praivesi 빌드 깨졌습니다~

24.08.28 기준으로 rebase 하여 다시 PUSH 했습니다!

2024-08-30 04:53 UTC, justinyoo requested changes
몇가지 네이밍 컨벤션이랑 scoped CSS 쓰는 쪽으로 바꿔보시지요.

2024-08-30 04:53 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/AdminEventsPageTests.cs
> +        Assert.That(listEvtDetailsComp, Is.Not.Null);
Fluent 문법을 사용해 주세요. 그러면 `listEvtDetailComp.Should().NotBeNull()` 같은 식이 될 겁니다.

2024-08-30 04:53 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/AdminEventsPageTests.cs
> +        Assert.That(evtDetailTbl, Is.Not.Null);
여기도 마찬가지

2024-08-30 04:53 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/AdminEventsPageTests.cs
> +        var evtDetailTbl = await Page.QuerySelectorAsync("#evt-detail-tbl");
아, 그리고 변수명에 굳이 줄임말을 쓸 필요는 없어요. 그냥 `eventDetailsTable` 같은 식으로 적는 것이 낫습니다.

2024-08-30 04:53 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/AdminEventsComponent.razor
> +<div id="evt-detail-comp">
`evt` 대신 `event`가 낫습니다. `comp`는 무엇을 의미하는 건가요?

2024-08-30 04:53 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/AdminEventIsActiveComponent.razor
> +    .evt-detail-active {
`evt-detail-active` 대신 `event-details-active` 같은 식으로 줄임말을 안 쓰는 것이 좋겠습니다.

2024-08-30 04:53 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/AdminEventIsActiveComponent.razor
> +</style>
가능하다면 Scoped CSS 를 위해 별도의 `AdminEventIsActiveComponent.razor.css` 파일로 빼는 것이 낫겠습니다.

2024-08-30 04:53 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/AdminEventsComponent.razor
> +</style>
이것도 가능하다면 `AdminEventsComponent.razor.css` 파일로 빼는 것이 낫겠습니다.

2024-08-31 01:53 UTC, praivesi commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/AdminEventsComponent.razor
> +</style>
넵 분리하였습니다.

2024-08-31 01:53 UTC, praivesi commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/AdminEventIsActiveComponent.razor
> +</style>
넵 분리하였습니다.

2024-08-31 01:55 UTC, praivesi commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/AdminEventIsActiveComponent.razor
> +    .evt-detail-active {
소스코드의 다른 부분에서 `eventDetails` 라는 용어를 모두 `adminEvents`로 변경하였기 때문에
`evt-detail-active` 도 `admin-event-active-state` 로 변경하였습니다.

2024-08-31 01:56 UTC, praivesi commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/AdminEventsComponent.razor
> +<div id="evt-detail-comp">
`evt-detail-comp` 를 `admin-events-component` 로 변경하였습니다.
`comp`는 `component`의 약자로 사용했었습니다.

2024-08-31 01:57 UTC, praivesi commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/AdminEventsPageTests.cs
> +        var evtDetailTbl = await Page.QuerySelectorAsync("#evt-detail-tbl");
`evtDetailTbl`은 `adminEventsTable`로, `evt-detail-tbl`은 `admin-events-table`로 변경하였습니다.

2024-08-31 01:57 UTC, praivesi commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/AdminEventsPageTests.cs
> +        Assert.That(evtDetailTbl, Is.Not.Null);
`adminEventsTable.Should().NotBeNull()` 로 변경하였습니다.

2024-08-31 01:59 UTC, praivesi commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/AdminEventsPageTests.cs
> +        Assert.That(listEvtDetailsComp, Is.Not.Null);
`adminEventsComponent.Should().NotBeNull()` 로 변경하였습니다.
(`listEvtDetailsComp`는 `adminEventsComponent` 로 변경되었습니다.)

2024-08-31 08:15 UTC, justinyoo requested changes
몇가지 간단한 하우스키핑 정도만 해 보시지요.

2024-08-31 08:15 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/AdminEvents.razor
> +@using AzureOpenAIProxy.PlaygroundApp.Components.UI.Admin
이 `@using ...` 디렉티브를 `_Imports.razor` 쪽으로 옮겨보시지요?

2024-08-31 08:15 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/AdminEventsComponent.razor
> +@using AzureOpenAIProxy.PlaygroundApp.Components.UI.Admin
그러면 이거 필요 없음

2024-08-31 08:15 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/AdminEventsComponent.razor
> +    PaginationState pagination = new PaginationState { ItemsPerPage = 10 };
크게 중요한 건 아닌데 둘 다 `private` 스코프를 주면 좋겠습니다.

2024-09-01 10:08 UTC, praivesi commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/AdminEvents.razor
> +@using AzureOpenAIProxy.PlaygroundApp.Components.UI.Admin
네 _Imports.razor 로 이동하였습니다.

2024-09-01 10:08 UTC, praivesi commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/AdminEventsComponent.razor
> +@using AzureOpenAIProxy.PlaygroundApp.Components.UI.Admin
_Import.razor로 옮겨져서 해당 라인은 삭제했습니다.

2024-09-01 10:08 UTC, praivesi commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/AdminEventsComponent.razor
> +    PaginationState pagination = new PaginationState { ItemsPerPage = 10 };
네 private 으로 스코프 추가 했습니다

2024-09-01 10:10 UTC, praivesi commented
> 몇가지 간단한 하우스키핑 정도만 해 보시지요.

@using 과 private scope 정리하였습니다!

2024-09-01 14:43 UTC, justinyoo requested changes

2024-09-01 14:43 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Models/AdminEventDetails.cs
이 클래스 구조가 이제 더이상 유효하지 않습니다. 최신화 해 주세요.

2024-09-01 14:45 UTC, justinyoo commented
빌드 깨집니다! 리포지토리 최신화 해 보신 후에 다시 해 보세요.

2024-09-02 14:21 UTC, praivesi commented
> 빌드 깨집니다! 리포지토리 최신화 해 보신 후에 다시 해 보세요.

24.09.02 기준으로 최신화 하였습니다!

2024-09-03 08:34 UTC, justinyoo requested changes
딱 두 가지만 더 수정하면 될 듯 합니다!

2024-09-03 08:34 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Models/AdminEventDetails.cs
모양이 다릅니다.

- https://github.com/aliencube/azure-openai-sdk-proxy/blob/main/src/AzureOpenAIProxy.ApiApp/Models/EventDetails.cs
- https://github.com/aliencube/azure-openai-sdk-proxy/blob/main/src/AzureOpenAIProxy.ApiApp/Models/AdminEventDetails.cs

두 파일을 참고로 작성해 주세요.

2024-09-03 08:34 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/AdminEventsPageTests.cs
> +        await this.Page.GotoAsync("https://localhost:5001/admin/events");
요 부분을 아예 Setup 메소드로 빼 볼까요?

https://github.com/aliencube/azure-openai-sdk-proxy/blob/c0aa2643ac2e1e7344d51b18a7aff983d6db4ccd/test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/PlaygroundPageTests.cs#L15-L20

여길 참고하세요.

2024-09-04 05:41 UTC, praivesi commented on src/AzureOpenAIProxy.PlaygroundApp/Models/AdminEventDetails.cs
네 ApiApp의 구조에 따라 AdminEventDetails를 변경하고 EventDetails를 추가하였습니다.

2024-09-04 05:43 UTC, praivesi commented
> 딱 두 가지만 더 수정하면 될 듯 합니다!

두 가지 모두 수정 완료하였습니다.
더 필요한 부분 있으시면 말씀해주세요 !

2024-09-06 04:20 UTC, justinyoo approved these changes
고생하셨습니다! LGTM!

2024-09-06 04:20 UTC, merged