[Backend API]Refactor OpenAPI doc version to appsettings.json
aliencube/azure-openai-sdk-proxy pull request #274
Opened 2024-08-28 09:21 UTC by sikutisa

Resolves #267 

## Description
* appsettings.json의 OpenApi 설정에 대응되는 엔티티인 OpenApiSettings 클래스 추가
* OpenApiSettings 클래스의 extnsions인 OpenApiSettingsExtensions 클래스 추가
  * IConfiguration을 통해 Open API 설정을 가져오는 메서드인 GetOpenApiSettings 메소드 포함
* ApplicationBuilderExtensions 리팩토링
*  ServiceCollectionExtensions 리팩토링
  * GetOpenApiSettings 메소드를 통해 DocVersion 값을 가져옴
* Constants.cs 변경에 따른 github workflow 수정

## Discussion Points
* appsettings.json 에서 DocVersion 변수명
  * 저는 Constants.cs의 Version 변수가 ApiApp 프로젝트의 버전이라고 이해했습니다. 그리고 swagger.json은 현재 ApiApp의 open api에 대한 명세이기에, ApiApp의 버전을 그대로 가져온다고 생각했습니다.
  * 즉, ApiApp에 대한 버전값이 존재하고, open api doc의 버전값은 이를 그대로 가져와서 사용할 뿐 독립적으로 존재하지 않는다고 생각했습니다. 
  * 39d8c9f77c5c8f1a528d28b40ab249cee4b33c10 에서 Constants.cs의 Version 변수에 대응되는 변수로 DocVersion 이라는 변수가 추가됐습니다. 저는 해당 변수명이 DocVersion이 아니라 Constants.cs 에서처럼 Version이나 아니면 ApiVersion과 같은 이름이 더 적합하다고 생각했었는데, 해당 변수명을 DocVersion으로 정하신 이유가 궁금합니다.

2024-08-28 09:59 UTC, justinyoo requested changes
빌더 패턴 까지는 필요 없고, 바로 `AddOpenApiService` 메소드에 직접 `IConfiguration` 인스턴스 받아서 해도 됩니다. 아직까지 이걸 싱글톤 인스턴스로 할 단계는 아닌 듯 싶네욥.

2024-08-28 09:59 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Extensions/ServiceCollectionExtensions.cs
> +            return settings;
빌더패턴 쓰는 건 투머치구요, 요거 확인해 보세요. 요정도로만 해도 충분합니다.

https://github.com/aliencube/azure-openai-sdk-proxy/blob/81c8c6e4a0f736d99c6162ef1baeb41c558609e5/src/AzureOpenAIProxy.ApiApp/Extensions/ServiceCollectionExtensions.cs#L27-L31

2024-08-28 10:27 UTC, sikutisa commented on src/AzureOpenAIProxy.ApiApp/Extensions/ServiceCollectionExtensions.cs
> +            return settings;
넵. 그럼 빌더 패턴 걷어내겠습니다.

2024-08-28 12:33 UTC, sikutisa commented on src/AzureOpenAIProxy.ApiApp/Extensions/ServiceCollectionExtensions.cs
> +            return settings;
* 현재 DocVersion 값이 필요한 곳이 ApplicationBuilderExtensions의 UseSwaggerUI 메서드와 ServiceCollectionExtensions의 AddOpenApiService 메서드 두 곳인데, 각각에서 IConfiguration 인스턴스로 settings를 가져오는 것은 코드 중복이 있다고 생각해서 OpenApiSettingsExtensions로 분리했습니다.
* ApplicationBuilderExtensions에서는 IServiceProvider를 활용하는 코드를 쓰는 것이, ServiceCollectionExtensions에서는 IServiceCollection를 활용하는 코드를 쓰는 것이 구현이 용이해서, OpenApiSettingsExtensions에서 메서드 오버로딩을 활용해서 구현했습니다.
* 빌드가 계속 실패하고 있는데, 이 부분은 확인 중 입니다.

2024-08-30 03:37 UTC, justinyoo requested changes
좋습니다! 작성하신 확장메소드를 검증하는 테스트 모드만 작성하면 될 듯 해요.

2024-08-30 03:37 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Extensions/OpenApiSettingsExtensions.cs
> +        return GetOpenApiSettings(serviceProvider);
여기서는 `return serviceProvider.GetOpenApiSettings();` 하는 것이 좀 더 간결하지 않을까요?

2024-08-30 03:37 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Extensions/OpenApiSettingsExtensions.cs
> +    }
좋은데요? 여기에 해당하는 테스트 코드만 작성하면 될 듯?

2024-08-30 03:43 UTC, sikutisa commented on src/AzureOpenAIProxy.ApiApp/Extensions/OpenApiSettingsExtensions.cs
> +        return GetOpenApiSettings(serviceProvider);
저도 고민하던 부분이긴 했는데... 🤣 바로 return 하도록 바꾸는 게 좋을 것 같습니다.

2024-08-30 03:54 UTC, sikutisa commented on src/AzureOpenAIProxy.ApiApp/Extensions/OpenApiSettingsExtensions.cs
> +        return GetOpenApiSettings(serviceProvider);
근데 GetOpenApiSettings 메소드에 serviceProvider가 파라미터로 넘어가야 해서 말씀하신 코드처럼은 안 되고 `return GetOpenApiSettings(services.BuildServiceProvider());` 이렇게 됩니다.

2024-08-30 04:21 UTC, justinyoo commented
랜덤하게 실패하는 테스트들을 수정해서 올려뒀으니, 브랜치 최신화한 후 작업해 보세요.

2024-08-31 06:47 UTC, justinyoo requested changes
몇가지 테스트 케이스 수정을 좀 해 보면 어떨까요?

2024-08-31 06:47 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Extensions/ApplicationBuilderExtensions.cs
> +﻿using AzureOpenAIProxy.ApiApp.Configurations;
이 `using ...` 디렉티브가 필요하던가요?

2024-08-31 06:47 UTC, justinyoo commented on test/AzureOpenAIProxy.ApiApp.Tests/Extensions/OpenApiSettingsExtensionsTests.cs
> +using Castle.Components.DictionaryAdapter;
이 라인이 필요한가요?

2024-08-31 06:47 UTC, justinyoo commented on test/AzureOpenAIProxy.ApiApp.Tests/Extensions/OpenApiSettingsExtensionsTests.cs
> +
```csharp
var dict = new Dictionary<string, string>()
{
    { "OpenApi", "" }
}
````

이 경우의 테스트도 추가해야 할 듯 합니다.

2024-08-31 06:51 UTC, sikutisa commented on src/AzureOpenAIProxy.ApiApp/Extensions/ApplicationBuilderExtensions.cs
> +﻿using AzureOpenAIProxy.ApiApp.Configurations;
사용하지 않고 있네요. 해당 using은 제거하겠습니다.

2024-08-31 06:52 UTC, sikutisa commented on test/AzureOpenAIProxy.ApiApp.Tests/Extensions/OpenApiSettingsExtensionsTests.cs
> +using Castle.Components.DictionaryAdapter;
3번 라인 말씀하시는 건가요?

2024-08-31 07:02 UTC, sikutisa commented on test/AzureOpenAIProxy.ApiApp.Tests/Extensions/OpenApiSettingsExtensionsTests.cs
> +using Castle.Components.DictionaryAdapter;
DictionaryAdapter도 사용하지 않는 것으로 확인돼서 제거하겠습니다.

2024-08-31 08:18 UTC, justinyoo requested changes
하나 깜빡하고 지나간 것 있는데, 그거 하나만 수정하면 될 듯 합니다.

2024-08-31 08:18 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Extensions/OpenApiSettingsExtensions.cs
> +        return GetOpenApiSettings(serviceProvider);
@sikutisa 이것 마지막으로 한 번 봐 주세요.

2024-08-31 08:24 UTC, sikutisa commented on src/AzureOpenAIProxy.ApiApp/Extensions/OpenApiSettingsExtensions.cs
> +        return GetOpenApiSettings(serviceProvider);
이걸 빼먹었군요;; 바로 반영하겠습니다.

2024-08-31 08:32 UTC, justinyoo reviewed
수고하셨습니다!

2024-08-31 08:32 UTC, merged