[Playground] #177 auth UI component
aliencube/azure-openai-sdk-proxy pull request #277
Opened 2024-08-28 14:39 UTC by pmj-chosim

- UI (Api key input&masking component)
- UI test(playwright) : * time out 에러 해결 中 

Error Message
System.TimeoutException : Timeout 30000ms exceeded. Call log: - waiting for Locator("input[name='ApiKey']") to be visible

2024-08-30 03:10 UTC, justinyoo requested changes
컴포넌트를 Blazor Fluent UI로 바꾸면 많은 부분을 수정하셔야 할 거예요.

2024-08-30 03:10 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/ApiKeyInputComponent.razor
> +<button @onclick="ToggleMask">@MaskState</button>
Blazor Fluent UI 컴포넌트로 만들어 보세요.

https://www.fluentui-blazor.net/TextField

이 컴포넌트는 버튼이 필요 없습니다. 오로지 텍스트 인풋 필드만 필요함.

2024-08-31 07:12 UTC, pmj-chosim commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/ApiKeyInputComponent.razor
> +<button @onclick="ToggleMask">@MaskState</button>
넵! 감사합니다. 마스킹 별도 구현이 fluent ui에서 제공하는 password 마스킹 기능 사용했습니다

2024-08-31 07:36 UTC, justinyoo commented
@pmj-chosim 컨플릭 해결해 주세요

2024-08-31 07:53 UTC, closed without merging