177 auth UI component
aliencube/azure-openai-sdk-proxy pull request #280
Opened 2024-08-31 08:01 UTC by pmj-chosim

2024-08-31 08:29 UTC, justinyoo requested changes
수정사항 코멘트 남겨뒀습니다.

2024-08-31 08:29 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/Home.razor
> +<ApiKeyInputComponent @rendermode="InteractiveServer" />
`Playground.razor` 페이지로 콤포넌트 옮겨주세요.

2024-08-31 08:29 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/ApiKeyInputComponent.razor
> +    private string ApiKeyValue { get; set; } = string.Empty;
- 이 필드 스코프가 `priavate` 이라면 `apiKeyValue` 형태의 camelCasing을 하셔야 합니다.
- `string?` 과 같이 nullable 형식으로 선언해 주세요. 그러면 굳이 `= string.Empty` 같이 초기화를 안해도 됩니다.

2024-08-31 08:29 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/ApiKeyInputComponent.razor
> +    public EventCallback<string> ApiKeyChanged { get; set; }
부모 컴포넌트에서 바라보는 이벤트 핸들러 이름이므로 `OnApiKeyInput` 정도가 적당합니다.

2024-08-31 08:29 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/ApiKeyInputComponent.razor
> +    private async Task OnApiKeyChanged(ChangeEventArgs e)
이벤트 핸들러 메소드명에는 굳이 `On`을 사용하지 않아도 됩니다. 실제 이 핸들러가 하려는 목적으로 메소드명에 녹여주세요. 예) `SetApiKey(ChangeEventArgs e)`

2024-08-31 08:29 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/DebugApiKeyButton.cs
`PlaygroundPageTests.cs` 테스트를 만들어야 할 거예요.

2024-08-31 08:29 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/DebugApiKeyButton.cs
> +            NUnit.Framework.Assert.AreEqual("password", inputType, "API 키 입력 필드는 기본적으로 마스킹되어 있어야 합니다.");
FluentAssertions 문법을 따라갑니다.

2024-08-31 08:29 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/DebugApiKeyButton.cs
> +        public async Task DefaultMaskedState()
테스트 메소드명은 `Given__When__Then__` 형식을 따라가세요.

2024-08-31 08:29 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/DebugApiKeyButton.cs
> +            // Then: API 키 입력 필드는 기본적으로 마스킹되어 있어야 함
테스트 메소드 안쪽에서는 `// Given`, `// When`, `// Then` 대신 `// Arrange`, `// Act`, `// Assert` 주석을 적어둔 후 따라갑니다.

2024-08-31 08:29 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/DebugApiKeyButton.cs
> +            await apiKeyInput.WaitForAsync(new LocatorWaitForOptions { Timeout = 60000 });
여기 굳이 60초 타임아웃을 두는 이유가 있나요?

2024-08-31 09:32 UTC, pmj-chosim commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/Home.razor
> +<ApiKeyInputComponent @rendermode="InteractiveServer" />
넵~감사합니다

2024-08-31 09:33 UTC, pmj-chosim commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/DebugApiKeyButton.cs
> +            await apiKeyInput.WaitForAsync(new LocatorWaitForOptions { Timeout = 60000 });
이전에 time error 생길 때 트러블 슈팅과정에서 썼던 내용을 안 지웠네요😅 삭제했습니다~

2024-08-31 09:38 UTC, justinyoo commented
@pmj-chosim 컨플릭 먼저 해결하고 진행하시지욥

2024-08-31 12:39 UTC, justinyoo commented
@pmj-chosim PR 본문이 처음엔 있었는데, 자꾸 닫고 열고 하는 과정에서 사라졌네요? PR 본문을 제대로 작성해 주세요.

2024-08-31 12:52 UTC, justinyoo requested changes

2024-08-31 12:52 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/Playground.razor
> +<ApiKeyInputComponent @rendermode="InteractiveServer" />
ConfigTabComponent 위쪽으로 이동시켜주세요.

2024-08-31 12:52 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/ApiKeyInputComponent.razor
> +@using AzureOpenAIProxy.PlaygroundApp.Clients
이 `@using ...` 디렉티브가 필요한가요?

2024-08-31 12:52 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/PlaygroundPageTests.cs
> +using FluentAssertions;
- 이 `using FluentAssersions;`는 이 파일의 첫번째 줄에 옵니다.
- `using FluentAssertions;`와 `using Microsoft.Playwright;` 사이에는 한 줄 비웁니다.

2024-08-31 12:52 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/PlaygroundPageTests.cs
> +        inputType.Should().Be("password", "API 키 입력 필드는 기본적으로 마스킹되어 있어야 합니다.");
- 한국어 메시지는 불필요합니다.
- `inputType.Should().NotBeNull().And.Be("password");` 같은 식으로 간결하게 작성할 수 있습니다.

2024-08-31 12:52 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/PlaygroundPageTests.cs
> +    public async Task Given_ApiKeyInputField_When_FieldIsLoaded_Then_FieldIsMaskedByDefault()
다른 테스트 메소드 이름을 잘 확인해 보시고, 비슷한 형식으로 만들어 주세요.

`Given Something When Something Acted Then It Should ...`

2024-08-31 12:52 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/PlaygroundPageTests.cs
> +        var apiKeyInput = Page.Locator("fluent-text-field >> input");
만약에 FluentTextField 가 여러개라면 이렇게 하면 가져올 수 있나요?

2024-08-31 12:52 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/PlaygroundPageTests.cs
> +    }
이 두 테스트의 차이는 무엇인가요?

2024-08-31 12:52 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/Home.razor
> +<ApiKeyInputComponent @rendermode="InteractiveServer" />
여기서는 빼야죠?

2024-08-31 15:27 UTC, pmj-chosim commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/Playground.razor
> +<ApiKeyInputComponent @rendermode="InteractiveServer" />
넵

2024-08-31 15:27 UTC, pmj-chosim commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/ApiKeyInputComponent.razor
> +@using AzureOpenAIProxy.PlaygroundApp.Clients
필요없는 using 들 다 삭제했습니다

2024-08-31 15:28 UTC, pmj-chosim commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/PlaygroundPageTests.cs
> +        var apiKeyInput = Page.Locator("fluent-text-field >> input");
가장 위에 배치된 Input 하나만 처리할 수 있어,  text field에 id를 부과한 후, id로 찾는 형태로 수정했습니다.

2024-09-01 02:01 UTC, justinyoo requested changes
HTML element 네이밍 컨벤션 + 테스트 케이스 작성 관련해서 리뷰 남겨뒀습니다.

2024-09-01 02:08 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/ApiKeyInputComponent.razor
> +    public EventCallback<string> OnKeyInput { get; set; }
#260 PR도 참고해서 작성해 보세요. 남들이 하는 코드를 참고하는 것도 좋은 공부입니다.

2024-09-01 02:51 UTC, pmj-chosim commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/PlaygroundPageTests.cs
> +    }
UnMasking 버튼 뒀을 때, 입력한 값(123g)이 그대로(123g) 나타나는지 체킹하기 위해 뒀었는데, 마스킹/언마스킹 버튼이 없어 필요없어 삭제했습니다

2024-09-01 02:51 UTC, pmj-chosim commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/Home.razor
> +<ApiKeyInputComponent @rendermode="InteractiveServer" />
넵!

2024-09-01 05:55 UTC, pmj-chosim commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/ApiKeyInputComponent.razor
> +<FluentTextField Id="apiKeyInputField" @bind-Value=apiKeyValue TextFieldType="TextFieldType.Password" @oninput="SetApiKey">API key input</FluentTextField>
넵! 감사합니다

2024-09-01 05:56 UTC, pmj-chosim commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/PlaygroundPageTests.cs
> +        inputType.Should().NotBeNull("Should be password type");
inputType.Should().Be("password", "Not password type");
넵! 위 코드로 수정했습니다

2024-09-01 05:56 UTC, pmj-chosim commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/PlaygroundPageTests.cs
> +   [Test]
넵 추가하겠습니다~

2024-09-01 06:37 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/PlaygroundPageTests.cs
> +        inputType.Should().NotBeNull("Should be password type");
메시지는 없어도 됩니다. 그냥 `Be("password")`로 하세요.

2024-09-01 06:41 UTC, justinyoo requested changes

2024-09-01 06:41 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/Tests.razor
> +<ApiKeyInputComponent OnKeyInput="HandleApiKeyInput" />
7번-9번 라인 사이로 옮기세요. 그리고, 이 값을 확인하는 `DebugButtonComponent`도 추가해서 매핑하시구요.

2024-09-01 06:41 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/PlaygroundPageTests.cs
> +    }
이 테스트 메소드에서는 두가지를 한번에 테스트하는데요, 테스트 메소드를 둘로 쪼개서 메소드 하나당 하나씩 테스트하는 식으로 바꿔주세요.

2024-09-01 06:41 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/PlaygroundPageTests.cs
> +        inputType.Should().Be("password", "Not password type");
여기 에러메시지는 필요 없다고 전에 리뷰에서도 남겨뒀으니... 삭제하시면 됩니다.

2024-09-01 10:16 UTC, pmj-chosim commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/Tests.razor
> +<ApiKeyInputComponent OnKeyInput="HandleApiKeyInput" />
넵!

2024-09-01 10:17 UTC, pmj-chosim commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/PlaygroundPageTests.cs
> +    }
넵 해당 인풋 컴포넌트가 잘 로딩됐는지  여부 확인, password 타입으로 잘 설정돼 있는지로 나누겠습니다.

2024-09-01 10:17 UTC, pmj-chosim commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/PlaygroundPageTests.cs
> +        inputType.Should().Be("password", "Not password type");
넵!

2024-09-01 13:55 UTC, justinyoo commented
로컬에서 테스트 돌려보고 올리는 것 맞나요?

2024-09-01 13:59 UTC, justinyoo requested changes
지금 현재 테스트 깨지고 있습니다. 로컬에서 테스트 통과하는지 확인한 후에 올려주세요.

2024-09-01 13:59 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/Playground.razor
> +        </FluentGridItem>
새 `FluentGridItem` 컴포넌트 필요없습니다.

2024-09-01 13:59 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/Playground.razor
>              <ConfigTabComponent @rendermode="InteractiveServer"/>
`ApiKeyInputComponent`는 이 `ConfigTabComponent` 바로 위에 위치시켜주세요.

2024-09-03 07:20 UTC, pmj-chosim commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/Playground.razor
> +        </FluentGridItem>
넵!

2024-09-03 07:20 UTC, pmj-chosim commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/Playground.razor
>              <ConfigTabComponent @rendermode="InteractiveServer"/>
넵!

2024-09-03 08:20 UTC, justinyoo requested changes
테스트 관련해서 리뷰 코멘트 남겨뒀습니다.

2024-09-03 08:20 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/Playground.razor
>              <ConfigTabComponent @rendermode="InteractiveServer"/>
지금은 `<FluentGrid>`와 `<FluentGridItem>` 사이에 있죠? 제가 `<ConfigTabComponent>` 바로 위에 위치시켜달라고 했습니다. ㄷㄷㄷ 그러면 어디에 들어가야 할까요? `<FluentGridItem>`과 `<ConfigTabComponent>` 사이에 있어야 하겠죠?

UI 그리드 시스템에 대해 조금만 들여다 보세요.

2024-09-03 08:20 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/Tests.razor
> +<ApiKeyInputComponent OnKeyInput="HandleApiKeyInput" />
여기도 Id 값을 파라미터로 지정하지 않으면 테스트하기 까다로울 겁니다.

2024-09-03 08:20 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/Tests.razor
> +    }
이 이벤트 핸들러는 `SetInput` 아래로 옮겨주세요.

2024-09-03 08:20 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/Tests.razor
> +<DebugButtonComponent Input="@apiKey" />
이 컴포넌트에도 Id 속성을 지정해 주세요.

2024-09-03 08:20 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/ApiKeyInputComponent.razor
> +<FluentTextField Id="api-key" @bind-Value=apiKeyValue TextFieldType="TextFieldType.Password" @oninput="SetApiKey">API key input</FluentTextField>
Testability 강화를 위해 `Id="@Id"` 형태로 해서 외부에서 주입 가능하게 해 주세요.

2024-09-03 08:20 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/ApiKeyInputComponent.razor
> +
여기에 `Id` 파라미터를 넣어 주세요.

```csharp
[Parameter]
public string? Id { get; set; }
```

2024-09-03 08:20 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/PlaygroundPageTests.cs
> +    public async Task Given_ApiKeyInputField_When_Page_Loaded_Should_Be_Visible()
`Given__When__Then__` 형식으로 메소드 네이밍을 잡아주세요. 다른 테스트 메소드를 참고하시면 됩니다.

예) `Given_ApiKeyInputComponent_When_Page_Loaded_Then_It_Should_Be_Visible()`

2024-09-03 08:20 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/PlaygroundPageTests.cs
> +    }
이 테스트 메소드 하나에서 `Expect`가 두 번 나온다는 얘기는 서로 다른 두 가지를 테스트한다는 얘긴데, 그러려면 테스트 메소드를 둘로 쪼개서 각각 하나씩 테스트할 수 있게끔 해 주세요.

2024-09-03 08:20 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/PlaygroundPageTests.cs
> +        await Expect(apiKeyInput).ToBeVisibleAsync();
이건 이미 앞에서 테스트를 했는데, 굳이 여기서 한 번 더 테스트를 하는 이유가 있나요?

2024-09-03 08:20 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/Tests.razor
> +<ApiKeyInputComponent OnKeyInput="HandleApiKeyInput" />
이 값을 `Test.razor` 페이지에서 테스트하는 코드가 없습니다.

2024-09-05 22:26 UTC, justinyoo requested changes

2024-09-05 22:26 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/ApiKeyInputComponent.razor
> +    private string? apiKeyValue { get; set; }
이 `private` 필드를 모든 파라미터 앞으로 옮겨주세요.

2024-09-05 22:26 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/PlaygroundPageTests.cs
> +    public async Task Given_ApiKeynputField_When_Endpoint_Invoked_Then_It_Should_Be_Show()
`It_Should_Be_Show`라는 표현은 없습니다 `It_Should_Be_Shown` 정도가 되겠죠?

2024-09-05 22:26 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/ApiKeyInputComponent.razor
> +        }
만약에 `null` 값이 아니지만 `string.Empty` 값인 경우에도 실행시키나요? 아니면 누군가 공백문자 같은 걸 넣으면 어떻게 되나요?

2024-09-05 22:26 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/TestsPageTests.cs
> +        await apiKeyInput.FillAsync("");
테스트 메소드 이름은 `Given_Null`인데 여기서는 그냥 empty string을 넣었네요?

2024-09-05 22:26 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/TestsPageTests.cs
> +        await Expect(Page.Locator(".fluent-toast-title")).ToHaveTextAsync($"{apiKey} (Type: System.String)");
`Type: System.String` 같은 식으로 하드코딩하면 안됩니다. 마찬가지로 타입을 73-74번 라인을 통해 받아오세요. 이미 관련한 테스트 코드가 있으니 그걸 참조하세요.

2024-09-05 22:50 UTC, pmj-chosim commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/ApiKeyInputComponent.razor
> +    private string? apiKeyValue { get; set; }
넵!

2024-09-05 22:50 UTC, pmj-chosim commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/PlaygroundPageTests.cs
> +    public async Task Given_ApiKeynputField_When_Endpoint_Invoked_Then_It_Should_Be_Show()
넵 수정하겠습니다.

2024-09-05 22:53 UTC, pmj-chosim commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/ApiKeyInputComponent.razor
> +        }
string.Empty에 대해 처리를 못해서  !string.IsNullOrWhiteSpace(apiKeyValue) 검사 조건으로 수정하려고 합니다.

2024-09-05 22:56 UTC, pmj-chosim commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/TestsPageTests.cs
> +        await apiKeyInput.FillAsync("");
아무것도 입력하지 않았을 때 상황을 테스트하려고 했어서, Given_Empty_ApiKeyInput~로 메소명을 변경하고 await apiKeyInput.FillAsync(string.Empty); 에 대해 테스트하려고 합니다.

2024-09-05 23:26 UTC, justinyoo requested changes

2024-09-05 23:26 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/ApiKeyInputComponent.razor
> +        }
`!` 보다는 `== true`해서 그냥 빠져나가고, 그 밑에 `false`인 경우에 핸들러를 실행시키는 방향으로 가 보세요.

예)

```csharp
if (string.IsNullOrWhiteSpace(apiKeyValue) == true)
{
    return;
}

await OnKeyInput.InvokeAsync(apiKeyValue);
```

2024-09-05 23:26 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/TestsPageTests.cs
> +        await apiKeyInput.FillAsync("");
테스트명을 바꾸면서 동시에 `[TestCase(...)]`를 활용하면 테스트 메소드 하나로 여러 경우를 테스트해 볼 수 있겠죠?

2024-09-06 03:10 UTC, pmj-chosim commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/ApiKeyInputComponent.razor
> +        }
넵 감사합니다

2024-09-06 03:13 UTC, pmj-chosim commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/TestsPageTests.cs
> +        await apiKeyInput.FillAsync("");
Empty보단 입력이 없을 때를 테스팅하는 게 더 적합할 것 같아서
Given_No_Input_On_ApiKeyField_When_DebugButton_Clicked_Then_Toast_Should_Show_NullMessage() 이렇게 메소드 변경하려고 하는게 괜찮을까요? 

Given_Input_On_DebugTarget_When_DebugButton_Clicked_Then_Toast_Should_Show_Input((string apiKeyValue, Type inputType))에 대해서  [TestCase("api-test-ex-key123", typeof(string))], [TestCase("3.141592**^$", typeof(string))]
테스트 케이스 2개 주려고 합니다.

2024-09-06 03:15 UTC, pmj-chosim commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/TestsPageTests.cs
> +        await Expect(Page.Locator(".fluent-toast-title")).ToHaveTextAsync($"{apiKey} (Type: System.String)");
넵 await Expect(Page.Locator(".fluent-toast-title")).ToHaveTextAsync($"{apiKeyValue} (Type: {inputType.FullName})"); 받아 오게 수정하겠습니다.

2024-09-06 04:38 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/TestsPageTests.cs
> +        await apiKeyInput.FillAsync("");
- 입력값이 안 들어오는 건 `FluentTextField` 속성 중 `Required` 파라미터를 세팅하면 됩니다. 굳이 테스트할 필요가 없어요.
- 마찬가지로 이 값은 GUID 형태가 되기 때문에 해당 패턴인지 아닌지 확인해야 합니다.

관련 문서를 꼼꼼하게 찾아보세요.

2024-09-06 04:40 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/TestsPageTests.cs
> +        await Expect(Page.Locator(".fluent-toast-title")).ToHaveTextAsync($"{apiKey} (Type: System.String)");
그렇지 않을텐데요? 기존의 테스트 코드가 그렇게 되어 있던가요?

2024-09-12 15:23 UTC, justinyoo requested changes
아직 코드 리뷰사항 반영이 전부 되어 있지 않습니다.

2024-09-12 15:23 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/TestsPageTests.cs
> +        await Expect(Page.Locator(".fluent-toast-title")).ToHaveTextAsync($"{apiKey} (Type: System.String)");
여기 코드리뷰 반영 안됐습니다.

2024-09-12 15:23 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/TestsPageTests.cs
> +        await apiKeyInput.FillAsync("");
여기 코드리뷰 반영 안됐습니다.

2024-09-12 15:23 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/ApiKeyInputComponent.razor
> +        apiKeyValue = e?.Value?.ToString();
`e?.Value?.ToString()`이 맞을까요, `e.Value!.ToString()`이 맞을까요?

2024-09-14 05:31 UTC, pmj-chosim commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/TestsPageTests.cs
> +        await apiKeyInput.FillAsync("");
// Assert
        if (expectedType == typeof(string))
        {
            string guidPattern = @"^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$";
            bool isGuid = Regex.IsMatch(apiKey, guidPattern);
             if (!isGuid) return;
        }
        
        이렇게 입력받은 string이 guid 형태인지 아닌지 테스트해도 될까요?

2024-09-14 06:18 UTC, pmj-chosim commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/ApiKeyInputComponent.razor
> +        apiKeyValue = e?.Value?.ToString();
null error 생길까봐 e?.Value?.ToString()를 했었는데, 입력을 받게 설정(required="true")하고 e.Value!.ToString()로 변경하겠습니다

2024-09-14 06:23 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/TestsPageTests.cs
> +        await apiKeyInput.FillAsync("");
지금은 UI 컴포넌트를 만드는 단계이지 UI 로직을 넣는 단계가 아닙니다.

2024-09-14 06:40 UTC, pmj-chosim commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/TestsPageTests.cs
> +        await apiKeyInput.FillAsync("");
GUID 패턴 확인하라고 말씀주신 부분을 제가 이해를 잘 못한 것 같습니다. 한 메소드에 여러 testcase로 test 수행하라고 말씀주셔서 guid 형태도 인풋에 해당하는 부분이니까 testcode에서 검증이 필요한 것으로 이해했는데요.
그게 아니라 검증 자체가 필요없고
<FluentTextField Id=~~ data-type="GUID" required="True"~~>
이렇게 component 에 지정을 하라는 말씀이신가요?
   
   //코드
   [Test]
    [TestCase("test-api-key-321", typeof(string))]
    [TestCase("example-key-123", typeof(string))]
    [TestCase("b9f6741c-2f44-4d9b-bd63-c0e6b97cc83f", typeof(string))]

    public async Task Given_Input_On_ApiKeyField_When_DebugButton_Clicked_Then_Toast_Should_Show_Input(string apiKey, Type expectedType)
    {
        // Arrange
        var apiKeyInput = Page.Locator("fluent-text-field#api-key-input").Locator("input");
        var debugButton = Page.Locator("fluent-button#debug-api-key");

        // Act
        await apiKeyInput.FillAsync(apiKey);
        await debugButton.ClickAsync();
        

        // Assert
        if (expectedType == typeof(string))
        {
            string guidPattern = @"^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$";
            bool isGuid = Regex.IsMatch(apiKey, guidPattern);
             if (!isGuid) return;
        }
        await Expect(Page.Locator(".fluent-toast-title")).ToHaveTextAsync($"{apiKey} (Type: {expectedType})");
    }

2024-09-14 07:24 UTC, justinyoo requested changes
테스트 페이지 로직은 신경 쓰지 않아도 됩니다. 이제 테스트 페이지는 없어질 거예요.

2024-09-14 07:24 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/PlaygroundPageTests.cs
> +        var id = "api-key";
굳이 이 값을 따로 빼는 이유는 뭔가요?

2024-09-14 07:24 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/PlaygroundPageTests.cs
> +        var apiKeyInput = Page.Locator($"fluent-text-field#{id}").Locator("input");
그냥 여기에 바로 넣어도 될 것 같은데?

2024-09-14 07:24 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/TestsPageTests.cs
> +        await apiKeyInput.FillAsync("");
지금 이 태스크는 UI 컴포넌트를 만드는 단계이지, 그 컴포넌트에 UI 로직을 넣는 단계는 아니예요. 그러니 지금 단계에서는 이게 GUID이든 뭐든 상관이 없다는 거죠.

이 필드에 필요한 값이 GUID 형태가 되는 것은 맞지만, 그걸 검증한다거나 하는 로직이 지금 필요하지는 않습니다.

2024-09-14 07:35 UTC, pmj-chosim commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/PlaygroundPageTests.cs
> +        var id = "api-key";
변수로 안 빼고 바로 사용하겠습니다

2024-09-14 07:35 UTC, pmj-chosim commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/PlaygroundPageTests.cs
> +        var apiKeyInput = Page.Locator($"fluent-text-field#{id}").Locator("input");
넵 수정하겠습니다

2024-09-14 07:40 UTC, pmj-chosim commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/TestsPageTests.cs
> +        await apiKeyInput.FillAsync("");
넵!! 이제 이해했습니다

2024-09-16 02:07 UTC, justinyoo approved these changes
고생하셨습니다! LGTM!

2024-09-16 02:08 UTC, merged