[DevOps] Table Storage용 bicep 파일 만들기 #283
aliencube/azure-openai-sdk-proxy pull request #292
Opened 2024-09-01 08:48 UTC by tae0y

관련이슈 #283 #213  
관련PR #281 

## 진행상황 공유
진행상황을 공유하기 위한 PR 제출입니다.
- 진행한것 : 기본 bicep 파일추가, 테이블 이름 목록을 받아 생성하기

2024-09-01 08:48 UTC, tae0y commented
## 트러블슈팅 공유
이런 증상이 있어 트러블슈팅 중인데 실마리를 찾지 못하고 있습니다.
azd up에서 `infra/storage-account.bicep`를 인식하지 못하는 것 같아서,
**이걸 인식시켜줄 방법을 찾아보고 있어요. 이 방향이 맞을까요?** @justinyoo 

### 증상을 해결해주는 것들, 하지만 여전히 azd up만으로는 배포되지 않음
  - `az deployment group create --resource-group rg-tae0y --template-file infra/storage-account.bicep`처럼 bicep을 특정하면 배포가 잘 됨
  - azd infra synth로 생성되는 resources.bicep에서 다음 구문을 추가하면 증상 해소됨

```
module storageAccount 'storage-account.bicep' = {
    name: 'storageAccount'
}
```

### 시도해도 증상이 해소되지 않았던 것들
  - `infra/storage-account.bicep`을 추가했으나 `azd up`으로 배포되지 않음
  - `infra/storage-account.bicep`를 자동으로 감지하지 못하는 것 같아 `azure.yaml` 수정했으나 증상 해소되지 않음
  -  `infra/main.bicep`으로 이름 바꿔서 다시 진행해보았지만 증상 해소되지 않음
  - azd 업그레이드

```yaml
# 다음 구문을 azure.yaml에 추가함
infra:
  bicep: ./infra/storage-account.bicep
```

```shell
# az 버전정보
→ az version
{
  "azure-cli": "2.63.0",
  "azure-cli-core": "2.63.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "containerapp": "0.3.53"
  }
}

# azd version
→ azd --version
azure-cli                         2.63.0

core                              2.63.0
telemetry                          1.1.0

Extensions:
containerapp                      0.3.53

Dependencies:
msal                              1.30.0
azure-mgmt-resource               23.1.1

Python location '/opt/homebrew/Cellar/azure-cli/2.63.0/libexec/bin/python'
Extensions directory '/Users/bachtaeyeong/.azure/cliextensions'

Python (Darwin) 3.11.9 (main, Apr  2 2024, 08:25:04) [Clang 15.0.0 (clang-1500.3.9.4)]

Legal docs and information: aka.ms/AzureCliLegal
Your CLI is up-to-date.
```

2024-09-01 13:47 UTC, justinyoo requested changes
테이블 배열 넘기는 부분은 `aspire.bicep` 파일에서 모듈을 불러오는 것으로 하면서 거기서 넘겨주면 됩니다.

2024-09-01 13:47 UTC, justinyoo commented on infra/abbreviations.json
이 파일은 수정할 필요가 없습니다.

2024-09-01 13:47 UTC, justinyoo commented on infra/storage-account.bicep
https://github.com/Azure-Samples/azd-starter-bicep/blob/main/infra/core/storage/storage-account.bicep

이 파일을 그대로 들고 오시고 디렉토리 구조를 동일하게 맞춰주세요.

2024-09-01 13:47 UTC, justinyoo commented on infra/storage-account.bicep
> +    }]
https://github.com/Azure-Samples/azd-starter-bicep/blob/main/infra/core/storage/storage-account.bicep 이 파일을 그대로 들고온 후에

이 부분만 수정하면 됩니다.

2024-09-03 14:50 UTC, tae0y commented on infra/abbreviations.json
변경사항 원복했습니다

2024-09-03 14:51 UTC, tae0y commented on infra/storage-account.bicep
넵 디렉토리 구조 유지해서 파일 가져왔습니다
테이블 생성하는 부분만 수정했고, 각주 달아뒀습니다

2024-09-03 14:53 UTC, tae0y commented
해당 테이블 스토리지를 참조해서 의존객체 생성하는 부분은
@sikutisa 일구님 작업 준비중입니다!

2024-09-05 23:09 UTC, justinyoo requested changes
몇가지 추가적으로 고려해 볼 사항을 리뷰 코멘트로 남겨뒀습니다.

2024-09-05 23:09 UTC, justinyoo commented on infra/aspire.bicep
> +
스토리지 어카운트의 커넥션 스트링도 받아와야겠죠? 대신, 이건 민감한 값이니 키볼트에 저장하는 방식을 써야 할 거예요.

아래 코드 참조해 보시구요,

https://github.com/devkimchi/aitb-parameters/blob/2fc2b2f96d832c9a047c5dc73969c765b16cc6cb/infra/core/gateway/apim.bicep#L59-L73

`infra/core/security/keyvault-secret.bicep` 이 리소스를 이용해서 커넥션 스트링을 키볼트에 저장해 보세요.

마지막으로 저장하고자 하는 키볼트 시크릿 이름은 `storage-connection-string` 쯤이면 적당하려나요?

2024-09-07 02:15 UTC, tae0y commented on infra/aspire.bicep
> +
명령줄에서 쉼표로 구분해서 입력할 수 있도록 수정했습니다

2024-09-07 02:15 UTC, tae0y commented on infra/aspire.bicep
> +        name: 'st${resourceToken}'
수정해보았습니다

2024-09-07 02:17 UTC, tae0y commented on infra/aspire.bicep
> +
진행해보았는데 아래와 같은 이슈가 있습니다

생성한 keyvault secret을 az에서 조회시 Forbidden 메시지
```shell
→ az keyvault secret show --name storageAccountConnectionString --vault-name kv-kbqn37idzenzi
(Forbidden) Caller is not authorized to perform action on resource.
If role assignments, deny assignments or role definitions were changed recently, please observe propagation time.
Caller: appid=04b07795-8ddb-461a-bbee-02f9e1bf7b46;oid=7873fe16-32eb-4c9d-80c1-b4ac8309b541;iss=https://sts.windows.net/0555c25f-8f8e-4aab-8ed6-28c995245080/
Action: 'Microsoft.KeyVault/vaults/secrets/getSecret/action'
Resource: '/subscriptions/cafd0f57-708a-480c-a55b-60004fc24611/resourcegroups/rg-tae0y/providers/microsoft.keyvault/vaults/kv-kbqn37idzenzi/secrets/storageaccountconnectionstring'
Assignment: (not found)
DenyAssignmentId: null
DecisionReason: null 
```

코파일럿, ms learn을 참고하면 아래와 같이 권한설정이 필요해보여요
이 방향이 맞을까요?
```shell
// Retrieve the object ID of the user deploying the template
var userObjectId = subscription().subscriptionId

// Assign the Key Vault Secrets User role to the user
resource keyVaultRoleAssignment 'Microsoft.Authorization/roleAssignments@2020-04-01-preview' = {
    name: guid(keyVault.id, userObjectId, 'b86a8fe4-44ce-4948-aee5-eccb2c155cd7') // Unique GUID for the role assignment
    scope: keyVault
    properties: {
        roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', 'b86a8fe4-44ce-4948-aee5-eccb2c155cd7') // Key Vault Secrets User role
        principalId: userObjectId
    }
}
```

2024-09-07 02:58 UTC, justinyoo requested changes
현재 컨테이너 앱을 키볼트에 연결시키는 부분이 없는데, 이건 같이 고민을 좀 해 보시죠.

2024-09-07 02:58 UTC, justinyoo commented on infra/aspire.bicep
> +var resolvedStorageAccountName = !empty(storageAccountName) ? storageAccountName : '${abbrs.storageStorageAccounts}${resourceToken}'
이건 굳이 `var`로 뺄 필요 없이 그냥 아래 모듈로 바로 넣으면 됩니다.

2024-09-07 02:58 UTC, justinyoo commented on infra/aspire.bicep
> +}
이미 우리 모듈에 있습니다. 그걸 활용해 보세요:

https://github.com/aliencube/azure-openai-sdk-proxy/blob/main/infra/core/security/keyvault-secret.bicep

2024-09-07 05:39 UTC, tae0y commented
> 현재 컨테이너 앱을 키볼트에 연결시키는 부분이 없는데, 이건 같이 고민을 좀 해 보시죠.

권한 설정하는 부분은 아래와 같이 구문을 추가해두었습니다
principalId가 무엇인지 어떻게 가져올지는 조사 중입니다. 

```C#
// Role Assignment for Key Vault secret : creator admin, apiapp user
resource keyVaultSecretRoleAssignment 'Microsoft.Authorization/roleAssignments@2020-04-01-preview' = {
    name: guid(resourceGroup().id, resolvedKeyVaultName, 'secret-role-assignment')
    properties: {
        principalId: creatorAdminPrincipalId
        roleDefinitionId: '00482A5A-887F-4FB3-B363-3B7FE8E74483' // administrator role
    }
}

resource keyVaultSecretApiAppRoleAssignment 'Microsoft.Authorization/roleAssignments@2020-04-01-preview' = {
    name: guid(resourceGroup().id, resolvedKeyVaultName, 'secret-apiapp-role-assignment')
    properties: {
        principalId: apiAppUserPrincipalId
        roleDefinitionId: '4633458B-17DE-408A-B874-0445C86B69E6' // secret user role
    }
}
```

2024-09-07 05:39 UTC, tae0y commented on infra/aspire.bicep
> +var resolvedStorageAccountName = !empty(storageAccountName) ? storageAccountName : '${abbrs.storageStorageAccounts}${resourceToken}'
넵 제출한 커밋에는
이 부분 놓쳐서 다시 확인해보겠습니다

2024-09-07 05:39 UTC, tae0y commented on infra/aspire.bicep
> +}
이것도 다시 확인해보겠습니다

2024-09-07 05:46 UTC, tae0y commented
커넥션스트링 자체는 잘 저장하고, 
해당 문자열을 조회해서(Azure portal에서 넣어주신 어드민 권한으로)
테이블이 잘 생성되었는지까지는 테스트 했습니다!

## 실행/배포
- 배포 명령어
```zsh
# 기본 변수설정
AZURE_ENV_NAME="tae0y"
AZURE_RESOURCE_GROUP="rg-$AZURE_ENV_NAME"

az deployment group create \
-g $AZURE_RESOURCE_GROUP \
--template-file ./infra/aspire.bicep \
--parameters environmentName='tae0y' \
--parameters location=$(azd env get-value AZURE_LOCATION) \
--parameters tableNames=events,tests #여기에 생성할 테이블 목록을 쉼표로 구분하여 ㅈ가성
```

## 테스트
- 테스트 명령어
```zsh
# 기본 변수설정
AZURE_ENV_NAME="tae0y"
AZURE_RESOURCE_GROUP="rg-$AZURE_ENV_NAME"

# 배포된 키볼트 이름 조회
KEY_VAULT_NAME=$(az keyvault list --resource-group $AZURE_RESOURCE_GROUP --query "[].name" --output tsv)

# 연결문자열을 환경변수로 설정
export AZURE_STORAGE_CONNECTION_STRING=$(az keyvault secret show --name storageAccountConnectionString --vault-name $KEY_VAULT_NAME | jq -r '.value')

# 생성된 테이블 목록을 조회
az storage table list --connection-string $AZURE_STORAGE_CONNECTION_STRING
```

- 테스트결과
```
[
  {
    "name": "events"
  },
  {
    "name": "tests"
  }
]
```

2024-09-07 06:04 UTC, justinyoo requested changes

2024-09-07 06:04 UTC, justinyoo commented on infra/aspire.bicep
> +}
우선은 이 부분은 주석처리해 둘까요? 지금 당장은 수동으로 추가하면 될 듯?

2024-09-07 06:04 UTC, justinyoo commented on infra/aspire.bicep
> +resource storageAccountConnectionString 'Microsoft.Keyvault/vaults/secrets@2023-07-01' = {
`resource` 대신 `module`을 써서 현재 이미 저장되어 있는 모듈을 통해 시크릿을 넣을 수 있는 방법이 있을 것 같은데요?

2024-09-07 12:00 UTC, tae0y commented on infra/aspire.bicep
> +var resolvedStorageAccountName = !empty(storageAccountName) ? storageAccountName : '${abbrs.storageStorageAccounts}${resourceToken}'
반영했습니다!

2024-09-07 12:00 UTC, tae0y commented on infra/aspire.bicep
> +}
네 주석처리 했습니다

2024-09-07 12:02 UTC, tae0y commented on infra/aspire.bicep
> +}
반영했습니다. 다만 이런 고민이 있습니다.

- 피하고 싶었던 것 : storage-account.bicep에서 connection string을 output으로 노출하고 싶지 않았음
- **그래서 진행한 것 : storage-account.bicep 내부에서 keyvault-secret.bicep 모듈을 참조하여 키값을 저장**
- 우려스러운 것 : 향후 keyvault-secret.bicep을 다른 모듈 등에서 참조할 때 이름 충돌, 모듈 중복생성, 모듈 참조 순환오류

2024-09-07 12:03 UTC, tae0y commented on infra/aspire.bicep
> +param tableNames string = 'events,tests'
반영했습니다

2024-09-07 12:03 UTC, tae0y commented on infra/aspire.bicep
> +}
반영했습니다

2024-09-07 12:03 UTC, tae0y commented on infra/aspire.bicep
> +}
반영했습니다

2024-09-07 12:03 UTC, tae0y commented on infra/aspire.bicep
> +resource storageAccountConnectionString 'Microsoft.Keyvault/vaults/secrets@2023-07-01' = {
반영했습니다

2024-09-10 08:02 UTC, justinyoo requested changes

2024-09-10 08:02 UTC, justinyoo commented on infra/core/storage/storage-account.bicep
> +}
혹시 이 모듈을 `aspire.bicep`에서 사용할 수 있나요?

2024-09-12 00:37 UTC, justinyoo requested changes
질문을 남겼습니다!

2024-09-12 00:37 UTC, justinyoo commented on infra/aspire.bicep
> +}
이 레퍼런스를 무조건 써야 하나요? 그냥 그 위에서 받아온 `storageAccount`를 쓸 수는 없고?

2024-09-12 00:37 UTC, justinyoo commented on infra/aspire.bicep
> +        secretValue: 'DefaultEndpointsProtocol=https;EndpointSuffix=${environment().suffixes.storage};AccountName=${storageAccount.name};AccountKey=${storageAccountReference.listKeys().keys[0].value}
여기서 액세스 키를 받아오려면 반드시 위에서처럼 해야 하는건가요? `storageAccount.listKeys().keys[0].value`는 아예 안되는 건가?

2024-09-12 05:28 UTC, tae0y commented on infra/aspire.bicep
> +        secretValue: 'DefaultEndpointsProtocol=https;EndpointSuffix=${environment().suffixes.storage};AccountName=${storageAccount.name};AccountKey=${storageAccountReference.listKeys().keys[0].value}
@justinyoo 멘토님 여기입니다!

2024-09-12 05:30 UTC, justinyoo commented on infra/core/storage/storage-account.bicep
> +        secretValue:'DefaultEndpointsProtocol=https;EndpointSuffix=${environment().suffixes.storage};AccountName=${storage.name};AccountKey=${storage.listKeys().keys[0].value};BlobEndpoint=${storage.
> 이전에 각 module 이름을 참조한 resource를 중복으로 생성한 이유는, resource로 선언되어 있어야 내부 값을 참조할 수 있었어요

아아아... 리소스로 선언을 해야만 하는군요! 그러면 키볼트 시크릿 모듈 호출하는 로직을 스토리지 어카운트 모듈 안으로 넣어야겠네.

2024-09-12 05:33 UTC, justinyoo requested changes

2024-09-12 05:33 UTC, justinyoo commented on infra/core/storage/storage-account.bicep
> +
여기서 키볼트 시크릿 모듈 호출해서 넣는 방향으로 가시지요.

2024-09-12 05:34 UTC, tae0y commented on infra/core/storage/storage-account.bicep
> +
넵! 수정해서 테스트 코드랑 같이 제출하겠습니다.
Readme 쪽에 테이블 파라미터 넘기는 방법도 추가해볼게욥.

2024-09-13 14:53 UTC, tae0y commented on infra/core/storage/storage-account.bicep
> +
수정해서 제출했습니다

2024-09-14 01:30 UTC, justinyoo requested changes

2024-09-14 01:30 UTC, justinyoo commented on README.md
> +        --parameters tableNames=events,tests
이미 bicep 파일 안에 기본값으로 `events`가 지정되어 있으니까 여기서는 굳이 명시하지 않아도 됩니다.

2024-09-14 01:30 UTC, justinyoo commented on README.md
> +        --parameters tableNames=events,tests
이미 bicep 파일 안에 기본값으로 `events`가 지정되어 있으니까 여기서는 굳이 명시하지 않아도 됩니다.

2024-09-14 01:30 UTC, justinyoo commented on infra/core/storage/storage-account.bicep
> +        name: 'Storage'
이 값이 `Storage`가 맞나요? `storage-connection-string`이 되어야 할 듯?

https://github.com/aliencube/azure-openai-sdk-proxy/blob/1f7d4180edcf8bd95c9a0db87ab96ec575d15190/src/AzureOpenAIProxy.ApiApp/appsettings.json#L30

2024-09-14 02:08 UTC, tae0y commented on README.md
> +        --parameters tableNames=events,tests
넵! 수정해서 다시 제출했습니다

2024-09-14 02:09 UTC, tae0y commented on infra/core/storage/storage-account.bicep
> +        name: 'Storage'
오! 착각했네요. 수정해서 다시 제출했습니닷!

2024-09-14 05:32 UTC, justinyoo approved these changes
수고하셨습니다! LGTM

2024-09-14 05:32 UTC, merged