[Admin] Component: Create event details - UI component #214
aliencube/azure-openai-sdk-proxy pull request #293
Opened 2024-09-01 11:28 UTC by KYJKY

## Task
#214 

<br/>

## 작업사항
![image](https://github.com/user-attachments/assets/7b7d4879-9961-4567-96d3-10b0ea5b404f)

- NewEventDetailsComponent.razor 생성: 어드민 페이지에서 이벤트를 생성하는 컴포넌트를 만들었습니다.
- Model 클래스 폴더 생성: 이벤트 생성 데이터를 담기 위해 기존 API 모델 클래스 복사

<br/>

## 궁금한/잘 모르겠는 부분
- 컴포넌트 단위에 대한 고민: 컴포넌트 계층구조에 대한 고민이 있습니다. 특히 제가 작업한 내용이 어떤 외부 컴포넌트에서 참조하는지에 대해 불분명?한 상황입니다. `/Components/Pages/AdminCreateEvent.razor`와 같은 외부 컴포넌트 내에 제가 작업한 `NewEventDetailsComponent.razor`를 포함시키는 방식으로 만들어야 하는지, 아니면 현재 만들어져 있는 `/Components/Pages/Admin.razor`에서 추후 참조하게 만들게 될지에 대해 잘 모르겠습니다.
- Task 단위에 대한 고민: 해당 Task와 #215 Task와의 경계가 궁금합니다. 아래 작업들이 현재 Task에서 진행되어야 할지, 215번에서 진행되어야 할지 궁금합니다.
  - Front App에서 유효성검사
  - 입력값을 Model Class에 맵핑
- CSS 관리에 대해 내부에 `<Style>`로 작성해도 상관 없을지 궁금합니다.
- 단위 테스트 코드에 대하여 각각 모든 input에 대해 존재 여부를 메서드로 추가하면 충분한 테스트인지 궁금합니다. 만약 유효성 검사 코드를 추가하게 된다면 input 단위로 유효성 검사 코드를 테스트 하는 메서드를 각각 추가하면 될까요?

<br/>

## 추후 작업 예정
- 단위 테스트 코드 작성
- Task 단위에 따라 유효성 검사 및 Model Class 맵핑 작업 추가

<br/>

2024-09-01 14:05 UTC, justinyoo commented
@KYJKY 아무래도 새 페이지 `/admin/events/new`를 만들어야 하는 시점이 됐네요. 이 페이지 먼저 만들어 볼까요? 새 태스크 열어두겠습니다. 그것 먼저 작업하시지요. 파일 이름은 `Components/Pages/AdminNewEvent.razor` 쯤으로 하겠습니다.

2024-09-01 14:08 UTC, justinyoo commented
#295

2024-09-01 14:35 UTC, justinyoo requested changes
> 컴포넌트 단위에 대한 고민: 컴포넌트 계층구조에 대한 고민이 있습니다. 특히 제가 작업한 내용이 어떤 외부 컴포넌트에서 참조하는지에 대해 불분명?한 상황입니다. /Components/Pages/AdminCreateEvent.razor와 같은 외부 컴포넌트 내에 제가 작업한 NewEventDetailsComponent.razor를 포함시키는 방식으로 만들어야 하는지, 아니면 현재 만들어져 있는 /Components/Pages/Admin.razor에서 추후 참조하게 만들게 될지에 대해 잘 모르겠습니다.

`AdminNewEvent.razor` 페이지를 만들었습니다. 그 안에 넣어두세요.

> Task 단위에 대한 고민: 해당 Task와 https://github.com/aliencube/azure-openai-sdk-proxy/issues/215 Task와의 경계가 궁금합니다. 아래 작업들이 현재 Task에서 진행되어야 할지, 215번에서 진행되어야 할지 궁금합니다.
> 
> - Front App에서 유효성검사
> -입력값을 Model Class에 맵핑

이 PR에서는 다루지 않고 #215 에서 진행합니다.

> CSS 관리에 대해 내부에 <Style>로 작성해도 상관 없을지 궁금합니다.

Scoped CSS로 작성하세요. 하지만, 그 이전에 기본 Fluent UI 제공 CSS로 충분한지 먼저 검토해 보세요.

> 단위 테스트 코드에 대하여 각각 모든 input에 대해 존재 여부를 메서드로 추가하면 충분한 테스트인지 궁금합니다.

맞습니다.

> 만약 유효성 검사 코드를 추가하게 된다면 input 단위로 유효성 검사 코드를 테스트 하는 메서드를 각각 추가하면 될까요?

#215 에서 진행합니다.

2024-09-01 14:35 UTC, justinyoo commented on AzureOpenAIProxy.sln
이 파일은 수정이 필요없는데 수정한 이유가 있나요?

2024-09-01 14:35 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/NewEventDetailsComponent.razor
이 콤포넌트를 새 이벤트 생성할 때, 기존 이벤트 수정할 때, 기본 이벤트를 볼 때 세 가지 경우에 다 사용할 수 있게 하려면 파일 이름을 어떻게 수정하면 좋을까요?

2024-09-01 14:35 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/NewEventDetailsComponent.razor
> +</style>
별도의 scoped CSS로 뺄까요? `xxxComponent.razor.css` 파일로 만들어 두시면 됩니다. 그런데 굳이 이 scoped CSS가 필요한가요? Fluent UI 기본 CSS로는 해결이 안되나요?

2024-09-01 14:35 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Models/AdminEventDetails.cs
최신화가 안 되어 있습니다. 다시 확인해 보세요.

2024-09-01 14:35 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Models/EventDetails.cs
최신화가 안 되어 있습니다. 다시 확인해 보세요.

2024-09-01 14:35 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/NewEventDetailsTests.cs
아직 테스트는 추가하지 않은 거죠?

2024-09-03 08:28 UTC, justinyoo requested changes

2024-09-03 08:28 UTC, justinyoo commented on AzureOpenAIProxy.sln
이 솔루션 파일을 수정하는 이유가 있나요?

2024-09-03 08:28 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Models/AdminEventDetails.cs
JSON 직렬화/비직렬화 관련해서라면 https://github.com/aliencube/azure-openai-sdk-proxy/blob/main/src/AzureOpenAIProxy.ApiApp/Models/AdminEventDetails.cs 대로 최신화 시켜보세요.

2024-09-03 08:28 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Models/EventDetails.cs
JSON 직렬화/비직렬화 관련해서라면 https://github.com/aliencube/azure-openai-sdk-proxy/blob/main/src/AzureOpenAIProxy.ApiApp/Models/EventDetails.cs 대로 최신화를 시켜주세요.

2024-09-03 08:28 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/NewEventDetailsTests.cs
아직 테스트는 하나도 추가하지 않은 거죠?

2024-09-03 14:49 UTC, KYJKY commented on AzureOpenAIProxy.sln
해당 파일은 VS 2022에서 자동으로 변환된 것 같습니다. 기존 내용으로 다시 적용하도록 하겠습니다.

2024-09-03 14:54 UTC, KYJKY commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/NewEventDetailsComponent.razor
세 가지 경우를 포괄하는 EventDetailsComponent.razor로 수정하면 좋을 것 같습니다.

2024-09-03 14:55 UTC, KYJKY commented on src/AzureOpenAIProxy.PlaygroundApp/Models/AdminEventDetails.cs
넵 알겠습니다!

2024-09-03 14:58 UTC, KYJKY commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/NewEventDetailsComponent.razor
> +</style>
해당 부분은 Fluent UI 문서를 좀 더 검토해보고 대체할 수 있다면 대체하는 방향으로 수정하겠습니다.

2024-09-03 14:59 UTC, KYJKY commented on src/AzureOpenAIProxy.PlaygroundApp/Models/AdminEventDetails.cs
네넵!

2024-09-03 15:39 UTC, KYJKY commented
#295 작업 후, 다시 돌아와서 수정하도록 하겠습니다.

2024-09-06 03:49 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/NewEventDetailsComponent.razor
뉍! 그러면 파일 이름을 `EventDetailsComponent.razor`로 수정하고 진행해 보시지욥!

그러려면 컴포넌트 파라미터로 이 컴포넌트의 상태(?)를 넘겨야 할 것 같은데요, 예를 들어 `EventDetailsType.New`, `EventDetailsType.View`, `EventDetailsType.Update` 같은 enum이 하나 있어서 그걸 활용하면 좋을 것 같습니다.

2024-09-06 04:15 UTC, justinyoo requested changes
수정사항 코멘트 남겨뒀습니다!

2024-09-06 04:15 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/NewEventDetailsComponent.razor
> +    <FluentHeader>Create Event</FluentHeader>
`New Event` 라고 할까요?

2024-09-06 04:15 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/NewEventDetailsComponent.razor
> +                <FluentSelect Id="timezone" TOption="string" Required>
타임존은 이 패키지를 써서 리스트를 만들어 주세요: https://nodatime.org/

2024-09-06 04:15 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/NewEventDetailsComponent.razor
> +                <FluentTextField Id="organizerEmail" Required />@@<FluentTextField Required />
굳이 이메일의 `@` 기준으로 앞뒤 두 개 필드를 설정할 필요는 없구요, `TextFieldType` 파라미터로 설정해 보세요.

2024-09-06 04:15 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/NewEventDetailsComponent.razor
> +                <FluentTextField Id="coorgnizerEmail" Required />@@<FluentTextField Required />
여기도 `FluentTextField` 컴포넌트 하나로 이메일 주소 받으시고, 타입을 `TextFieldType.Email`로 해 주세요.

2024-09-06 04:15 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/NewEventDetailsComponent.razor
> +                <FluentTimePicker Id="eventStartTime" DefaultValue="00:00" />
`Id` 값은 모두 `kebab-casing` 형태로 해 주세요

2024-09-07 02:47 UTC, justinyoo commented
@KYJKY 컨플릭 해소해 주세요!

2024-09-07 05:49 UTC, justinyoo requested changes
코멘트 남겨뒀습니다.

2024-09-07 05:49 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/NewEventDetailsComponent.razor
> +                <FluentDatePicker Id="event-start-date" @bind-Value="@tempEventStartDate" />
여기 디폴트 값을 오늘 (today) 로 할 수 있나요?

2024-09-07 05:49 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/NewEventDetailsComponent.razor
> +                <FluentTimePicker Id="event-start-time" DefaultValue="00:00" />
여기는 디폴트 값을 현재 시각에서 가장 가까운 정각으로 할 수 있나요?

예) 현재 시각이 `12:34` 이면 `13:00`, 현재 시각이 `13:00` 이면 `14:00`, 현재 시각이 `14:01`이면 `15:00`, 현재 시각이 `23:59`이면 `00:00`

2024-09-07 05:49 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/NewEventDetailsComponent.razor
> +                <FluentDatePicker Id="event-end-date" @bind-Value="@tempEventEndDate" />
여기는 오늘 (today)에서 하루 지난 시점으로 기본값을 지정할 수 있나요?

2024-09-07 05:49 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/NewEventDetailsComponent.razor
> +                <FluentTimePicker Id="event-end-time" DefaultValue="00:00" />
여기는 시작시각 값이랑 동일하게 디폴트 값을 지정할 수 있나요?

2024-09-07 05:49 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/NewEventDetailsComponent.razor
> +                <FluentNumberField Id="event-max-token-cap" @bind-Value="tempEventMaxTokenCap" Required />
여기는 temp 값을 설정하는 이유가 있나요?

2024-09-07 05:49 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/NewEventDetailsComponent.razor
> +                <FluentNumberField Id="event-daily-request-cap" @bind-Value="tempEventDailyRequestCap" Required />
여기는 temp 값을 설정하는 이유가 있나요?

2024-09-07 05:49 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/NewEventDetailsComponent.razor
> +    public string? Id { get; set; }
모든 private 필드 다음으로 파라미터를 옮겨주세요.

2024-09-07 05:49 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/NewEventDetailsComponent.razor
> +            <FluentButton Id="admin-event-detail-cancel" class="button">Cancel</FluentButton>
이 버튼 두 개에 아직 이벤트 핸들러가 없습니다.

2024-09-07 05:49 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Models/AdminEventDetails.cs
이미 이 파일은 존재합니다. 굳이 다시 추가할 필요 없어요.

2024-09-07 05:49 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Models/EventDetails.cs
이미 이 파일은 존재합니다. 굳이 다시 추가할 필요 없어요.

2024-09-07 05:51 UTC, justinyoo requested changes

2024-09-07 05:51 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/NewEventDetailsComponent.razor
> +                </FluentSelect>
여기 옵션 Noda Time 라이브러리로 해결해 주세요.

2024-09-09 17:09 UTC, KYJKY commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/NewEventDetailsComponent.razor
> +                <FluentSelect Id="timezone" TOption="string" Required>
네넵 해당 사항 적용하였습니다.

2024-09-09 17:10 UTC, KYJKY commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/NewEventDetailsComponent.razor
> +                <FluentTimePicker Id="event-start-time" DefaultValue="00:00" />
해당 방법으로 디폴트 시간 설정 완료하였습니다.

2024-09-09 17:13 UTC, KYJKY commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/NewEventDetailsComponent.razor
> +                <FluentDatePicker Id="event-end-date" @bind-Value="@tempEventEndDate" />
오늘 기준 하루 뒤로 수정하였습니다.

2024-09-09 17:13 UTC, KYJKY commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/NewEventDetailsComponent.razor
> +                <FluentTimePicker Id="event-end-time" DefaultValue="00:00" />
시작값과 동일하게 설정하였습니다.

2024-09-09 17:15 UTC, KYJKY commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/NewEventDetailsComponent.razor
> +                <FluentNumberField Id="event-max-token-cap" @bind-Value="tempEventMaxTokenCap" Required />
해당 부분 초기에 오류 메시지가 발생하여서 임시로 설정하였습니다.
현재 아래와 같이 모델 데이터에 바인딩 되도록 수정하였습니다.

```html
<FluentNumberField Id="event-max-token-cap" @bind-Value="adminEventDetails.MaxTokenCap" Required />
```

2024-09-09 17:15 UTC, KYJKY commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/NewEventDetailsComponent.razor
> +                <FluentNumberField Id="event-daily-request-cap" @bind-Value="tempEventDailyRequestCap" Required />
해당 부분 초기에 오류 메시지가 발생하여서 임시로 설정하였습니다.
현재 아래와 같이 모델 데이터에 바인딩 되도록 수정하였습니다.

```html
<FluentNumberField Id="event-daily-request-cap" @bind-Value="adminEventDetails.DailyRequestCap" Required />
```

2024-09-09 17:16 UTC, KYJKY commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/NewEventDetailsComponent.razor
> +            <FluentButton Id="admin-event-detail-cancel" class="button">Cancel</FluentButton>
이벤트 핸들러 아래와 같이 추가하였습니다.

```csharp
@code{
  // .. 생략
  
  private void AddEvent()
  {
  
  }
  
  private void CancelEvent()
  {
  
  }
}
```

2024-09-09 17:19 UTC, KYJKY commented on src/AzureOpenAIProxy.PlaygroundApp/Models/AdminEventDetails.cs
엇 제가 main 브런치를 최신화해서 현재 리퀘스트 분기에 Merge 하였는데 이 경우에는 그냥 브랜치에서 두 모델 파일을 삭제해야 할까요?

2024-09-10 07:56 UTC, justinyoo requested changes
기본적으로 모든 메소드는 async/await 를 가정한다고 생각하고 작성해 주세요.

2024-09-10 07:56 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/NewEventDetailsComponent.razor
> +    private AdminEventDetails adminEventDetails;
마찬가지로 nullable 로 해 주세요

2024-09-10 07:56 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/NewEventDetailsComponent.razor
> +    }
마찬가지로 `void` 대신 `async Task ...`을 사용합니다.

2024-09-23 06:16 UTC, justinyoo requested changes

2024-09-23 06:16 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/AdminNewEvent.razor
> +<NewEventDetailsComponent Id="admin-new-event" @rendermode="InteractiveServer"></NewEventDetailsComponent>
```csharp
<NewEventDetailsComponent Id="admin-new-event" @rendermode="InteractiveServer"></NewEventDetailsComponent>
```

대신

```csharp
<NewEventDetailsComponent Id="admin-new-event" @rendermode="InteractiveServer" />
```

처럼 self-closing 형태로 해 주세요.

2024-09-23 06:16 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/NewEventDetailsComponent.razor
> +</style>
이건 별도의 scoped CSS로 뺄까요? `NewEventDetailsComponent.razor.css` 파일로 만들어 주세요.

2024-09-23 06:16 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/NewEventDetailsComponent.razor
> +        await Task.Delay(100);
굳이 이건 필요가 없습니다.

2024-09-23 06:16 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/NewEventDetailsComponent.razor
> +        DateTime currentTime = DateTime.Now;
`DateTimeOffset` 타입으로 해 주시고, `DateTimeOffset.UtcNow` 값으로 지정하세요.

2024-09-23 06:16 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/NewEventDetailsComponent.razor
> +        adminEventDetails.DateEnd = currentTime.AddDays(1).AddMinutes(-currentTime.Minute).AddHours(1);
기왕 하는 거 `AddDays.AddHours.AddMinutes` 순서가 나을 듯?

2024-09-23 06:16 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/NewEventDetailsComponent.razor
> +                    <FluentTimePicker Id="event-end-time" Value="@adminEventDetails.DateEnd.DateTime" ValueChanged="@(e => adminEventDetails.DateEnd = e.Value)" />
앞서 초기화하는 DateTimeOffset 값은 UTC 값이지만, 여기서는 Local 타임존에 맞춰서 보여줘야 합니다. 포맷은 ISO-8601 형태의 Date 값(`yyyy-MM-dd`)과 Time 값(`HH:mm`)이면 됨.

2024-09-23 06:16 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/NewEventDetailsComponent.razor
> +
여기에 `await Task.CompletedTask;` 추가해 주세요.

2024-09-23 06:16 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/Admin/NewEventDetailsComponent.razor
> +
여기에 `await Task.CompletedTask;` 추가해 주세요.

2024-10-01 16:27 UTC, KYJKY commented
현재 피드백 사항 적용 및 테스트 코드 추가 완료하였습니다!

## 질문사항
- 사용자의 브라우저 타임존을 가져오기 위해 추가한 timezone.js 파일이 있는데 해당 경로로 추가 및 명명을 커밋한 상태로 둬도 괜찮을까요?
- 사용자의 타임존을 가져오는 코드를 다른 컴포넌트에서 사용할 수 있도록 클래스로 빼는 작업이 필요할까요?
- [요소검사/타임존초기화/이벤트시작시간/이벤트종료시간] 에 대한 테스트를 추가해둔 상태인데 현재 Task에서 별도로 추가가 필요한 테스트 항목이 있을까요?

2024-10-02 08:54 UTC, justinyoo commented
@KYJKY 빌드가 깨집니다

2024-10-02 08:54 UTC, justinyoo commented
> 사용자의 브라우저 타임존을 가져오기 위해 추가한 timezone.js 파일이 있는데 해당 경로로 추가 및 명명을 커밋한 상태로 둬도 괜찮을까요?

브라우저 타임존 대신 시스템 타임존에 의존해야 합니다. timezone.js 파일은 어디서 온 건가요?

2024-10-02 08:56 UTC, justinyoo commented
> 사용자의 타임존을 가져오는 코드를 다른 컴포넌트에서 사용할 수 있도록 클래스로 빼는 작업이 필요할까요?

사용자의 타임존은 이 화면과 이벤트 업데이트하는 화면 말고는 쓸 일이 없습니다.

2024-10-02 08:57 UTC, justinyoo commented
> [요소검사/타임존초기화/이벤트시작시간/이벤트종료시간] 에 대한 테스트를 추가해둔 상태인데 현재 Task에서 별도로 추가가 필요한 테스트 항목이 있을까요?

충분한 듯 싶습니다!

2024-10-05 00:08 UTC, justinyoo commented
@KYJKY 테스트 실패합니다. 날짜 포맷 다시 확인해 보세요!

2024-10-05 05:37 UTC, justinyoo requested changes

2024-10-05 05:37 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/NewEventDetailsPageTests.cs
> +        var inputTitle = await Page.QuerySelectorAsync("#event-title");
`Page.QuerySelectorAsync` 대신 `Page.Locator`로 바꿔보세요.

2024-10-05 05:37 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/NewEventDetailsPageTests.cs
> +        await Page.WaitForSelectorAsync("#event-start-time");
`Page.Locator` 패턴으로 바꿀 수 있나요?

2024-10-05 05:37 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/NewEventDetailsPageTests.cs
> +    }
`InlineData(...)` 데코레이터를 쓰면 굉장히 테스트메소드가 간결해집니다.

2024-10-05 05:40 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/NewEventDetailsPageTests.cs
> +    }
예)

```csharp
[InlineData("event-title")]
[InlineData("event-summary")]
...
public async Task ...(string id)
{
    ...

    var element = Page.Locator($"#{id}");

    ...

    await Expect(element).ToBeVisibleAsync();
}
```

2024-10-05 07:44 UTC, KYJKY commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/NewEventDetailsPageTests.cs
> +        var inputTitle = await Page.QuerySelectorAsync("#event-title");
넵 수정하였습니다!

2024-10-05 07:45 UTC, KYJKY commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/NewEventDetailsPageTests.cs
> +        await Page.WaitForSelectorAsync("#event-start-time");
`Page.Locator("").WaitForAsync()` 형태로 수정하였습니다.

2024-10-05 07:46 UTC, KYJKY commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/NewEventDetailsPageTests.cs
> +    }
다른 테스트와 동일하게 XUnit을 사용하지 않고 InlineData 대신 TestCase를 사용하여 해당 부분을 수정하였는데 괜찮을까요?

2024-10-05 08:30 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/NewEventDetailsPageTests.cs
> +    }
오 맞네요 `TestCase` 써야 하네 ㅋ xUnit이랑 헷갈렸음. 전체적으로 다 NUnit으로 바꿔야 하나... ㅠ

2024-10-05 08:36 UTC, justinyoo requested changes

2024-10-05 08:36 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/NewEventDetailsPageTests.cs
> +    }
지금 이 테스트는 1) 엘레먼트가 제대로 로딩됐는지 보는 건가요, 2) 해당 엘레먼트에 값이 들어갔는지 보는 건가요?

만약 1)을 테스트 하는 거라면, 50-53 라인의 테스트 코드는 맞지 않는 듯?
만약 2)를 테스트하는 거라면 실제로 어떤 값을 넣고 그 값이 들어간 건지를 확인해야 합니다. 더불어 1) 과 관련한 테스트도 추가해야 합니다.

2024-10-05 08:36 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/NewEventDetailsPageTests.cs
> +        await inputTimezone.WaitForAsync();
이 라인이 필요한가요?

2024-10-05 11:24 UTC, KYJKY commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/NewEventDetailsPageTests.cs
> +    }
1)이 맞습니다. 코드 작성하다가 헷갈렸습니다..
`ToBeVisibleAsync()`로 로딩 여부를 확인하도록 수정하였습니다.

2024-10-05 11:25 UTC, KYJKY commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/NewEventDetailsPageTests.cs
> +        await inputTimezone.WaitForAsync();
앗 Timezone은 해당 라인 필요하지 않아서 삭제하였습니다!

2024-10-06 12:24 UTC, justinyoo requested changes

2024-10-06 12:24 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/AzureOpenAIProxy.PlaygroundApp.csproj
> +    <PackageReference Include="TimeZoneConverter" Version="6.1.0" />
혹시 `NodaTime` 패키지만으로 충분하지 않던가요?

2024-10-06 12:24 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/NewEventDetailsPageTests.cs
> +        await inputStartTime.WaitForAsync();
이게 여전히 필요한가요?

2024-10-06 12:24 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/NewEventDetailsPageTests.cs
> +    }
이 테스트 메소드는 Date와 Time 두 값을 하나의 메소드에서 테스트하는데, Date 값과 Time 값을 별도의 테스트 메소드로 쪼개야 하지 않을까요?

2024-10-06 12:24 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/NewEventDetailsPageTests.cs
> +        await inputEndTime.WaitForAsync();
이게 여전히 필요한가요?

2024-10-06 12:24 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/NewEventDetailsPageTests.cs
> +    }
이 테스트 역시 Date를 테스트하는 메소드와 Time을 테스트하는 메소드로 쪼개야 할 듯 합니다.

2024-10-06 18:10 UTC, KYJKY commented on src/AzureOpenAIProxy.PlaygroundApp/AzureOpenAIProxy.PlaygroundApp.csproj
> +    <PackageReference Include="TimeZoneConverter" Version="6.1.0" />
Windows OS에서 Windows 타임존으로 반환하고 있어서 해당 라이브러리를 추가했었는데 TimeZoneInfo 내부 기능으로 충분히 처리할 수 있어서 삭제하였습니다!

2024-10-06 18:10 UTC, KYJKY commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/NewEventDetailsPageTests.cs
> +        await inputStartTime.WaitForAsync();
아뇨! 필요 없어서 해당 코드 삭제 처리 했습니다.

2024-10-06 18:11 UTC, KYJKY commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/NewEventDetailsPageTests.cs
> +    }
별도의 테스트로 나눴습니다!

2024-10-06 18:12 UTC, KYJKY commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/NewEventDetailsPageTests.cs
> +        await inputEndTime.WaitForAsync();
동일하게 삭제 처리 했습니다.

2024-10-06 18:12 UTC, KYJKY commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/NewEventDetailsPageTests.cs
> +    }
동일하게 별도의 테스트로 나누었습니다!

2024-10-10 11:23 UTC, justinyoo commented
@KYJKY 테스트 깨지는 부분 main 브랜치에서 반영해 주세욥

2024-10-12 06:12 UTC, justinyoo approved these changes
LGTM! 고생하셨습니다!

2024-10-12 06:13 UTC, merged