[OpenAPI] Add endpoint for list of deployment models
aliencube/azure-openai-sdk-proxy pull request #294
Opened 2024-09-01 12:37 UTC by jihyunmoon16

- PlaygroundEndpointUrls.cs 파일에 엔드포인트 추가
- PlaygroundEndpoint.cs 파일에 openapi 명세서 추가
- Program.cs 파일에 작성한 엔드포인트 메소드 추가
- DeploymentModelsDetails.cs 클래스 생성
-이 클래스는 모델 아이디, 모델 이름, 그리고 버전 정보를 가지고 있도록 만들었습니다. (id만 필수값으로 정했어요) 

테스트 코드도 곧 추가하겠습니다!

2024-09-01 13:50 UTC, justinyoo commented
어떤 이슈에 대응하기 위한 것인가요?

2024-09-01 15:52 UTC, jihyunmoon16 commented
> 어떤 이슈에 대응하기 위한 것인가요?

#169 이 이슈입니다

2024-09-06 01:16 UTC, justinyoo requested changes
좋은데요? 우선 리뷰 코멘트 남겼구요, 이제 관련 테스트 코드도 추가해 보시지요.

2024-09-07 03:05 UTC, jihyunmoon16 commented on src/AzureOpenAIProxy.ApiApp/Endpoints/PlaygroundEndpoints.cs
> +        .Produces(statusCode: StatusCodes.Status401Unauthorized)
넵 반영했습니다

2024-09-07 03:05 UTC, jihyunmoon16 commented on src/AzureOpenAIProxy.ApiApp/Models/DeploymentModelDetails.cs
> +}
네!!

2024-09-07 05:34 UTC, justinyoo requested changes
리뷰 코멘트 남겨뒀습니다!

2024-09-07 05:34 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Endpoints/PlaygroundEndpoints.cs
> +using Microsoft.AspNetCore.Mvc;
이 `using ...` 라인이 필요한가요?

2024-09-07 05:34 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Models/DeploymentModelDetails.cs
> +    public string? Version { get; set; }
`Name` 제외하고는 모두 필요 없습니다.

```csharp
[JsonRequired]
public string Name { get; set; } = string.Empty;
```

2024-09-07 05:38 UTC, jihyunmoon16 commented on src/AzureOpenAIProxy.ApiApp/Endpoints/PlaygroundEndpoints.cs
> +using Microsoft.AspNetCore.Mvc;
[FromRoute] string eventId 여기서 [FromRoute] 를 사용하려면 필요합니다

2024-09-07 05:43 UTC, jihyunmoon16 commented on src/AzureOpenAIProxy.ApiApp/Models/DeploymentModelDetails.cs
> +    public string? Version { get; set; }
넵 반영했습니다. 요건 required라서 nullable로 하지 않는군요.

2024-09-07 06:19 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Endpoints/PlaygroundEndpoints.cs
> +using Microsoft.AspNetCore.Mvc;
오 맞네요. 데헷

2024-09-07 06:21 UTC, justinyoo requested changes

2024-09-07 06:21 UTC, justinyoo commented on test/AzureOpenAIProxy.AppHost.Tests/ApiApp/Endpoints/GetDeploymentModelsOpenApiTest.cs
> +}
응답 개체 관련 테스트를 추가해 주세요.

2024-09-07 06:21 UTC, justinyoo commented on test/AzureOpenAIProxy.AppHost.Tests/ApiApp/Endpoints/GetDeploymentModelsOpenApiTest.cs
> +    [InlineData("404")]
500 도 추가해 주세요.

2024-09-09 12:18 UTC, jihyunmoon16 commented on test/AzureOpenAIProxy.AppHost.Tests/ApiApp/Endpoints/GetDeploymentModelsOpenApiTest.cs
> +    [InlineData("404")]
네!! 반영했습니다

2024-09-09 12:21 UTC, jihyunmoon16 commented on test/AzureOpenAIProxy.AppHost.Tests/ApiApp/Endpoints/GetDeploymentModelsOpenApiTest.cs
> +}
추가했습니다! ㅎㅎ 빠진 부분이 많았네요.

2024-09-10 07:44 UTC, justinyoo requested changes

2024-09-10 07:44 UTC, justinyoo commented on test/AzureOpenAIProxy.AppHost.Tests/ApiApp/Endpoints/GetDeploymentModelsOpenApiTest.cs
> +                                         .GetProperty("DeploymentModelDetails")
이 프로퍼티들 관련 테스트는 어디에 있나요?

2024-09-10 07:44 UTC, justinyoo commented on test/AzureOpenAIProxy.AppHost.Tests/ApiApp/Endpoints/GetDeploymentModelsOpenApiTest.cs
> +        }
테스트 메소드 안에 조건문을 넣는 것은 좋지 않습니다. 조건에 맞는 것 테스트 따로, 조건에 맞지 않는 것 테스트 따로 이렇게 나눠야 해요.

2024-09-14 05:29 UTC, jihyunmoon16 commented
스웨거 화면
![image](https://github.com/user-attachments/assets/9ddd2ac2-4c64-41f2-b85d-a068a5c5e950)


DeploymentModelDetails Schema
![image](https://github.com/user-attachments/assets/10e9ae62-a9cd-4a8f-8aa0-9db7df0e482e)

2024-09-14 05:31 UTC, jihyunmoon16 commented on test/AzureOpenAIProxy.AppHost.Tests/ApiApp/Endpoints/GetDeploymentModelsOpenApiTest.cs
> +        }
네 수정해볼께요

2024-09-14 05:35 UTC, justinyoo commented
@jihyunmoon16 좋습니다! 앞에서 코드리뷰한 부분을 수정해 보면 될 듯 해요.

2024-09-14 06:36 UTC, jihyunmoon16 commented on test/AzureOpenAIProxy.AppHost.Tests/ApiApp/Endpoints/GetDeploymentModelsOpenApiTest.cs
> +                                         .GetProperty("DeploymentModelDetails")
다른 openapi 테스트 코드 참고해서 아래와 같은 테스트 추가했습니다.

![image](https://github.com/user-attachments/assets/3e33bdf1-e589-404f-bd9c-4b1a1b780d46)

1. schemas에 DeploymentModelDetails가 있는지 확인하는 테스트
2. required에 name 속성이 있는지 확인하는 테스트
3. DeploymentModelDetails에 name이란 속성이 있는지 확인하는 테스트
4. name 속성의 타입이 string이 맞는지 확인하는 테스트

2024-09-16 02:03 UTC, justinyoo requested changes
테스트 관련 코멘트 남겨뒀습니다. 아래 링크에서 유민경님께서 고민한 부분을 함께 고민해 보세요.

- #313

2024-09-16 02:03 UTC, justinyoo commented on test/AzureOpenAIProxy.AppHost.Tests/ApiApp/Endpoints/GetDeploymentModelsOpenApiTest.cs
> +    public async Task Given_Resource_When_Invoked_Endpoint_Then_It_Should_Return_Type(string attribute, bool isRequired, string type)
`isRequired`라는 파라미터는 이 테스트에서 안 쓰였던데 굳이 추가할 필요가 없습니다. 테스트 데이터를 `MemberData`에서 `InlineData`로 바꿔보세요. 그러면 불필요한 테스트 데이터를 추가할 일이 없어집니다.

2024-09-16 02:03 UTC, justinyoo commented on test/AzureOpenAIProxy.AppHost.Tests/ApiApp/Endpoints/GetDeploymentModelsOpenApiTest.cs
> +    public async Task Given_Resource_When_Invoked_Endpoint_Then_It_Should_Return_Property(string attribute, bool isRequired, string type)
`isRequired`, `type` 파라미터는 이 테스트에서 안 쓰였던데 굳이 추가할 필요가 없습니다. 테스트 데이터를 `MemberData`에서 `InlineData`로 바꿔보세요. 그러면 불필요한 테스트 데이터를 추가할 일이 없어집니다.

2024-09-17 13:59 UTC, jihyunmoon16 commented on test/AzureOpenAIProxy.AppHost.Tests/ApiApp/Endpoints/GetDeploymentModelsOpenApiTest.cs
> +    [MemberData(nameof(DeploymentModelAttributeData))]
#307 참고해서 수정했습니다. MemberData로 써야 한다고 생각했는데 인라인데이터를 쓰니까 코드가 깔끔해졌어요!

2024-09-18 03:55 UTC, justinyoo approved these changes
수고하셨습니다! LGTM!

2024-09-18 03:55 UTC, merged