[Chat Completions] Response payload definition #22 (backup)
aliencube/azure-openai-sdk-proxy pull request #298
Opened 2024-09-02 00:15 UTC by jhmin99

Related to #22 

백업하였습니다!

# 수정사항 
- ChatCompletionSchemasOpenApiTests에서 다른 Apphost tests들과 마찬가지로
        `await host.ResourceNotificationService.WaitForResourceAsync("apiapp", KnownResourceStates.Running).WaitAsync(TimeSpan.FromSeconds(30));` 를 추가하였습니다.

history : #237

2024-09-03 08:05 UTC, justinyoo requested changes
마지막 주석 다는 작업만 하면 끝날 것 같습니다!

2024-09-03 08:05 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Converters/EnumMemberConverter.cs
> +public class EnumMemberConverter<T> : JsonConverter<T> where T : Enum
클래스에 주석을 달아 주세요. 예)

```csharp
/// <summary>
/// This represents the converter entity for <see cref="EnumMember" />.
/// </summary>
```

2024-09-03 08:05 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Converters/EnumMemberConverter.cs
> +    public override T Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
여기에도 주석을 달아주세요. 예) `/// <inheritdoc />`

2024-09-03 08:05 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Converters/EnumMemberConverter.cs
> +    public override void Write(Utf8JsonWriter writer, T value, JsonSerializerOptions options)
여기에도 주석을 달아주세요. 예) /// <inheritdoc />

2024-09-03 08:05 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Endpoints/ProxyChatCompletionsEndpoint.cs
> +        //.Produces<ChatCompletion>(statusCode: StatusCodes.Status200OK, contentType: "application/json")
이 주석은 더이상 필요 없습니다.

2024-09-03 08:05 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Models/CreateChatCompletionResponse.cs
> +    [JsonPropertyName("id"), Required]
모든 프로퍼티에 대해 OpenAPI 문서에 있는대로 주석을 달아 주세요. 예)

```csharp
/// <summary>
/// Gets or sets a unique identifier for the chat completion.
/// </summary>
```

2024-09-04 01:19 UTC, jhmin99 commented
모든 프로퍼티에 OpenAPI 문서에 있는대로 주석을 달고, description이 없는 경우에는 최소한의 설명을 추가하여 작성하였습니다.

2024-09-05 23:34 UTC, justinyoo requested changes
마지막 knit picking 입니다!

2024-09-05 23:34 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Models/CreateChatCompletionResponse.cs
> +/// For more information, see <a href="https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/data-plane/AzureOpenAI/inference/stable/2024-06-01/inference.json">azure
이 내용은 `<remark>` 태그로 작성해 주시면 됩니다.

2024-09-05 23:34 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Converters/EnumMemberConverter.cs
> +/// <summary>
요 사이에 한 줄 넣어 주세요.

2024-09-05 23:34 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Models/CreateChatCompletionResponse.cs
> +    /// <summary>
요 사이에 한 줄 넣어 주세요. 다른 곳들 중 빈 줄 안 들어간 곳 있으면 모두 찾아서 넣어주세요.

2024-09-06 07:34 UTC, jhmin99 commented
> 마지막 knit picking 입니다!

수정하였습니다!

2024-09-07 02:46 UTC, justinyoo requested changes
하나만 더!

2024-09-07 02:46 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Models/CreateChatCompletionResponse.cs
> +/// For more information, see <a href="https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/data-plane/AzureOpenAI/inference/stable/2024-06-01/inference.json">azure
요런 식으로...

```xml
<summary>
The response from creating a chat completion.
</summary>
<remark>
For more information, ...
</remark>
```

2024-09-07 04:11 UTC, justinyoo approved these changes
고생하셨습니다! LGTM!

2024-09-07 04:12 UTC, merged