[Backend API] Table Storage Connection Setting
aliencube/azure-openai-sdk-proxy pull request #299
Opened 2024-09-03 17:00 UTC by sikutisa

* Related to: #208 #213 
* 해당 이슈들을 해결하기 앞서 필요한 선행 작업입니다. 
---
## Description
* Azure Table Storage를 사용하려면 `TableServiceClient` 클래스가 필요한 것으로 이해했습니다.
  * https://learn.microsoft.com/en-us/dotnet/api/azure.data.tables.tableserviceclient?view=azure-dotnet
* @tae0y 님이 #281 에서 작업하셨던 부분 중, appsettings.json에 추가한 속성들을 읽어와서 의존성 주입하는 코드를 ServiceCollectionExtensions에 추가했습니다.

## Discussion
* ContainerName
  * #281 작업 내역에 ContainerName 이란 속성이 있었는데, TableServiceClient 생성에 사용되지 않는 속성 같습니다. 해당 속성이 필요한 이유가 있을까요?
* ConnectionString
  *  `public TableServiceClient (string connectionString);` 생성자를 사용했는데, 다른 생성자를 사용하는 것이 적절한지에 대해 논의할 필요가 있을 것 같습니다.
  * ConnectionString을 단일 문자열로 관리하기 보단 아래 항목들을 별도로 관리하고, 코드 상에서 한 문자열로 변환해 사용하는 것이 더 좋을 것 같은데 어떻게 생각하시나요?
    * DefaultEndpointsProtocoㅣ
    * EndpointSuffix
    * AccountName
    * AccountKey
    * BlobEndpoint
    * FileEndpoint
    * QueueEndpoint
    * TableEndpoint
* 현재 진행 상황에서 추가적으로 진행해야 하는 부분에 대해 피드백을 받고 싶습니다.

## Reference
https://learn.microsoft.com/en-us/connectors/azuretables/#connect-to-azure-table-storage-connector-using-table-endpoint
https://learn.microsoft.com/en-us/azure/storage/common/storage-configure-connection-string

2024-09-05 23:12 UTC, justinyoo commented
bicep 리뷰 코멘트 남겨뒀는데요, 커넥션 스트링을 키볼트에서 가져온다고 가정해 보시면 좋겠습니다: https://github.com/aliencube/azure-openai-sdk-proxy/pull/292#pullrequestreview-2284211213

2024-09-05 23:19 UTC, justinyoo commented
#300 태스크 생성해 뒀으니 거기서 코멘트 하나만 남겨주세요 @sikutisa

2024-09-06 02:45 UTC, sikutisa commented
> bicep 리뷰 코멘트 남겨뒀는데요, 커넥션 스트링을 키볼트에서 가져온다고 가정해 보시면 좋겠습니다: [#292 (review)](https://github.com/aliencube/azure-openai-sdk-proxy/pull/292#pullrequestreview-2284211213)

해당 리뷰 확인해서 키볼트에서 가져오는 방식으로 변경해보겠습니다.

2024-09-07 09:57 UTC, sikutisa commented
@justinyoo 
현재 문제가 되는 테스트 코드는 아래와 같습니다. (`ServiceCollectionExtensionsTests.cs`의 110라인 입니다.)

```cs
    [Theory]
    [InlineData("http://localhost", default(string))]
    [InlineData("http://localhost", "")]
    public void Given_NullOrEmpty_SecretName_When_Invoked_AddKeyVaultService_Then_It_Should_Throw_Exception(string vaultUri, string? secretName)
    {
        // Arrange
        var services = new ServiceCollection();
        var dict = new Dictionary<string, string>()
        {
            { "Azure:KeyVault:VaultUri", vaultUri },
            { "Azure:KeyVault:SecretNames:OpenAI", secretName! },
        };
#pragma warning disable CS8620 // Argument cannot be used for parameter due to differences in the nullability of reference types.
        var config = new ConfigurationBuilder().AddInMemoryCollection(dict).Build();
#pragma warning restore CS8620 // Argument cannot be used for parameter due to differences in the nullability of reference types.
        services.AddSingleton<IConfiguration>(config);
        services.AddKeyVaultService();

        // Act
        Action action = () => services.BuildServiceProvider().GetService<SecretClient>();

        // Assert
        action.Should().Throw<InvalidOperationException>();
    }
```

두 시나리오 중 첫번째 시나리오인 `[InlineData("http://localhost", default(string))]`에서 `System.Collections.Generic.KeyNotFoundException`가 발생하고 있습니다. 하지만 디버그 모드로 확인해봤을 때에는 일단 config 변수까지는 키가 정상적으로 추가되는 것으로 보입니다.
![스크린샷 2024-09-07 181512](https://github.com/user-attachments/assets/dde3a2a5-9050-46df-943e-d7ee605b2bf6)

그래서 추측컨데, 현재 AddKeyVaultService 함수에서 설정값을 객체에 바인드할 때 값이 null이면 Dictionary 객체 바인드가 제대로 동작하지 않고 있는 것 같습니다.

2024-09-10 07:32 UTC, justinyoo requested changes

2024-09-11 13:40 UTC, sikutisa commented on test/AzureOpenAIProxy.ApiApp.Tests/Extensions/ServiceCollectionExtensionsTests.cs
> +            { "Azure:KeyVault:SecretNames:OpenAI", secretName! },
하긴 올바르지 않은 케이스에서 익셉션이 발생하는가가 더 중요하겠네요. 🤣

2024-09-11 14:19 UTC, sikutisa commented on src/AzureOpenAIProxy.ApiApp/Configurations/KeyVaultSettings.cs
> +    public IDictionary<string, string> SecretNames { get; set; } = new Dictionary<string, string>();
이 부분은 현재 `public Dictionary<string, string> SecretNames { get; set; } = [];`로 변경됐습니다.

2024-09-11 14:19 UTC, sikutisa commented on test/AzureOpenAIProxy.ApiApp.Tests/Extensions/ServiceCollectionExtensionsTests.cs
> +            { "Azure:KeyVault:SecretNames:OpenAI", secretName! },
반영해서 수정했습니다.

2024-09-12 04:58 UTC, justinyoo requested changes

2024-09-12 04:58 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Extensions/ServiceCollectionExtensions.cs
> +    }
좋습니다! 이 메소드에 대한 테스트 코드도 만들어 볼 수 있나요?

2024-09-12 15:28 UTC, justinyoo approved these changes
LGTM! 고생하셨습니다!

2024-09-12 15:28 UTC, merged