[Playground] Add Events components
aliencube/azure-openai-sdk-proxy pull request #311
Opened 2024-09-07 06:44 UTC by Capella87

Resolves: #181 

![image](https://github.com/user-attachments/assets/695b2c48-583b-4256-bde2-cad473c25c84)

## Description
* ```/events/``` 경로 아래에 Events 페이지 추가
* 최대 4개의 로그인한 유저가 참여한 이벤트를 보여주는 Grid 기반의 EventListComponent 추가
* 이벤트 제목과 summary를 보여주는 이벤트 컴포넌트인 EventItemComponent 추가

## Tasks
- [ ] 테스트 코드

## 궁금한 점
* Playwright로 프론트앤드의 어떤 것을 테스트 할 수 있나요?
* 컴포넌트를 구현하는 과정에서 CSS를 많이 사용했는데 style property가 너무 길어져서 별도의 CSS에 옮기는 게 나을까요?

테스트 코드는 아직 미완성입니다.

2024-09-08 08:28 UTC, Capella87 commented
테스트 부분도 구현했습니다.
## 추가 변경점
### 테스트
* 유저에게 보여지는 event item이 4개를 넘지 않는지 검증
* EventListComponent가 Events 컴포넌트에서 제대로 로드되었는지 검증

### 기능
* 추가적으로 사용자가 현재 참여하는 이벤트가 없을 경우 참여한 이벤트가 없다는 메시지를 출력
* 로드할 때 Progressbar ring 추가

2024-09-10 04:34 UTC, justinyoo requested changes
코드에 생각이 너무 많은 것 같아요. 단순하게 볼 수 있는 방법이 있을 겁니다.

2024-09-10 04:34 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventItemComponent.razor
> +    public Guid Id { get; set; }
다른 컴포넌트에 맞춰서 여기 ID 값도 수정해 주세요. ID 타입은 `string?` 입니다.

2024-09-10 04:34 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventItemComponent.razor
> +    public string Title { get; set; }
`string?`

2024-09-10 04:34 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/Events.razor
> +@rendermode InteractiveServer
`@rendermode ...` 라인 필요 없습니다.

2024-09-10 04:34 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventItemComponent.razor
> +                @onclick="NavigateToEventDetails">
4번 줄과 5번 줄을 굳이 줄바꿈한 이유가 있나요?

2024-09-10 04:34 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventItemComponent.razor
> +@inject IOpenAIApiClient Api
이 두 라인은 현재 사용하지 않는데 추가한 이유가 있나요?

2024-09-10 04:34 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventItemComponent.razor
> +    }
이건 무슨 용도로 쓰는 함수인가요? 이 대신 `OnInitializedAsync()` 쓰면 안되나요? 아니면, 굳이 이 메소드가 필요한가요?

2024-09-10 04:34 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventItemComponent.razor
> +    }
이 메소드는 사용하지 않는데 굳이 정의한 이유가 있나요?

2024-09-10 04:34 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventListComponent.razor
> +    }
`if ... else ...` 구문이 너무 복잡합니다. 단순화시킬 수 있는 방법을 찾아보세요.

2024-09-10 04:34 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventListComponent.razor
> +    }
제가 디스코드에 공유한 문서를 보면 `public`, `protected`, `internal`, `private` 메소드들의 정렬 순서가 있습니다. 확인해 보세요.

2024-09-10 04:34 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Properties/launchSettings.json
이 파일은 건드릴 필요가 없는데, 수정한 이유가 있나요?

2024-09-10 08:46 UTC, Capella87 commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventItemComponent.razor
> +    }
이벤트 카드를 누르면 해당 이벤트의 정보를 보여주는 사이트를 띄우게 하려고 만들었습니다.

2024-09-11 10:24 UTC, justinyoo requested changes

2024-09-11 10:24 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/Pages/Events.razor
> +<EventListComponent Id="events-list" @rendermode="InteractiveServer" />
Id 값으로 `events-list`라고 하기에는 복수형 + 리스트라서 동어반복 같아요. `events` 또는 `event-list` 또는 `list-of-events` 중에 하나 골라 보세요.

2024-09-11 10:24 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventItemComponent.razor
근본적으로 이 컴포넌트가 필요한가요? 그냥 `EventListComponent.razor` 안에서 `FluentGridItem` 컴포넌트 부르면 될 것 같은데?

2024-09-11 10:24 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventItemComponent.razor
> +    }
- 만약 살리려면 `async Task`로 살려주세요.
- 그리드 전체를 clickable 하게 만드는 게 나을지 아니면 헤더 텍스트를 링크로 만드는 게 나을지 어떻게 생각하세요?

2024-09-11 10:24 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventItemComponent.razor
> +        </FluentHeader>
`FluentHeader` 컴포넌트의 용도가 이상합니다. 여기에 쓰는 컴포넌트가 맞나요? 오히려 Label이 더 맞을 것 같은데...

https://www.fluentui-blazor.net/Label

한 번 고민 좀 해 보실래요?

2024-09-11 10:24 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventListComponent.razor
> +            </FluentGridItem>
이 구조랑 `EventItemComponent.razor`에 정의한 `FluentGridItem` 구조가 맞질 않아요. 일관성을 한 번 유지시켜 보시지요.

2024-09-11 10:24 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventListComponent.razor
> +    private List<EventDetails>? _events;
얘는 private 필드니까 가장 먼저 나와야겠지요? 제가 디스코드에서 공유한 코딩 가이드라인 한 번 찬찬히 잘 읽어보세요.

2024-09-11 10:24 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventListComponent.razor
> +    private Task<List<EventDetails>> CreateEventDetailsAsync()
`async` 빠졌습니다.

2024-09-11 10:24 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Properties/launchSettings.json
파일 자체를 변경할 필요가 없어요. 이런 변경사항 자체가 나오면 안됩니다.

2024-09-12 04:32 UTC, Capella87 commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventItemComponent.razor
> +        </FluentHeader>
처음에 시범삼아서 넣었는데 의외로 맞아서 그냥 두었는데요, 컴포넌트 설명에서도 페이지나 애플리케이션의 맨 위에서 사용하라고 나오네요. 제가 번지수를 잘못 찾았네요.

Label 컴포넌트 문서를 참조해보니 ```EmailHeader``` 라벨은 너무 큰 것 같고, 그냥 ```Header``` 라벨은 너무 작습니다. ```PaneHeader``` 정도면 적당한 크기 같은데 어떠신가요?
![image](https://github.com/user-attachments/assets/59f5ed51-662b-4b44-b2c3-9d1e4f3ec1cb)

2024-09-12 04:50 UTC, Capella87 commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventListComponent.razor
> +            </FluentGridItem>
일관성이 없다는 구조가, ```FluentCard```를 사용하지 않고 만든 구조인 건가요?

2024-09-12 04:52 UTC, Capella87 commented on src/AzureOpenAIProxy.PlaygroundApp/Properties/launchSettings.json
확인해보니 마지막줄에 또 개행 문자가 들어갔네요... 수정하겠습니다!

2024-09-12 05:36 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventItemComponent.razor
> +        </FluentHeader>
저도 `PaneHeader` 쯤이 적당해 보입니다

2024-09-12 05:37 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventListComponent.razor
> +            </FluentGridItem>
ㅇㅇ 기왕이면 다 같이 `FluentCard` 형태를 가져가면 좋을 듯 싶습니다.

2024-09-13 05:14 UTC, Capella87 commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventItemComponent.razor
> +        </FluentHeader>
위 clickable에 대해서 생각을 해보고 여러 예시를 찾아봤습니다.
UI 디자인에 대해 알려주는 UI Tips에 [따르면](https://www.uidesign.tips/ui-tips/make-cards-look-clickable-vol-2) 사용자의 상상에 맡겨서는 안된다면서 클릭할 수 있다는 점과 어떤 역할을 하는 것인지 사용자에게 보여줄 수 있게 버튼을 추가하라고 했습니다.

버튼을 넣지 않고 헤더만 clickable하게 하는 것 보다 summary 아래에 'details' 나 'more' 버튼을 넣고 전체를 clickable하게 설계하거나, 버튼 대신 헤더 Title에 HTML의 일반 링크처럼 밑줄을 긋는 방식으로, 최소한 '누르면 자세한 정보를 보여준다'라는 것을 어필할 수 있게 하면 더 직관적인 설계가 될 것 같습니다.

저는 clickable로 하되, details 라는 작은 버튼을 아래에 추가하는 방향으로 가면 좋을 것 같습니다. 어떻게 생각하시나요?

2024-09-13 07:57 UTC, Capella87 commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventItemComponent.razor
> +    }
위 clickable에 대해서 생각을 해보고 여러 예시를 찾아봤습니다.
UI 디자인에 대해 알려주는 UI Tips에 [따르면](https://www.uidesign.tips/ui-tips/make-cards-look-clickable-vol-2) 사용자의 상상에 맡겨서는 안된다면서 클릭할 수 있다는 점과 어떤 역할을 하는 것인지 사용자에게 보여줄 수 있게 버튼을 추가하라고 했습니다.

버튼을 넣지 않고 헤더만 clickable하게 하는 것 보다 summary 아래에 'details' 나 'more' 버튼을 넣고 전체를 clickable하게 설계하거나, 버튼 대신 헤더 Title에 HTML의 일반 링크처럼 밑줄을 긋는 방식으로, 최소한 '누르면 자세한 정보를 보여준다'라는 것을 어필할 수 있게 하면 더 직관적인 설계가 될 것 같습니다.

저는 clickable로 하되, details 라는 작은 버튼을 아래에 추가하는 방향으로 가면 좋을 것 같습니다. 어떻게 생각하시나요?

2024-09-13 08:02 UTC, Capella87 commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventListComponent.razor
> +            </FluentGridItem>
구현했습니다!
![image](https://github.com/user-attachments/assets/7b701cba-d6d5-45cb-9191-d09b155e8672)
```FluentCard```에서 ```MinimalStyle```을 이용해서 기본 CSS 설정을 꺼도 ```box-shadow```와 ```border```는 따로 설정을 ```!important```까지 해줘야 완전히 안 보이게 나왔습니다.

2024-09-13 12:37 UTC, justinyoo requested changes
계속해서 얘기하는 거지만, 자꾸 뭔가를 복잡하게 생각하는 것 같아요. 최대한 단순하게 생각해 보세요. 뭔가 더 필요한 것 같다고 생각하면 별도로 이슈를 생성하고 거기서 논의하는 식으로 해 보세요.

2024-09-13 12:37 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventItemComponent.razor
> +﻿<FluentGridItem Id="@Id" xs="12" sm="6" Justify="JustifyContent.Center" Style="text-align: center;" @onclick="NavigateToEventDetails">
여전히 이 `@onclick` 이벤트핸들러의 의미를 알 수 없습니다.

2024-09-13 12:37 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventItemComponent.razor
> +        </FluentHeader>
이거 다른 것으로 교체하자고 했던 것 같은데?

2024-09-13 12:37 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventItemComponent.razor
> +    }
앞서도 얘기했지만, 이 이벤트 핸들러의 용도를 아직도 모르겠습니다. 그냥 `Title` 값에 링크 걸면 안되나요? 나머지는 굳이 고민하고 자시고 할 게 있나?

2024-09-13 12:37 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventListComponent.razor
> +        }
이게 무슨 로직인가요? 전에보다 로직이 더 꼬인 것 같은데?

2024-09-13 12:37 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventListComponent.razor
> +    }
이 자체가 필요없지 않나요? 그냥 이걸

```csharp
@if (_events == null || _events.Any() == false)
{
    // 보여줄 게 없는 경우 화면 렌더링 로직
}
else
{
    foreach (var ev in _events)
    {
        // 이벤트 아이템 뿌려주는 로직
    }
}
```

이게 제일 깔끔하지 않아요?

2024-09-13 12:37 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventListComponent.razor
> +    }
이거 `protected` 메소드는 `private` 메소드 보다 먼저 위치시키세요.

2024-09-14 13:50 UTC, Capella87 commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventListComponent.razor
> +    }
```_events```가 ```null```일때는 로딩 중인 경우라고 가정했고, ```_events.Count == 0```인 경우는 로딩을 한 후 이벤트가 없는 경우로 가정했습니다.

"그냥 이벤트가 없거나 로딩 중입니다" 이렇게만 남기는 게 나으려나요?

2024-09-14 13:51 UTC, Capella87 commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventListComponent.razor
> +    }
완료했습니다.

2024-09-14 13:52 UTC, Capella87 commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventItemComponent.razor
> +    }
해당 메소드와 ```onclick``` 대신 ```FluentNavLink```를 이용하여 링크를 만들었습니다.

2024-09-16 01:55 UTC, justinyoo requested changes

2024-09-16 01:55 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventListComponent.razor
> +    private List<EventDetails>? _events = null;
- 이미 `List<EventDetails>?`라고 nullable 로 표현했기 때문에 굳이 `= null;`을 추가할 필요가 없습니다.
- 다른 UI 컴포넌트와 마찬가지로 `_events` 대신 `events`로 통일할까요?

2024-09-16 01:55 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventListComponent.razor
> +        </FluentGridItem>
이것도 `EventItemCompnent` 쪽에서 해결할 수 있나요?

2024-09-16 01:55 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventListComponent.razor
> +    }
지금 딱 이벤트 네 개일 경우만 렌더링하게 되어 있는데요, 그렇다면 이벤트가 1-3개일 땐 어떻게 보이나요? 만약 이벤트가 5개 이상일 땐 어떻게 보이나요?

2024-09-19 04:46 UTC, Capella87 commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventListComponent.razor
> +    }
이벤트가 5개 이상인 경우 Linq를 통해 ```events```에서 앞 4개만 가져오게 수정했습니다.

2024-09-19 04:48 UTC, Capella87 commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventListComponent.razor
> +    private List<EventDetails>? _events = null;
통일했습니다.

2024-09-19 04:51 UTC, Capella87 commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventListComponent.razor
> +        </FluentGridItem>
일반 이벤트를 보여주는 경우와 이벤트가 없다고 보여주는 부분의 CSS 값과 내부 구조가 상이합니다.

2024-09-20 07:54 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventListComponent.razor
> +        </FluentGridItem>
내부구조가 다를 일이 있나요? 그렇다면 디자인이 뭔가 이상하다는 건데... 단지 보여주는 방식이 다를 뿐이지 내부 구조가 다를 일은 아니라고 생각합니다.

2024-09-20 07:59 UTC, justinyoo requested changes

2024-09-20 07:59 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventListComponent.razor
> +        @foreach (var e in entries)
이 부분을 하나로 합칠 수 있지 않을까요?

```csharp
@foreach (var e in entries.Take(4))
```

2024-09-20 07:59 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventListComponent.razor
> +        var entries = events.Take(4);
만약에 이벤트가 항목이 1-3개라면 여기서 에러가 나는지 확인해 보셨나요?

2024-09-20 14:57 UTC, Capella87 commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventListComponent.razor
> +        var entries = events.Take(4);
![image](https://github.com/user-attachments/assets/cf45b736-1d36-4341-9936-eb209eae95b4)

아무 이상 없었습니다. 테스트 코드에서도 5개 이상인지 assert하는 부분이 있습니다.

2024-09-20 15:16 UTC, Capella87 commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventListComponent.razor
> +        </FluentGridItem>
일반 이벤트 카드는 ```FluentCard``` 안에서 헤더와 summary 두 부분으로 이루어져 있고, "이벤트 없음 카드"는 헤더가 필요 없기 때문에 한 부분으로 되어 있습니다. 
```razor
    <FluentCard Id="event-title" Style="flex-grow: 1; padding: 0em; display: flex; flex-direction: column; align-items: normal;">
        <FluentNavLink Id="event-details-link" Href="@($"/events/{Id}")" Style="flex-grow: 0; align-self: center;">
            <FluentLabel Typo="Typography.PaneHeader" Style="margin-block: 0.5em;">
                    @Title
            </FluentLabel>
        </FluentNavLink>
        <div id="event-summary" class="card border" style="background-color: var(--neutral-layer-2); padding: 1em; padding-inline: 1.5em; flex-grow: 1">
            <div class="card-body">
                <h5>@Summary</h5>
            </div>
        </div>
    </FluentCard>
```
그런데 "없음" 카드는 이렇게 되어 있습니다.
```razor
        <FluentGridItem Id="no-events" xs="12" sm="12" Justify="JustifyContent.Center" Style="text-align: center; flex-grow: 1;">
            <FluentCard MinimalStyle="true" Style="flex-grow: 1; background-color: var(--neutral-layer-2); display: flex; padding: 0em; flex-direction: row; align-items: center; align-content: center; justify-content: center; background-color: transparent; box-shadow: none !important; border: hidden;">
                <FluentLabel Typo="Typography.Header">You don’t have any events you have participated in now.</FluentLabel>
            </FluentCard>
        </FluentGridItem>
```
이 부분을 렌더링하면 다음과 같이 나옵니다.
![image](https://github.com/user-attachments/assets/82e8e6b2-6e2a-4019-bf5c-c712d8cc46d5)
실제로는 카드로 되어 있지만 위의 CSS 옵션으로 투명하게 만들어서 그렇지 않게 보입니다. "없음" 문구만 보여주기 때문에 헤더를 넣을 필요가 없습니다.

그렇다면, "없음" 문구를 띄울 때 구현 방법을 바꾸는 게 나을까요? (예: 오버레이 구현)

2024-09-23 06:05 UTC, justinyoo requested changes

2024-09-23 06:05 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventListComponent.razor
> +        @foreach (var e in events.Take(4))
그러니까, 여기가 실제로 이벤트 갯수가 3개라고 해도 `.Take(4)`를 하는데 에러가 없다는 말 맞죠?

2024-09-23 06:05 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventItemComponent.razor
> +    public int ColumnBreakpoint { get; set; } = 6;
이 파라미터는 무엇이며, 이 값이 디폴트로 6인 이유는 무엇인가요?

---

그리드 시스템에서 그리드의 크기를 가리키는 것 같은데, 굳이 이걸 파라미터로 받을 필요가 있나요? 그냥 그리드에 찍으면 될텐데?

2024-09-23 06:05 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventItemComponent.razor
> +﻿<FluentGridItem Id="@Id" xl="@ColumnBreakpoint" xxl="@ColumnBreakpoint" Justify="JustifyContent.Center" Style="text-align: center;">
그리드 사이즈를 지금 xl, xxl만 해 뒀는데, 다른 것도 다 고려해야 하지 않을까요?

2024-09-23 11:31 UTC, Capella87 commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventItemComponent.razor
> +    public int ColumnBreakpoint { get; set; } = 6;
확인해보니 파라미터로 받을 필요가 없어 그냥 그리드에 찍는 것으로 수정했습니다.

2024-09-23 11:39 UTC, Capella87 commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventItemComponent.razor
> +    public int ColumnBreakpoint { get; set; } = 6;
flex를 적용해 다양한 시도를 하다가 들어갔었습니다.

2024-09-23 11:39 UTC, Capella87 commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventItemComponent.razor
> +﻿<FluentGridItem Id="@Id" xl="@ColumnBreakpoint" xxl="@ColumnBreakpoint" Justify="JustifyContent.Center" Style="text-align: center;">
```sm``` (600px 미만)에서는 한 열(列)에 보이게, ```xl``` (2560px 미만)는 2행 2열로, ```xxl``` (2560px 이상)에서는 한 행(行)에 4개가 보이도록 브레이크포인트를 수정했습니다. 또한 Grid의 Justification을 center로 바꾸니 이벤트가 없을 때 보여주는 메시지도 가운데에 딱 나오게 되었습니다.

2024-09-23 11:41 UTC, Capella87 commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventListComponent.razor
> +        @foreach (var e in events.Take(4))
네. 아무런 이상이 없었습니다. [LINQ](https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.take?view=net-8.0) 문서에서도 가져와야 할 개수보다 적으면 전체를 가져온다고 나와 있었습니다.

2024-09-23 11:43 UTC, Capella87 commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventItemComponent.razor
> +﻿<FluentGridItem Id="@Id" xl="@ColumnBreakpoint" xxl="@ColumnBreakpoint" Justify="JustifyContent.Center" Style="text-align: center;">
그래서 이벤트가 3개일 경우에는 세 번째 이벤트가 두번째 행에서 가운데에 나오게 되었습니다.

2024-09-23 15:08 UTC, Capella87 commented
헤더, summary 존재여부와 클릭 가능 여부를 테스트하는 코드도 추가했습니다.

2024-10-02 08:51 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventItemComponent.razor
> +﻿<FluentGridItem Id="@Id" xl="@ColumnBreakpoint" xxl="@ColumnBreakpoint" Justify="JustifyContent.Center" Style="text-align: center;">
> 그래서 이벤트가 3개일 경우에는 세 번째 이벤트가 두번째 행에서 가운데에 나오게 되었습니다.

엇 이렇게 되면 안될 것 같은데요? 그냥 왼쪽으로 붙이는 게 낫지 않겠어요?

2024-10-02 08:52 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventItemComponent.razor
> +﻿<FluentGridItem Id="@Id" xl="@ColumnBreakpoint" xxl="@ColumnBreakpoint" Justify="JustifyContent.Center" Style="text-align: center;">
@Capella87 👆

2024-10-02 13:08 UTC, Capella87 commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventItemComponent.razor
> +﻿<FluentGridItem Id="@Id" xl="@ColumnBreakpoint" xxl="@ColumnBreakpoint" Justify="JustifyContent.Center" Style="text-align: center;">
수정했습니다. Grid의 Justify를 FlexStart로 수정하니 자연스럽게 배열되네요.

2024-10-03 00:51 UTC, justinyoo requested changes

2024-10-03 00:51 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventListComponent.razor
> +                padding-inline: 1.0em; align-items: center; margin-top: 18px; border-radius: 8px;">
아무리 봐도 이 인라인스타일이 좀 걸리는데... 혹시 이거 scoped CSS로 뺄 수 있나요? 인라인 스타일은 뭐랄까 간단한 거 한두개 정도면 괜찮지 싶은데, 이건 너무 복잡한 구성이 인라인 스타일로 들어가서... 이건 별도의 Scoped CSS로 빼는 게 맞는 것 같아요.

2024-10-03 00:51 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventItemComponent.razor
> +        <FluentCard Class="event" MinimalStyle="true" Style="flex-grow: 1; display: flex; padding: 0em; flex-direction: column; align-items: normal; align-content: center; justify-content: center;">
마찬가지로 여기에 작성한 인라인 스타일도 Scoped CSS로 빼면 어떨까 싶습니다.

2024-10-03 00:51 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventItemComponent.razor
> +            <div class="event-summary card border" style="background-color: var(--neutral-layer-2); padding: 1em; padding-inline: 1.5em; flex-grow: 1">
여기도 마찬가지

2024-10-03 00:51 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventItemComponent.razor
> +    public string? Summary { get; set; }
이 밑에 파라미터로 `HasNoEvent` 같은 걸 추가하면 어때요? 그리고 그 플래그를 바탕으로 렌더링을 하는 게 좀 더 의미적으로 맞지 않나 생각합니다. 지금은 `Id` 값 기준으로 처리하잖아요? ID 값은 그런 용도가 아니다보니 이게 계속 목엣가시처럼 걸리네...

```csharp
[Parameter]
public bool HasNoEvent { get; set; }
```

이렇게 해두면 기본값이 `false`이니까, 이벤트가 없을 경우에만 `true`로 처리하면 될 듯?

2024-10-07 11:15 UTC, Capella87 commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/EventItemComponent.razor
> +    public string? Summary { get; set; }
parameter를 추가하는 방향으로 구현했습니다.

2024-10-10 11:35 UTC, justinyoo approved these changes
고생하셨습니다! LGTM!

2024-10-10 11:36 UTC, merged