[Playground] System Message Tab: UI Component only #289
aliencube/azure-openai-sdk-proxy pull request #312
Opened 2024-09-07 14:08 UTC by yjchun626

# 개요
- #289 
- 목표:
     - Playground 페이지의 System Message Tab에 사용될 컴포넌트(FluentButton, FluentTextArea 혼합) 구현

# 구현한 내용
## 1. `SystemMessageTabComponent.razor` 생성
- PlaygroundApp 프로젝트 내 `Components/UI/SystemMessageTabComponent.razor` 추가
     - `FluentButton` -> 'Apply changes', 'Reset to default' 버튼 생성
     - `FluentTextArea` -> System message 작성하는 textarea 생성
- 이후 `Tests.razor`에 컴포넌트 추가하여 작동 확인하였습니다.
### 초기 화면
![image](https://github.com/user-attachments/assets/7e83beca-9406-4c0c-8e6d-e378bf3719c4)

## 2. System message - TextArea 상태 및 버튼 클릭에 따른 간단한 로직 구현
- 초기: 
     - default 값 `You are an AI assistant that helps people find information.`으로 설정됨
     - 위의 'Apply changes', 'Reset to default' 버튼 모두 비활성화된 상태
- System message의 textarea 값 변경 감지: 위의 'Apply changes', 'Reset to default' 버튼 모두 활성화됨
     - 'Apply changes' 버튼 눌러야 새로운 textarea 값이 System message 값으로 적용됨 -> 이후 Apply 버튼은 다시 textarea 값 변경 전까지 비활성화
     -  'Reset to default' 버튼은 변경된 값이 기본값과 다르면 내내 활성화 상태

https://github.com/user-attachments/assets/b5abc354-800e-4419-ba66-7cf8f84f3ae9

- 'Reset to default' 버튼은 System message 값이 기본값과 다른 상태일 때 계속 활성화되어야 함
    - (아주) 만약에 'Apply changes' 버튼으로 업데이트 된 System message 값이 기본값과 같다면 Reset 버튼도 같이 비활성화 되도록 함

https://github.com/user-attachments/assets/1981c29b-72b4-4cfb-bbe8-a9c9ff647c12

## 3. `SystemMessageTabComponentTests.cs`(임시) 생성
- `Tests.razor` 내 `SystemMessageTabComponent` 컴포넌트를 테스트하기 위한 파일을 `test/AzureOpenAIProxy.PlaygroundApp.Tests/UI(임시)`에 생성했습니다.
     1. label, textarea, button 등 기본적인 컴포넌트가 페이지 로드 시 보이는지
     2. textarea나 button이 초기 로드 시 의도한 default 상태로 설정되어 있는지
     3. textarea 값 변경 감지되면 Apply & Reset 버튼 활성화되는지
     4. Apply, Reset 버튼 각각 의도한 대로 작동하는지 
     - ... 이런 테스트 코드들을 작성해보았습니다.

# 고민되는 부분
1. textarea 부분과 Apply, Reset 버튼 각각이 활성화/비활성화되는 환경이나, 버튼을 눌렀을 때 실행되는 동작이 좀 복합적이어서 중복되는 코드를 최대한 덜어내려고 하다보니, 아래와 같이 `Assert.Multiple`을 사용해서 한 번에 여러 개를 Assert하는 테스트를 작성했습니다.

```
[Test]
    [TestCase("1 New system message 1", typeof(string))] ...
    public async Task Given_ApplyButton_When_Clicked_Then_TextArea_Value_Should_Be_Applied_As_SystemMessage_And_ApplyButton_Should_Be_Disabled(string expectedValue, Type expectedType)
    {
        // Arrange ...
        // Act ...

        // Assert
        Assert.Multiple(async () =>
        {
            await Expect(Page.Locator(".fluent-toast-title")).ToHaveTextAsync($"{expectedValue} (Type: {expectedType})");
            isApplyButtonDisabled.Should().NotBeNull();
            if (expectedValue == defaultValue)
            {
                isResetButtonDisabled.Should().NotBeNull();
            }
            else
            {
                isResetButtonDisabled.Should().BeNull();
            }
        });
    }
```
- 이 코드 말고도 비슷한 테스트가 2개 정도 더 있는데 이를 쪼개는 작업이 필요할지 궁금합니다.

2. 지금까지 작성했던 컴포넌트 테스트 코드들이 모두 `TestsPageTests.cs`에 들어간 것으로 이해해서 이 파일을 참고하면서 테스트를 작성을 했는데, 지금 작성한 것 보다도 좀 더 재사용성을 고려해서 코드를 고쳐야 할지 궁금합니다.

3. `SystemMessageTab` 컴포넌트를 담기 위한 컴포넌트가 `ConfigTabComponent.razor`인 것으로 이해를 했는데, UI를 만들어서 `Tests.razor`에서 테스트를 한 지금 단계에서 그치지 않고 `ConfigTabComponent.razor`에 적용하는 단계까지 진행해야 할지 궁금합니다.

2024-09-10 04:20 UTC, justinyoo requested changes
어떻게 보면 `tests` 페이지는 그냥 거쳐가는 거라 거기서 테스트하는 것도 좋지만, 실제 컴포넌트에 넣고 `/playground` 페이지에서 테스트하는 것이 더 나을 수도 있을 것 같습니다.

2024-09-10 04:20 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/UI/SystemMessageTabComponentTests.cs
> +        });
굳이 `Assert.Multiple`로 감쌀 필요가 없지 싶은데요?

2024-09-10 04:20 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/UI/SystemMessageTabComponentTests.cs
> +            await Expect(Page.Locator(".fluent-toast-title")).ToHaveTextAsync($"{expectedValue} (Type: {expectedType})");
이건 text 값을 `Page.Locator()`에서 텍스트를 받아오는 것으로 `// Act`쪽에 들어가야 할 것 같구요, 여기서는 그 값이 맞는지 확인하는 로직이 필요할 듯 합니다.

2024-09-10 04:20 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/UI/SystemMessageTabComponentTests.cs
> +            }
`if ... else ...`문은 각각 따로 테스트 메소드를 활용하면 어떨까요?

2024-09-10 04:20 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/UI/SystemMessageTabComponentTests.cs
> +            await Expect(Page.Locator(".fluent-toast-title")).ToHaveTextAsync($"{expectedValue} (Type: {expectedType})");
여기도 마찬가지

2024-09-13 13:05 UTC, justinyoo requested changes

2024-09-13 13:05 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/SystemMessageTabComponent.razor
> +        userSystemMessage = e.Value?.ToString();
`e.Value?.ToString()` vs `e.Value!.ToString()`

2024-09-13 13:05 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/SystemMessageTabComponent.razor
> +    private bool isResetButtonDisabled { get; set; } = true;
`bool` 변수는 아무 값을 지정하지 않으면 기본값으로 `false`로 지정됩니다. 이 기본값을 굳이 거슬러 애써 `true`를 세팅하는 건 안티패턴인 경우가 많은데요, 그렇다면 이 두 변수명을 `isApplyButtonEnabled`, `isResetButtonEnabled`로 바꿔서 기본값을 가져가게 하면 어떨까요?

2024-09-13 13:05 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/SystemMessageTabComponent.razor
> +    private string? userSystemMessage { get; set; }
이 변수는 필드 멤버라 굳이 `{ get; set; }`의 게터/세터가 필요 없습니다.

2024-09-13 13:05 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/SystemMessageTabComponent.razor
> +    private bool isResetButtonDisabled { get; set; } = true;
이 변수들도 필드 멤버라 굳이 `{ get; set; }`의 게터/세터가 필요 없습니다.

2024-09-14 06:08 UTC, justinyoo requested changes
몇가지 오타 + 로직 확인

2024-09-14 06:08 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/PlaygroundPageTests.cs
> +        var isResetButtonDisabled = await resetButton.GetAttributeAsync("disabled");
이 테스트가 뭔가 새로운 값이 들어오면 Apply 버튼이랑 Reset 버튼이 둘 다 활성화가 되는 걸 테스트하려는 거죠? 변수명 때문에 계속 헷갈렸는데, 그렇다면 이 변수명들을 `...Enabled`로 바꾸는 게 맞을까요? 아니면 계속 `...Disabled`로 놓는 게 좋을까요?

2024-09-14 06:08 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/ConfigTabComponent.razor
> +    private string? SystemMessage;
private 멤버니까 두 변수 모두 `camelCasing` 입니당.

2024-09-14 09:02 UTC, yjchun626 commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/PlaygroundPageTests.cs
> +        var isResetButtonDisabled = await resetButton.GetAttributeAsync("disabled");
기존 코드로 테스트할 때 버튼의 'disabled' 속성 유무에 따라 값이 정해지니까 `await applyButton.GetAttributeAsync("disabled");` 할때는 `...Disabled`로 이름 짓는 것이 맞겠다고 생각을 했는데, 저도 이부분 때문에 테스트 코드를 수정할 때마다 헷갈리더라고요 

수정하다 보니 아래처럼 버튼의 Enable 여부(bool)로 코드를 작성하는게 더 직관적인 것 같아서 비슷한 코드들을 전부 아래 코드처럼 바꿔봤습니다.

```
// Act
var isApplyButtonEnabled = await applyButton.GetAttributeAsync("disabled") == null;

// Assert
isApplyButtonEnabled.Should().BeTrue();
```

2024-09-14 09:56 UTC, yjchun626 commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/PlaygroundPageTests.cs
> +        var actualValue = await Page.EvaluateAsync<string>($"document.querySelector('{componentSelector}').value");
컴포넌트 'value' 값을 가져오려면 `EvaluateAsync`를 사용하는 방법만 있는 줄 알았는데 아래처럼 `.Locator(...).GetAttributeAsync("value")`로도 가능해서 수정했습니다! 

```
var actualValue = await Page.Locator(componentSelector).GetAttributeAsync("value");
```

2024-09-14 10:03 UTC, yjchun626 commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/PlaygroundPageTests.cs
> +        ");
피드백을 받고 찾아보니 `EvaluateAsync` 메소드가 웹 사이트 내에서 사용자 예상 행동을 실제로 테스트하기보다는, 그냥 JS 코드를 실행해서 값을 가져와 테스트하는 방식이라서 수정하는 게 나은 것이라고 이해를 했는데 제가 생각한게 맞을까요?

2024-09-14 10:36 UTC, yjchun626 commented
# 변경 사항
## 기존 request
```
await Page.EvaluateAsync(@$"
                const textarea = document.querySelector('{systemMessageTextAreaSelector}');
                textarea.value = '{newValue}';
                textarea.dispatchEvent(new Event('input', {{ bubbles: true }}));
");
```
> 이부분을 Locator와 FillAsync로 해결해 볼 수 있으세요?
---
## 해결 방법
처음에 `fluent-text-area`가 일반적인 HTML 구성 요소가 아니기 때문에 `.FillAsync`를 사용할 수 없다고 해서 좀 더 찾아봤는데, 개발자 도구로 살펴보니 `fluent-text-area` 안에 숨겨진 속성으로 `textarea`가 따로 있었습니다. 

그래서 일단 아래와 같이 2개로 나누어서 `Locator`로 받아온 다음에 필요한 코드를 작성했습니다.

```
// (1) 기존 fluent-text-area
var systemMessageTextArea = Page.Locator("fluent-text-area#system-message-tab-textarea");

// (2) 위 fluent-text-area 내의 <textarea> 속성 - control 가능
var systemMessageTextAreaControl = Page.Locator("fluent-text-area#system-message-tab-textarea textarea");
```

그 다음에 `.FillAsync`를 사용하는 코드와, 새로 적용한 값을 받아오는 코드(`.Locator(...).GetAttributeAsync("value")`)까지 아래와 같이 수정했습니다.

```
// Act
        await systemMessageTab.ClickAsync();
        await systemMessageTextAreaControl.FillAsync(expectedValue);
        await applyButton.ClickAsync();
        ...
        var actualValue = await systemMessageTextArea.GetAttributeAsync("value");

// Assert
        actualValue.Should().Be(expectedValue);
```

2024-09-16 01:32 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/PlaygroundPageTests.cs
> +        object expectedValue
엇, 그러고 보니 여기서 굳이 `object` 타입으로 설정할 필요가 있었나요?

2024-09-16 01:32 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/PlaygroundPageTests.cs
> +        ");
비슷하긴 한데, 저라면 Playwright의 네이티브 메서드를 적극적으로 활용할 것 같습니다.

2024-09-16 01:42 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/PlaygroundPageTests.cs
> +        var isResetButtonDisabled = await resetButton.GetAttributeAsync("disabled");
```csharp
var isApplyButtonEnabled = await applyButton.GetAttributeAsync("disabled") == null;
```

이 부분을 보면 `await applyButton.GetAttributeAsync("disabled") == null` 이 자체가 `null`인지 아닌지 체크하는 하나의 테스트라서, 테스트 메소드 안에 또다른 테스트가 들어간 느낌이라 코드의 의도는 알겠지만, 테스트 메소드 자체의 목적과는 좀 다르다고 생각합니다.

사실 테스트의 목적을 보면

1. 이 버튼이 활성화 됐는지 아닌지를 확인한다
2. `await applyButton.GetAttributeAsync("disabled")` 로 해당 버튼의 속성을 찾는다
3. 속성값이 있으면 비활성화, 없으면 활성화
4. 즉, 속성값 유무를 테스트한다.

라는 로직으로 이해했어요.

따라서, 지금 수정한 테스트 로직은 버튼 활성화 여부를 확인하는 거고, 원래 의도는 버튼의 속성값이 존재하는가 여부를 확인하는 거였다고 이해했는데... 어떻게 생각하세요? 원래 의도를 따라가자면

```csharp
var isApplyButtonEnabled = await applyButton.GetAttributeAsync("disabled");

isApplyButtonEnabled.Should().NotBeNull();
```

이 되어야 할 것 같은데, 유정님 의견은 어떠세요?

2024-09-16 01:44 UTC, justinyoo requested changes
몇가지 추가 의견 남겼습니다.

2024-09-16 06:32 UTC, justinyoo commented
PR: #280 #325 머지 이후 컨플릭 생겼습니당

2024-09-16 08:11 UTC, yjchun626 commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/PlaygroundPageTests.cs
> +        var isResetButtonDisabled = await resetButton.GetAttributeAsync("disabled");
말씀주신 것 읽고나니까 제가 변수명 지을때 테스트 의도보다는 그냥 코드가 돌아가고 assert 되는 방식에만 집중했던 것 같습니다 

솔직히 말씀드리면 Assert할 때 변수명에 따라 null, not null이 맥락상 잘 매치되어 보이게끔 _('disable' 속성이 보이는 거면 `...Disabled`=`...NotBeNull` 또는 버튼이 활성화된 상태면 `...Enabled`=`...BeTrue`)_ 해보고 싶었는데 애초에 그것이 그렇게 중요한 점은 아닌걸 지금 깨달은 것 같아요

말씀주신 대로 아래 방식과 같이 다시 수정하도록 하겠습니다. 감사합니다!!
```
var isApplyButtonEnabled = await applyButton.GetAttributeAsync("disabled");

isApplyButtonEnabled.Should().NotBeNull();
```

2024-09-16 08:13 UTC, yjchun626 commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/PlaygroundPageTests.cs
> +        object expectedValue
혹시나 다른데 쓰이려나 하고 `object`로 처음에 작성했다가 일단은 쓰이는 컴포넌트가 한정되어 있으니 `string`으로 변경하려고 했는데 깜빡했습니다 😅

2024-09-17 04:13 UTC, justinyoo requested changes
컴포넌트 중첩 관련해서 이벤트 버블링 관련 핸들러를 추가해야 할 것 같습니다.

2024-09-17 04:13 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/SystemMessageTabComponent.razor
> +        <FluentButton id="system-message-tab-apply-button" @onclick="OnApplyChanges" Disabled="@(!isApplyButtonEnabled)"
`Disabled=` 속성 값에 `true/false`를 전달하는데 좀 더 직관적인 표현을 생각해 보자면...

1. `@(!isApplyButtonEnabled)`
2. `@(isApplyButtonEnabled == false)`

이 둘 중 어떤게 더 나을까요? 저는 2번쪽을 선호하는 편인데, 가독성이 좀 더 높지 않나 생각합니다.

2024-09-17 04:13 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/PlaygroundPageTests.cs
> +    }
이 테스트는 config-window 컴포넌트 테스트에 해당하느니만큼 `PlaygroundPageConfigWindowTests.cs` 쪽으로 옮겨보면 어떨까요?

2024-09-17 04:13 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/ConfigTabComponent.razor
> +    }
여기서 설정한 `systemMessage` 값을 그 상위 컴포넌트인 `ConfigWindowComponent` 쪽으로 버블업 시키기 위한 이벤트 핸들러가 필요하지 않을까요? 마찬가지로 `ConfigWindowComponent` 컴포넌트는 상위 페이지 컴포넌트로 버블업 시켜야 할테구요.

2024-09-17 04:13 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/ConfigTabComponent.razor
>      public string? Id { get; set; }
이 파라미터 밑에 이벤트 콜백 하나 더 추가해야 할 듯 합니다. 그래야 이 상위 컴포넌트로 시스템 메시지를 전달할 수 있어요.

```csharp
[Parameter]
public EventCallback<string> OnSystemMessageChanged { get; set; }
```

2024-09-19 10:03 UTC, yjchun626 commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/SystemMessageTabComponent.razor
> +        <FluentButton id="system-message-tab-apply-button" @onclick="OnApplyChanges" Disabled="@(!isApplyButtonEnabled)"
넵 말씀대로 `!` 연산자 사용하는 것보다 2번처럼 작성하는 것이 버튼 비활성화 여부를 보여주는 데에 더 직관적인 것 같아 수정했습니다.

2024-09-19 11:29 UTC, yjchun626 commented
# 변경 사항
## 1. systemMessage 값 버블업 위한 이벤트 핸들러 추가 ([618e658](https://github.com/aliencube/azure-openai-sdk-proxy/pull/312/commits/618e6580344ce2ffc05a4229a9bdaa7d00f51f2d))
- 목표: **'ConfigTab -> ConfigWindow -> Playground 페이지'** 로 이어지는 컴포넌트 사이 `systemMessage` 값을 전달할 수 있도록 이벤트 핸들러 추가 및 코드 수정
1. `ConfigTabComponent.razor`와 `ConfigWindowComponent.razor`에 이벤트 핸들러를 추가했습니다.
```c#
[Parameter]
public EventCallback<string> OnSystemMessageChanged { get; set; }
```

2. `ConfigTabComponent.razor`, `ConfigWindowComponent.razor`, `Playground.razor` 각각에 SetSystemMessage 메소드 추가 or 수정 
```c#
// ConfigTab, ConfigWindow -> 각자의 상위 컴포넌트로 버블링
private async Task SetSystemMessage(string systemMessage)
{
    this.systemMessage = systemMessage;
        
    await OnSystemMessageChanged.InvokeAsync(systemMessage);
}

// Playground 페이지
<ConfigWindowComponent ... OnSystemMessageChanged="SetSystemMessage" ... />
...
private async Task SetSystemMessage(string systemMessage)
{
    this.systemMessage = systemMessage;

    await Task.CompletedTask;
}
```

## 2. SystemMessageTab 관련 테스트 코드 `PlaygroundPageConfigWindowTests.cs`로 이전 및 수정([c874a50](https://github.com/yjchun626/azure-openai-sdk-proxy/commit/c874a506c0a8affe1cd69b75d2c16cda13503c65))
1. 코드리뷰를 반영하여 기존 `PlaygroundPageTests.cs`에 있던 SystemMessageTab 컴포넌트 관련 테스트 코드를 전부 `PlaygroundPageConfigWindowTests.cs`로 옮겼습니다.
2. GitHub Actions 내에서 불규칙적으로 SystemMessageTab 관련 테스트에서 fail 처리가 되어 이를 해결하고자 `await Task.Delay(500);` 을 추가했습니다.
     - 테스트에서 fail이 대부분 `actualValue`, `is...ButtonEnabled` 변수 값을 Assert할 때 나타나서, `await applyButton.ClickAsync();` 등으로 **버튼을 클릭한 후에** 타 컴포넌트의 상태 변화를 **대기**하고 각 변수에 할당하는 것이 해결 방법이라 생각했습니다.
```c#
// Act
... // .FillAsync로 새로운 값 적용 등
await applyButton.ClickAsync();
await Task.Delay(500); // 버튼 클릭 후 우선 대기 - 500밀리초

// 이후 각 변수에 값 할당
var actualValue = await systemMessageTextArea.GetAttributeAsync("value");
var isApplyButtonEnabled = await applyButton.GetAttributeAsync("disabled");
var isResetButtonEnabled = await resetButton.GetAttributeAsync("disabled");

// Assert
actualValue.Should().Be(expectedValue);
isApplyButtonEnabled.Should().NotBeNull();
isResetButtonEnabled.Should().NotBeNull();
```

## 3. `SystemMessageTabComponent.razor` 코드 리팩토링 ([80031c1](https://github.com/yjchun626/azure-openai-sdk-proxy/commit/80031c1ab8d8f91c29dd4928042e362b5d4385b7))
1. 코드리뷰를 반영하여 각 <FluentButton>의 'Disabled' 속성 값을 표현하는 코드식을 변경했습니다.
```c#
<FluentButton ... @onclick="OnApplyChanges" Disabled="@(isApplyButtonEnabled == false)"> ...
```
2. 변수 이름 수정: `changeSystemMessage` -> `userInput`
- 기존 SystemMessageTab 컴포넌트 내의 TextArea control의 input 값을 받아오는 변수 이름을 위와 같이 변경했습니다.
- 그와 같이 <FluentTextArea>의 `@oninput` 이벤트 메소드인 `OnInputChanged`를 아래와 같이 변경했습니다.
```c#
private async Task OnInputChanged(ChangeEventArgs userInput)
{
    this.userInput = userInput.Value!.ToString();
    isApplyButtonEnabled = true;
    ...
    await Task.CompletedTask;
}
```
## 궁금한 점
1. 위에서 언급했듯이 테스트 코드에 `Task.Delay` 문을 사용했는데, 사실 테스트 코드 작성할 때 의도적으로 Delay를 넣는 것은 지양해야 하는 것인지 궁금합니다.
     - SystemTabComponent 테스트에서 fail이 뜨는 이유가 다른게 있을지도 좀 더 봐야할 것 같습니다.
2. SystemMessage 값 버블링을 위해 코드를 수정하고 커밋을 했는데(필요한 곳에 이벤트 핸들러 추가하고, 상위 컴포넌트 내 하위 컴포넌트 요소에 `{이벤트 핸들러}={값 set 메소드}` 작성), 값이 제대로 올라가는 데에 혹시 놓친 부분이 있는지 궁금합니다.

2024-09-20 08:16 UTC, justinyoo requested changes

2024-09-20 08:16 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/PlaygroundPageConfigWindowTests.cs
> +        await Task.Delay(500);
첫번째 `systemMessageTab.ClickAsync();`와 두번째 `applyButton.ClickAsync()` 사이에 텀이 없는 것 같아서 어떨 땐 되고 어떨땐 안되고 하는 듯 싶으니... 각 `ClickAsync()` 메소드에서 지원하는 Delay 옵션을 써보면 어떨까요?

https://playwright.dev/dotnet/docs/api/class-locator#locator-click

2024-09-20 08:33 UTC, yjchun626 commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/PlaygroundPageConfigWindowTests.cs
> +        await Task.Delay(500);
아하 메소드 내에서 자체 delay 지원하는 옵션을 미처 생각 못했네요.!! 참고해서 수정해보겠습니다 😅

2024-09-20 09:48 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/PlaygroundPageConfigWindowTests.cs
> +        await Task.Delay(500);
뉍!

2024-09-20 09:50 UTC, justinyoo requested changes

2024-09-20 09:50 UTC, justinyoo commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/PlaygroundPageTests.cs
> +    }
요것들도 옮겨야 할 듯?

2024-09-20 09:52 UTC, yjchun626 commented on test/AzureOpenAIProxy.PlaygroundApp.Tests/Pages/PlaygroundPageTests.cs
> +    }
바로 옮길게요!!

2024-09-20 09:58 UTC, justinyoo approved these changes
고생하셨습니다. LGTM!

2024-09-20 09:58 UTC, merged