[Playground] Refactoring `OpenAIApiClient` #163
aliencube/azure-openai-sdk-proxy pull request #314
Opened 2024-09-11 17:29 UTC by 5jisoo

## 작업중인 이슈
- #163 

## 작업 내용
1. Program.cs에서 AzureOpenAIClient 싱글톤 등록
    - api key는 임의의 문자열 값으로 설정해두었습니다.
2. OpenAIApiClient으로 AzureOpenAIClient을 주입
3. OpenAIApiClientOptions에서 apikey, endpoint 삭제
4. ChatWindowComponent에서 불필요한 요소 정리

## 궁금한 점
1. 지난번 유튜브 요약 실습에서 `https+http://apiapp` 를 HttpClient의 BaseAddress로 지정해주었던 것과 동일한 방식으로 AzureOpenAIClient의 endpoint를 설정하였는데, 이게 올바른 방향이 맞는지 궁금합니다.
2. 리팩토링도 테스트 코드가 따로 필요한지 궁금합니다.

2024-09-12 05:09 UTC, justinyoo requested changes
이 `ChatWndowComponent.razor`가 들어있는 `Home.razor` 파일을 로컬에서 테스트 돌리면 잘 돌아가는지만 확인해 보시지요. 통합테스트 부분은 나중에 따로 처리해야 할 듯.

2024-09-12 05:09 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Program.cs
> +));
여기서 `AzureKeyCredential` 인스턴스를 만들 때 필요한 API key 값은 플레이그라운드 UI에서 받아오기 때문에, 이렇게 할 수가 없어요.

2024-09-12 05:09 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/ChatWindowComponent.razor
>              var options = new OpenAIApiClientOptions()
차라리 이 `OpenAIApiClientOptions` 인스턴스를 `Endpoint`값만 넣어서 `Scoped`로 인젝션하면 어때요? 그러면 나머지 값은 여기서 받아서 넣을 수 있으니까.

2024-09-13 03:45 UTC, justinyoo commented
@5jisoo 컨플릭 먼저 해결해 보시구요, 이제부터는 플레이그라운드 페이지에 직접 적용을 시켜볼까요?

2024-09-13 12:53 UTC, justinyoo requested changes

2024-09-13 12:53 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Program.cs
> +    _ => new OpenAIApiClientOptions { Endpoint = "https+http://apiapp" }
저 `Endpoint` 속성을 `string?` 에서 `Uri?`로 바꾸면 어때요? 그리고 이 문서대로 해 보면?

https://learn.microsoft.com/en-us/dotnet/aspire/service-discovery/overview#named-endpoints

2024-09-13 12:53 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/ChatWindowComponent.razor
> +        await Api.CompleteChatAsync();
이 `CompletChatAsync()` 메서드를 `CompleteChatAsync(Options)`로 바꿔야 하지 않을까요? 그래야 이 컴포넌트에서 받아온 모든 데이터를 전달할 수 있을 듯?

2024-09-13 12:53 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Clients/OpenAIApiClient.cs
> +public class OpenAIApiClient(OpenAIApiClientOptions clientOptions) : IOpenAIApiClient
이걸 여기서 받아오면 안 될 것 같아요.

2024-09-13 12:53 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Clients/OpenAIApiClient.cs
> +    public async Task<string> CompleteChatAsync()
이 메서드 시그니처가 `CompletChatAsync(OpenAIApiClientOptions options)`로 바뀌어야 할 듯?

2024-09-22 15:11 UTC, 5jisoo commented
일단 수정 사항은 전부 고쳤습니다!
첨부해주신 공식문서 읽어보았는데, Named endpoints쪽이 아직 동일한 에러가 발생하고 있습니다. 
계속 찾아보고는 있는데 쉽지 않네요🥲

2024-09-23 05:49 UTC, justinyoo commented
> 일단 수정 사항은 전부 고쳤습니다! 첨부해주신 공식문서 읽어보았는데, Named endpoints쪽이 아직 동일한 에러가 발생하고 있습니다. 계속 찾아보고는 있는데 쉽지 않네요🥲

정 안되면 HttpClient 인스턴스를 인젝션하고 거기서 BaseUri 값을 받아오는 식의 꼼수를 써야 할 수도 있을 듯 해요.

2024-09-23 05:57 UTC, justinyoo requested changes
대략의 의견을 남겨봤어요

2024-09-23 05:57 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Program.cs
>  builder.Services.AddScoped<IOpenAIApiClient, OpenAIApiClient>();
`builder.Services.AddScoped<IOpenAIApiClient, OpenAIApiClient>();` 대신

```csharp
builder.Services.AddHttpClient<IOpenAIApiClient, OpenAIApiClient>(client =>
{
    client.BaseUri = new Uri("https+http://apiapp");
});
```

이런 식으로 해 보면 어때요?

2024-09-23 05:57 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Clients/OpenAIApiClient.cs
>      /// <inheritdoc />
그다음에 여기서

```csharp
public class OpenAIApiClient(HttpClient http) : IOpenAIApiClient
{
    private readonly HttpClient _http = http ?? throw new ArgumentNullException(nameof(http));
```

하고

2024-09-23 05:57 UTC, justinyoo commented on src/AzureOpenAIProxy.PlaygroundApp/Clients/OpenAIApiClient.cs
> +        // test
그다음에 여기에서

```csharp
clientOptions.Endpoint = this._http.BaseUri;
```

대충 이런 식으로 넣어도 될 듯 한데...?

2024-09-23 08:48 UTC, 5jisoo commented
.... 이렇게 바꾸어도 동일한 에러가 발생합니다

2024-09-23 10:08 UTC, justinyoo commented
> .... 이렇게 바꾸어도 동일한 에러가 발생합니다

지수님 리포로 PR 하나 날렸어요: https://github.com/5jisoo/azure-openai-sdk-proxy/pull/1

한 번 확인해 보시고, 적용시켜 보세요.

2024-09-28 04:21 UTC, tae0y commented on src/AzureOpenAIProxy.PlaygroundApp/Components/UI/OldChatWindowComponent.razor
>                  MaxTokens = maxTokens,
Azure.AI.OpenAI 2.0.6-beta에서 MaxTokens 필드가 deprecated되어 빌드 오류가 발생해서요
MaxOutputTokenCount 이제 이 필드를 사용해야하는 것 같습니다
빌드시 오류메시지 (로컬, github action 빌드 모두 아래 문제가 발생함)
```
/Users/bachtaeyeong/10_SrcHub/azure-openai-sdk-proxy/src/AzureOpenAIProxy.PlaygroundApp/Clients/OpenAIApiClient.cs(41,13): error CS0117: 'ChatCompletionOptions'에는 'MaxTokens'에 대한 정의가 포함되어 있지 않습니다. [/Users/bachtaeyeong/10_SrcHub/azure-openai-sdk-proxy/src/AzureOpenAIProxy.PlaygroundApp/AzureOpenAIProxy.PlaygroundApp.csproj]
    경고 4개
    오류 1개
```

제 빌드 환경은 다음과 같습니다
- .NET SDK  Version: 8.0.301
-  Mac OS X / OS Version:  14.6 / M1
- 실제 버전정보 `dotnet list package` : 다른 팀원은 `2.0.0-beta.5`에선 빌드 잘 돼고 있어서, `beta6`부터 오류가 나는것 같아요.
```
Project 'AzureOpenAIProxy.PlaygroundApp' has the following package references
   [net8.0]: 
   Top-level Package                                     Requested   Resolved    
   > Azure.AI.OpenAI                                     2.*-*       2.0.0-beta.6
   > Microsoft.FluentUI.AspNetCore.Components            4.*         4.10.0      
   > Microsoft.FluentUI.AspNetCore.Components.Emoji      4.*         4.6.0       
   > Microsoft.FluentUI.AspNetCore.Components.Icons      4.*         4.10.0  
```
- playground csproj 파일
```csproj
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <AssemblyName>AzureOpenAIProxy.PlaygroundApp</AssemblyName>
    <RootNamespace>AzureOpenAIProxy.PlaygroundApp</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.AI.OpenAI" Version="$(AzureOpenAIVersion)" />
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" Version="$(FluentUIVersion)" />
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Emoji" Version="$(FluentUIVersion)" />
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Icons" Version="$(FluentUIVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AzureOpenAIProxy.ServiceDefaults\AzureOpenAIProxy.ServiceDefaults.csproj" />
  </ItemGroup>
</Project>
```

2024-10-02 06:53 UTC, justinyoo commented
지금 OpenAI SDK 가장 최신 버전이 2.1.0-beta.1 입니다. 그거 기준으로 가시지요.

https://www.nuget.org/packages/Azure.AI.OpenAI/2.1.0-beta.1

2024-10-02 08:49 UTC, justinyoo commented
제가 main 브랜치 업데이트해서 컨플릭 날 거예요 @5jisoo 확인해 보시고, 반영시켜 주세요

2024-10-06 05:33 UTC, justinyoo approved these changes
일단 테스트 코드 없이 가 봅시다

2024-10-06 05:34 UTC, merged