[Backend API] Implement endpoint for view event details
aliencube/azure-openai-sdk-proxy pull request #318
Opened 2024-09-14 06:30 UTC by sikutisa

Resolves: #208 

### Description
* 이벤트 ID를 통해 이벤트 세부사항을 가져오는 API 구현
* `AdminEventEndpoints.cs`의 **AddGetAdminEvent** 메소드 업데이트
* `AdminEventRepository.cs` 업데이트
  * TableServiceClient 의존성 추가
* TODO
  * **GetEvent** 메소드 업데이트

2024-09-20 07:40 UTC, justinyoo requested changes
코멘트 남겨뒀습니다

2024-09-20 07:40 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEventEndpoints.cs
> +            [FromRoute] string eventId,
혹시 여기서 `string` 대신 `Guid`로 데이터 타입 설정이 가능한가요?

2024-09-20 07:40 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEventEndpoints.cs
> +            if(Guid.TryParse(eventId, out _))
만약에 파라미터 타입을 `string`에서 `Guid`로 설정이 가능하다면 사실 이 `if { ... }` 블록은 필요없을 듯 싶고, 그게 안된다면 여기서 `out _` 대신 파싱한 결과 값을 두고 그 값을 저기 아래 126번 라인에서 쓰면 되지 않을까요?

```csharp
var parsed = Guid.TryParse(eventId, out var result) ? result : default(Guid);
if (parsed == default(Guid))
{
    // 404 로직
}

...

try
{
    var details = await service.GetEvent(parsed);
    // 나머지 로직
}
```

2024-09-20 07:40 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEventEndpoints.cs
> +                // TODO: 발생 가능한 exception 별로 다르게 처리할 필요가 있는지 검토
전 굳이...? 예외별로 다르게 처리할 이유는 없어보입니다!

2024-09-21 14:10 UTC, sikutisa commented on src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEventEndpoints.cs
> +                // TODO: 발생 가능한 exception 별로 다르게 처리할 필요가 있는지 검토
넵 알겠습니다 👌

2024-09-21 14:23 UTC, sikutisa commented on src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEventEndpoints.cs
> +            [FromRoute] string eventId,
관련 문서 찾아봤는데, `Guid` 타입은 모델 바인드가 지원되는 것 같습니다. `Guid`로 변경해서 작업하겠습니다. 
https://learn.microsoft.com/en-us/aspnet/core/mvc/models/model-binding?view=aspnetcore-8.0

2024-09-21 14:24 UTC, sikutisa commented on src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEventEndpoints.cs
> +            if(Guid.TryParse(eventId, out _))
다음 코멘트에서 논의한 것에 의하면, 말씀하신 데로 if 블록 사용하지 않아도 될 것 같습니다.
https://github.com/aliencube/azure-openai-sdk-proxy/pull/318#discussion_r1769582595

2024-09-22 09:32 UTC, sikutisa commented on src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEventEndpoints.cs
> +                // TODO: 발생 가능한 exception 별로 다르게 처리할 필요가 있는지 검토
repository에서 `TableClient.GetEntityAsync`를 실행했을 때, 엔티티가 존재하지 않으면 `RequestFailedException`이 발생하는 것으로 확인해서 status에 따라서 처리를 추가했습니다.

https://learn.microsoft.com/en-us/dotnet/api/azure.data.tables.tableclient.getentityasync?view=azure-dotnet#azure-data-tables-tableclient-getentityasync-1(system-string-system-string-system-collections-generic-ienumerable((system-string))-system-threading-cancellationtoken)

2024-09-23 05:46 UTC, justinyoo requested changes
좋습니다! 두어가지만 더 짚어보시지요.

2024-09-23 05:46 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEventEndpoints.cs
> +                return details is null? Results.NotFound(): Results.Ok(details);
여기서 조건식으로 NotFound가 걸릴 일이 있을까요?

2024-09-23 05:46 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Repositories/AdminEventRepository.cs
> +            partitionKey: "event-details"
이 `event-details` 값은 상수이고 변할 일이 없으니 별도의 `Constants` 클래스에 넣거나 하는 것이 나을 듯?

2024-09-23 05:46 UTC, justinyoo commented on test/AzureOpenAIProxy.ApiApp.Tests/Services/AdminEventServiceTests.cs
> +using Google.Protobuf.WellKnownTypes;
??? 이건 뭔가요?

2024-09-23 06:03 UTC, sikutisa commented on test/AzureOpenAIProxy.ApiApp.Tests/Services/AdminEventServiceTests.cs
> +using Google.Protobuf.WellKnownTypes;
지우겠습니다 😅

2024-09-23 06:04 UTC, sikutisa commented on src/AzureOpenAIProxy.ApiApp/Endpoints/AdminEventEndpoints.cs
> +                return details is null? Results.NotFound(): Results.Ok(details);
엔티티를 못 찾으면 예외가 먼저 발생해서 404 처리가 될 것 같습니다. 필요 없는 조건식인 것 같네요. 지우겠습니다.

2024-09-23 06:17 UTC, sikutisa commented on src/AzureOpenAIProxy.ApiApp/Repositories/AdminEventRepository.cs
> +            partitionKey: "event-details"
https://github.com/aliencube/azure-openai-sdk-proxy/pull/281#issuecomment-2354480484
해당 코멘트를 참고해서 event details와 resource details에 대한 파티션 키를 별도의 파일로 분리했습니다.

2024-09-23 06:23 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Repositories/AdminEventRepository.cs
> +        await tableClient.CreateIfNotExistsAsync();
여기도 맨 마지막에 `.ConfigureAwait(false)` 추가해 주세요.

async/await 체인의 맨 마지막(여기서는 Endpoint 메소드)을 제외하고는 모두 `.ConfigureAwait(false)`를 붙입니다.

2024-09-23 06:24 UTC, sikutisa commented on src/AzureOpenAIProxy.ApiApp/Repositories/AdminEventRepository.cs
> +        await tableClient.CreateIfNotExistsAsync();
86번 라인 말씀하시는 것 맞나요?

2024-09-23 06:27 UTC, sikutisa commented
혹시 테스트코드는 괜찮은지 한 번만 더 봐주실 수 있나요? 익숙치 않아서 조금 자신이 없네요 😅

2024-09-23 08:39 UTC, justinyoo approved these changes
수고하셨습니다! LGTM!

2024-09-23 08:39 UTC, merged