[Backend API] Add Table Name property to appsettings.json
aliencube/azure-openai-sdk-proxy pull request #320
Opened 2024-09-14 07:44 UTC by sikutisa

* Resolves: #319 

### Description
* AdminEventRepository에 StorageSettings field 추가
* `AddAdminEventRepository`가 실행될 때, 해당 필드 초기화

2024-09-14 07:53 UTC, justinyoo requested changes

2024-09-14 07:53 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Configurations/StorageSettings.cs
> +public class StorageSettings
`StorageAccountSettings`

2024-09-14 07:53 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Configurations/TableSettings.cs
> +public class TableSettings
`TableStorageSettings`

2024-09-14 07:53 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Repositories/AdminEventRepository.cs
> +public class AdminEventRepository(IServiceCollection sc) : IAdminEventRepository
`public class AdminEventRepository(TableServiceClient tableServiceClient, StorageAccountSettings settings) : IAdminEventRepository`

2024-09-14 07:53 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/appsettings.json
> +    "Stroage": {
`StorageAccount`

2024-09-14 07:53 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Repositories/AdminEventRepository.cs
> +        services.AddScoped<IAdminEventRepository>(p => new AdminEventRepository(services));
롤백하세욥

2024-09-14 07:59 UTC, sikutisa commented on src/AzureOpenAIProxy.ApiApp/appsettings.json
> +    "Stroage": {
반영했습니다.

2024-09-14 08:00 UTC, sikutisa commented on src/AzureOpenAIProxy.ApiApp/Configurations/StorageSettings.cs
> +public class StorageSettings
반영했습니다.

2024-09-14 08:04 UTC, sikutisa commented on src/AzureOpenAIProxy.ApiApp/Configurations/TableSettings.cs
> +public class TableSettings
반영했습니다.

2024-09-14 08:21 UTC, sikutisa commented on src/AzureOpenAIProxy.ApiApp/Repositories/AdminEventRepository.cs
> +public class AdminEventRepository(IServiceCollection sc) : IAdminEventRepository
반영했습니다.

2024-09-14 08:21 UTC, sikutisa commented on src/AzureOpenAIProxy.ApiApp/Repositories/AdminEventRepository.cs
> +        services.AddScoped<IAdminEventRepository>(p => new AdminEventRepository(services));
롤백했습니다.

2024-09-14 08:22 UTC, sikutisa commented on src/AzureOpenAIProxy.ApiApp/Extensions/StorageSettingsExtensions.cs
> +        return settings;
@justinyoo 
`ServiceCollectionExtensions.cs`에 있는 메소드들을 참고해서 구조를 변경했는데요, 작업을 하다 보니 이 메소드를 별도의 파일로 분리할 필요가 있나 생각이 드네요. `ServiceCollectionExtensions.cs`로 합치는 거 어떻게 생각하시는지요.

2024-09-14 08:25 UTC, sikutisa commented
기존에 존재하는 테스트들 중, 수정사항에 영향을 받는 테스트들은 업데이트 했고 `AddAddStorageAccountSettings` 메소드에 대한 테스트는 추가해야 하는 상황입니다.

2024-09-14 16:14 UTC, sikutisa commented on src/AzureOpenAIProxy.ApiApp/Extensions/StorageSettingsExtensions.cs
> +        return settings;
일단 테스트는 현재 구조를 기반으로 추가했습니다.

2024-09-16 01:09 UTC, justinyoo requested changes
예외처리하는 부분이랑 테스트 관련 코멘트 남겨뒀어요.

2024-09-16 01:09 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Repositories/AdminEventRepository.cs
> +    private readonly StorageAccountSettings _storageAccountSettings = storageAccountSettings;
NullReferenceException 처리도 해야 합니다. 예)

```csharp
private readonly TableServiceClient _tableServiceClient = tableServiceClient ?? throw new ArgumentNullException(nameof(tableServiceClient));
```

여기 참고해 보세요:

https://github.com/aliencube/azure-openai-sdk-proxy/blob/af47323ad84450f7fa7cb90b6d35927c96ad49e5/src/AzureOpenAIProxy.ApiApp/Services/AdminEventService.cs#L43-L46

2024-09-16 01:09 UTC, justinyoo commented on test/AzureOpenAIProxy.ApiApp.Tests/Repositories/AdminEventRepositoryTests.cs
>      public void Given_Instance_When_CreateEvent_Invoked_Then_It_Should_Throw_Exception()
이 테스트 전에 디펜던시가 null 일 경우 `ArgumentNullException` 던지는 테스트도 추가해야 합니다. 디펜던시가 두개니까, 테스트도 두개를 추가해야 할 듯?

2024-09-16 01:12 UTC, justinyoo requested changes

2024-09-16 01:12 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Extensions/StorageAccountSettingsExtensions.cs
저도 일구님 의견에 동의합니다. `ServiceCollectionExtensions.cs` 쪽으로 합치시죠.

2024-09-16 02:10 UTC, sikutisa commented on src/AzureOpenAIProxy.ApiApp/Repositories/AdminEventRepository.cs
> +    private readonly StorageAccountSettings _storageAccountSettings = storageAccountSettings;
해당 부분 추가했습니다.

2024-09-16 02:10 UTC, sikutisa commented on test/AzureOpenAIProxy.ApiApp.Tests/Repositories/AdminEventRepositoryTests.cs
>      public void Given_Instance_When_CreateEvent_Invoked_Then_It_Should_Throw_Exception()
테스트 추가했습니다.

2024-09-16 02:10 UTC, sikutisa commented on src/AzureOpenAIProxy.ApiApp/Extensions/StorageAccountSettingsExtensions.cs
`StorageAccountSettingsExtensions.cs`를 `ServiceCollectionExtensions.cs`로 통합하고, 이에 따라 테스트 코드 역시 통합하였습니다.

2024-09-16 02:15 UTC, justinyoo approved these changes
수고하셨습니다!

2024-09-16 02:15 UTC, merged