[Backend API] Implement endpoint for list of events
aliencube/azure-openai-sdk-proxy pull request #330
Opened 2024-09-23 14:10 UTC by sikutisa

Resolves: #180 

### Description
* 사용자의 이벤트 목록을 가져오는 엔드포인트 구현
* `PlaygroundService.cs` 추가
  * `GetEvents()` 메소드 구현
* `EventRepositorycs` 추가
  * `GetEvents()` 메소드 구현
*  `PlaygroundService`와 `EventRepsitory`에 대한 의존성 추가

### Discussions
* 최종적으로 로그인한 유저가 확인 가능한 이벤트들만 리스트로 제공해야 하는데, 현재 Model들만 가지고는 불가능한 사항인 것 같습니다.
  * `AdminDetails`와 유사하게 `EventDetails`를 상속하는 `UserDetails`와 같은 모델을 만들고, 해당 이벤트에 엑세스 가능한 유저 정보를 추가
  * 유저에 대응되는 모델을 추가하고, 해당 모델에 유저가 엑세스 가능한 이벤트들에 대한 정보를 들고 있게 하기
    * 유저에 대한 ID 식별값이 row key로 들어가고, 이벤트들의 ID(이벤트의 row key와 동일한 값)들을 들고 있는다면...?
  * 다른 방법도 논의해보면 좋을 것 같습니다.

### ToDo
* 테스트코드 추가

2024-10-03 00:26 UTC, justinyoo commented
> 최종적으로 로그인한 유저가 확인 가능한 이벤트들만 리스트로 제공해야 하는데, 현재 Model들만 가지고는 불가능한 사항인 것 같습니다.

맞습니다. 현재는 사용자 로그인 기능 자체가 없어서 불가능해요. 그래서 현재로서는 그냥 모든 이벤트를 다 들고 오는게 최선이예요. 이부분은 차후에 리팩토링을 거쳐야 합니다.

2024-10-03 00:31 UTC, justinyoo requested changes

2024-10-03 00:31 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Endpoints/PlaygroundEndpoints.cs
> +                }
여기에 404를 추가했다면 아래 52-53번 라인 사이에 404 로직 하나 더 추가해야 합니다.

2024-10-03 00:31 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Program.cs
> +// Add event repository
요 주석을 `// Add playground repositories` 라고 바꿔볼까요?

2024-10-03 07:03 UTC, sikutisa commented on src/AzureOpenAIProxy.ApiApp/Endpoints/PlaygroundEndpoints.cs
> +                }
추가했습니다.

2024-10-03 07:03 UTC, sikutisa commented on src/AzureOpenAIProxy.ApiApp/Program.cs
> +// Add event repository
반영했습니다.

2024-10-03 07:05 UTC, sikutisa commented
> 맞습니다. 현재는 사용자 로그인 기능 자체가 없어서 불가능해요. 그래서 현재로서는 그냥 모든 이벤트를 다 들고 오는게 최선이예요. 이부분은 차후에 리팩토링을 거쳐야 합니다.

말씀하신 것처럼 모든 이벤트 가져오는 방향으로 작업하겠습니다. 그리고 테스트 코드들도 추가했습니다.

2024-10-06 05:47 UTC, justinyoo requested changes

2024-10-06 05:47 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Endpoints/PlaygroundEndpoints.cs
> +        .Produces(statusCode: StatusCodes.Status404NotFound)
이 404 추가한 것 관련해서 OpenAPI 문서 테스트 코드가 필요합니다.

2024-10-06 05:47 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Repositories/EventRepository.cs
> +        return events;
질문: 여기 어딘가에서 order by 소팅을 해서 돌려주는 게 좋을까요, 아니면 소팅하는 로직은 UI에서 하는 걸로 냅두는 게 좋을까요?

2024-10-06 05:47 UTC, justinyoo commented on test/AzureOpenAIProxy.ApiApp.Tests/Repositories/EventRepositoryTests.cs
> +}
- `listSize` 값을 10또는 20 미만의 랜덤 숫자로 가져오게 하는 로직으로 바꿔서 진행해보면 어떨까요?
- 그렇게 하면 eventId 값도 `Guid.NewGuid()` 같은 식으로 랜덤하게 만들어서 미리 seeding을 해 놓고 시작하면 될 것 같기도 한데?

2024-10-06 06:29 UTC, sikutisa commented on src/AzureOpenAIProxy.ApiApp/Endpoints/PlaygroundEndpoints.cs
> +        .Produces(statusCode: StatusCodes.Status404NotFound)
> 이 404 추가한 것 관련해서 OpenAPI 문서 테스트 코드가 필요합니다.

OpenAPI 문서 테스트 코드가 spetral 검사 규칙이 추가 돼야 한다는 의미일까요?

2024-10-06 06:31 UTC, sikutisa commented on src/AzureOpenAIProxy.ApiApp/Repositories/EventRepository.cs
> +        return events;
저는 백엔드에서 정렬해서 반환하는 게 더 좋을 것 같습니다. 정렬 기준은 생각해두신게 있으실까요?

2024-10-06 06:32 UTC, sikutisa commented on test/AzureOpenAIProxy.ApiApp.Tests/Repositories/EventRepositoryTests.cs
> +}
말씀하신 방향이 더 좋을 것 같습니다. 반영하도록 하겠습니다.

2024-10-06 12:25 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Endpoints/PlaygroundEndpoints.cs
> +        .Produces(statusCode: StatusCodes.Status404NotFound)
AppHost.Tests 프로젝트에서 OpenAPI 문서 생성하는 것에 대한 테스트가 있습니다. 거기 한 번 확인해 보세요.

2024-10-06 12:27 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Repositories/EventRepository.cs
> +        return events;
만약 소팅해서 반환한다면 title, 시작일, 종료일 순서로 정렬을 하면 어떨까 싶습니다.

2024-10-06 14:53 UTC, sikutisa commented on src/AzureOpenAIProxy.ApiApp/Endpoints/PlaygroundEndpoints.cs
> +        .Produces(statusCode: StatusCodes.Status404NotFound)
> 이 404 추가한 것 관련해서 OpenAPI 문서 테스트 코드가 필요합니다.

테스트 코드를 작성하기 이전에, 404에 대해 좀 더 논의할 필요가 있을 것 같은데요.
제가 #318 를 작업할 때, `TableClient.GetEntity()` 함수를 사용했었습니다. 이 함수의 경우에는 엔티티를 찾지 못하면 statuscode가 404인 `RequestFailedException`이 발생하게 됩니다. 그래서 이를 다른 예외와 구분해서 처리하기 위해 아래 코드처럼 처리했었습니다.
```cs
            catch (RequestFailedException ex)
            {
                if(ex.Status == 404)
                {
                    logger.LogError($"Failed to get events list");
                    return Results.NotFound();
                }

                logger.LogError(ex, $"Error occurred while fetching events list");
                return Results.Problem(ex.Message, statusCode: StatusCodes.Status500InternalServerError);
            }
```
이번 이슈의 경우 복수개의 엔티티를 가져올 수 있다 보니 `TableClient.QueryAsync()` 함수를 사용했는데요. 이 함수도 `RequestFailedException`가 발생할 수 있다고 돼 있어, 엔티티를 못찾으면 `TableClient.GetEntity()`와 동일하게 동작할 거라 생각했는데, 테스트해보니 엔티티가 없는 경우에도 예외가 발생하지 않습니다.
그래서 지금 두 엔드포인트가 다르게 동작하고 있는데요.
`/admin/events/{eventID}`의 경우, 이벤트 ID에 해당하는 이벤트가 없을 때는 404 에러가 반환됩니다. 이 경우는 정상적으로 동작하고 있다고 생각이 됩니다. 
![admin-events-{eventId}](https://github.com/user-attachments/assets/d9c7c750-c6ce-4fa4-937d-99ef53176809)

지금 작업 중인 `/events`의 경우, 이벤트가 없을 경우에 200과 함께 빈 리스트가 반환되고 있습니다.
![events](https://github.com/user-attachments/assets/77ca529b-36a2-484e-b5b4-2a800e587cfc)

이벤트가 없을 경우에 어떻게 처리하는 것이 더 적절한가에 대해 논의해야 할 것 같습니다.
1안) 200과 함께 빈 리스트 반환
2안) 서비스 레이어에서 빈 리스트가 넘어오면, 404로 응답

2024-10-06 15:37 UTC, sikutisa commented on src/AzureOpenAIProxy.ApiApp/Repositories/EventRepository.cs
> +        return events;
말씀하신 부분을 반영했고, `EventDetails`에는 `DateStart`와 `DateEnd`가 없어, 해당 속성들을 `AdminEventDetails`에서 `EventDetails`로 옮겼습니다.

2024-10-10 01:12 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Repositories/EventRepository.cs
> +        return events;
앗, 이게 플레이그라운드 용이로군요! 그렇다면 title 하나로만 하면 충분할 듯 싶습니다! @sikutisa

2024-10-10 03:25 UTC, sikutisa commented on src/AzureOpenAIProxy.ApiApp/Repositories/EventRepository.cs
> +        return events;
그렇다면 해당 내용 revert하고 수정하겠습니다 😂

2024-10-10 03:51 UTC, sikutisa commented
1. https://github.com/aliencube/azure-openai-sdk-proxy/pull/330#discussion_r1789120950 에서 말씀드린 것 처럼 404 처리가 필요하지 않은 것 같아서 해당 부분 제외했습니다.
2. 리스트는 `Title`만 기준으로 정렬하도록 변경했습니다.
3. github actions 상에서 `AzureOpenAIProxy.AppHost.Tests.PlaygroundApp.Pages`에 있는 테스트들 중 `~Then_It_Should_Return_HTML_Elements` 테스트들이 전부 실패하는데, 확인 중입니다...

2024-10-10 05:46 UTC, justinyoo commented on src/AzureOpenAIProxy.ApiApp/Endpoints/PlaygroundEndpoints.cs
> +        .Produces(statusCode: StatusCodes.Status404NotFound)
저도 1번 안이 낫다고 생각합니다.

2024-10-10 11:27 UTC, justinyoo approved these changes
고생하셨습니다! LGTM

2024-10-10 11:27 UTC, merged